### ISSUE TITLE
[Bug]: On mobile on initial page load, carousal does not scroll all the way

### ISSUE THREAD

**Issue by muezz** [davidjerleke/embla-carousel#1008]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

The bug occurs when I open my website in a mobile browser (I have tried both Safari and Arc). On initial page load, the carousal does not start from the first item and I am unable to scroll by dragging it.

### Expected Behavior

The behavior should be identical to when the carousal loads in a desktop browser.

### What browsers are you seeing the problem on?

Chrome, Safari

### Version

v8.2.0

### CodeSandbox
[Code Sandbox](https://codesandbox.io/p/devbox/k7ms8q?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm1a96mdf00073b6i4ry9a6ya%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm1a96mdf00023b6iucit2vsw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm1a96mdf00043b6i2r9rayz9%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm1a96mdf00063b6idd6vyd29%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm1a96mdf00023b6iucit2vsw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm1a96mde00013b6i0c7do429%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cm1a96mdf00023b6iucit2vsw%2522%252C%2522activeTabId%2522%253A%2522cm1a96mde00013b6i0c7do429%2522%257D%252C%2522cm1a96mdf00063b6idd6vyd29%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm1a96mdf00053b6in3uwml5f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%257D%255D%252C%2522id%2522%253A%2522cm1a96mdf00063b6idd6vyd29%2522%252C%2522activeTabId%2522%253A%2522cm1a96mdf00053b6in3uwml5f%2522%257D%252C%2522cm1a96mdf00043b6i2r9rayz9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm1a96mdf00033b6ie1b7ci2r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cm1a96mdf00043b6i2r9rayz9%2522%252C%2522activeTabId%2522%253A%2522cm1a96mdf00033b6ie1b7ci2r%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@muezz thanks for your question.

All examples are working just fine on the [documentation website](https://www.embla-carousel.com/examples/predefined/) whether it's on mobile or desktop. So I suggest you double and triple check your CSS and your JavaScript code before creating a bug report.

Thanks for understanding.

**Comment by muezz** [comment]
@davidjerleke The sandbox link points to a clean project with nothing but this component and no CSS by me. The only caveat is that I am using this package _through_ **shadcnUI**. 

So you are right. If you the examples in the docs are working as expected, then I can open the issue on shadcn instead.

Thanks for taking a look.
