### ISSUE TITLE
[Bug]: Slide resize cancels animation

### ISSUE THREAD

**Issue by viters** [davidjerleke/embla-carousel#1039]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

See example: https://codesandbox.io/p/sandbox/embla-carousel-slides-to-scroll-react-forked-qrgrfs?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A49%2C61

If you have dynamic content ```{active === index ? `test${index}` : 'test'}``` then animation onScroll does not work properly. Change it to static `test` and it works perfectly fine.

https://github.com/user-attachments/assets/041b943a-bef8-4669-91bd-36bde20f31af

### Expected Behavior

Honestly I am not sure if this is by design - that animation does reset when slides resize. Maybe it is just impossible to calculate? Just wanted to let you know and see your thoughts.

### What browsers are you seeing the problem on?

Firefox and Chrome.

### Version

8.3.0

### CodeSandbox

https://codesandbox.io/p/sandbox/embla-carousel-slides-to-scroll-react-forked-qrgrfs?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A49%2C61

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@viters thanks for your question. This is expected behavior but you can solve it like this for most use cases:

https://github.com/davidjerleke/embla-carousel/issues/737#issuecomment-1933563728
