### ISSUE TITLE
[Bug]: Autoplay stops on mobile browsers only

### ISSUE THREAD

**Issue by KrisLau** [davidjerleke/embla-carousel#1049]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [X] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

When I swipe/drag on a slide (to go to next/previous slide) with autoplay enabled, the slides stop autoplaying but only on mobile. I have both `stopOnFocusIn` and `stopOnInteraction` set to `false` and it works fine on desktop.

I have tested on both Android and iOS and they both seem to have this same issue and for both, the autoplay works fine before the swipe.

### Expected Behavior

Slide autoplay should continue as usual

### Additional Context

I wasn't really sure what else to mess with other than the stopOn options so I tried enabling and disabling those.

### What browsers are you seeing the problem on?

Chrome, Safari

### Version

8.3.0

### CodeSandbox

https://codesandbox.io/p/sandbox/embla-carousel-autoplay-react-forked-lwwz2h?workspaceId=2aee42b0-5644-4e41-bbff-ffcdcc53479d

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@KrisLau thanks for your question. Please make the sandbox public so I can access it.

**Comment by KrisLau** [comment]
@davidjerleke Sorry didn't realize I had to switch the access setting! I changed it to unlisted, let me know if that works

**Comment by davidjerleke** [comment]
@KrisLau no worries. I've tested the sandbox on iPhones and the autoplay timer only resets on swipe, meaning it starts autoplaying again. It doesn't stop entirely?

**Comment by KrisLau** [comment]
@davidjerleke Super weird, I tried testing the CodeSandbox on my phone and it works fine there as well. I'm not sure it's a difference in the way CodeSandbox renders the website?

Also, I tried creating one that's more similar to my actual website: https://codesandbox.io/p/sandbox/embla-carousel-autoplay-react-forked-5ftvx8?workspaceId=2aee42b0-5644-4e41-bbff-ffcdcc53479d But even that one seems to work on the CodeSandbox but not on my website🙁 

Not sure how exactly to reproduce it 😞

**Comment by KrisLau** [comment]
@davidjerleke Not exactly sure what fixed it but I'm guessing a build related issue? A new unrelated build was made yesterday which seemed to fix it, thanks for taking the time to check the issue!
