### ISSUE TITLE
[Bug]: RangeError Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jperezr21** [davidjerleke/embla-carousel#1064]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

Was not able to reproduce.

### Expected Behavior

No error.

### Additional Context

Started happening after upgrading from 8.3.1 to 8.4.0.

The issue is happening in `updateAndRemoveAccumulatedTime`:
![image](https://github.com/user-attachments/assets/72ede959-2aea-4ad6-9a21-fd528a1e43c4)

Looking at the diff between 8.3.1 and 8.4.0 it seems that this function was introduced in the new release: https://github.com/davidjerleke/embla-carousel/compare/v8.3.1...v8.4.0#diff-8cdac3333b1ac4c0d5bb15d6b666ca387664c871d960fbce4f43704207715deeR47-R51

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### Version

8.4.0

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@jperezr21 thanks for your bug report. Did this happen in production or when your development watch was running?

**Comment by jperezr21** [comment]
In production.

**Comment by davidjerleke** [comment]
@jperezr21 let me know if you find a consistent way of reproducing the problem. Thanks.

**Comment by jperezr21** [comment]
Thank you @davidjerleke!

**Comment by davidjerleke** [comment]
@jperezr21 a bug fix has been released in [v8.5.1](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.5.1). Try upgrading and let me know if the problem goes away.
