### ISSUE TITLE
Vue 3 wrapper

### ISSUE THREAD

**Issue by davidjerleke** [davidjerleke/embla-carousel#17]
# Feature description

Create an **Embla Carousel Vue** wrapper - A component that allows Vue users to consume Embla Carousel.

## Release
Released with [v7.0.0-rc05](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.0-rc05). Documentation will be released with stable v7 but until then you can check out usage instructions below:

# Vue wrapper

Start by installing the Embla Carousel **npm package** and add it to your dependencies.

```shell
npm install embla-carousel-vue --save
```

## The component structure

Embla Carousel provides the handy `emblaCarouselVue` function for seamless integration with Vue. A minimal setup requires an **overflow wrapper** and a **scroll container**. Start by adding the following structure to your carousel:

```html
<template>
  <div class="embla" ref="emblaNode">
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>
</template>

<script>
  import emblaCarouselVue from 'embla-carousel-vue'

  export default {
    setup() {
      const [emblaNode] = emblaCarouselVue()
      return { emblaNode }
    },
  }
</script>
```

## Styling the carousel

The `emblaCarouselVue` function gives us an **emblaNode** to attach to our wrapping element with the classname `embla`, which is needed to cover the scroll overflow. The element with the `container` classname is the scroll body that scrolls the slides. Continue by adding the following **CSS** to these elements:

```html
<style scoped>
  .embla {
    overflow: hidden;
  }
  .embla__container {
    display: flex;
  }
  .embla__slide {
    position: relative;
    flex: 0 0 100%;
  }
</style>
```

## Accessing the carousel API

The `emblaCarouselVue` function takes the Embla Carousel options as the first argument. Additionally, you can access the API with an `onMounted` like demonstrated below:

```html
<template>
  <div class="embla" ref="emblaNode">
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>
</template>

<script>
  import { onMounted } from 'vue'
  import emblaCarouselVue from 'embla-carousel-vue'

  export default {
    setup() {
      const [emblaNode, emblaApi] = emblaCarouselVue({ loop: false })

      onMounted(() => {
        if (emblaApi.value) {
          // Embla API is ready
        }
      })

      return { emblaNode, emblaApi }
    },
  }
</script>
```

## Adding plugins

The `emblaCarouselVue` function also accepts plugins as the second argument. Note that plugins need to be passed in an array like so:

```html
<template>
  <div class="embla" ref="emblaNode">
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>
</template>

<script>
  import emblaCarouselVue from 'embla-carousel-vue'
  import Autoplay from 'embla-carousel-autoplay'

  export default {
    setup() {
      const [emblaNode] = emblaCarouselVue({ loop: false }, [Autoplay()])
      return { emblaNode }
    },
  }
</script>
```

Congratulations! You just created your first Embla Carousel component.

**Comment by davidjerleke** [comment]
Released with [v7](https://github.com/davidjerleke/embla-carousel/releases/edit/v7.0.0).

**Comment by sinneren** [comment]
Is it working with Vue 2 + @nuxtjs/composition-api ?

**Comment by davidjerleke** [comment]
@sinneren thank you for your question. It only works with Vue 3.

**Comment by rojadesign** [comment]
@davidjerleke I'm not sure if I do something wrong and maybe it's a dumb question, but how can I access the `clickAllowed` method?

**Comment by rojadesign** [comment]
@davidjerleke thank you for your response. Here is a link to the [sandbox](https://codesandbox.io/s/prod-frog-6jq2xf?file=/src/components/HelloWorld.vue). I'm not sure if the vue `setup` syntax is a problem or maybe the only problem.

**Comment by davidjerleke** [comment]
@rojadesign I think the setup is not working as expected because importing `onMounted` shouldn't cause any errors. Would you mind trying the following [Vue3 + TypeScript template](https://codesandbox.io/s/vue-3-typescript-template-vpifg?file=/src/index.ts) instead?

**Comment by rojadesign** [comment]
@davidjerleke thank you for your time. Here is the [Vue3 + TypeScript template](https://codesandbox.io/s/busy-grass-koezv1?file=/src/HelloWorld.ts) used - not really working but the same error I have locally also appears there:

`Property 'clickAllowed' does not exist on type 'EmblaCarouselType | HTMLElement'.`
`Property 'clickAllowed' does not exist on type 'HTMLElement'.ts(2339)`

**Comment by davidjerleke** [comment]
@rojadesign yes, this is clearly a TypeScript bug and the typings are wrong. The type for `emblaApi` should be `EmblaCarouselType | null`. I'll have to look into this when possible. Feel free to propose a solution if you want. [The Vue wrapper code is here](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel-vue/src/components/index.ts).

**Comment by spoitler** [comment]
Hello,
Can this work with the api option ? I can't.

**Comment by davidjerleke** [comment]
@spoitler I don’t understand the question. Would you mind clarifying what you mean?

**Comment by spoitler** [comment]
is it necessary to use the setup() function to initialize it ?

**Comment by davidjerleke** [comment]
@spoitler yes I think so.
