### ISSUE TITLE
[Feat]: Build an Angular wrapper

### ISSUE THREAD

**Issue by davidjerleke** [davidjerleke/embla-carousel#18]
Create an Embla Carousel Angular npm package - A wrapper component that allows Angular users to consume Embla Carousel like the React implementation.

~~Please react with --> 👍 if you want this to be implemented.~~

- This will be merged with #627.

**Comment by jbradely** [comment]
Hello , thank you for your efforts to extends the compatibility of the Embla Carousel to Angular users ,
 i know it's an old post but i could'nt find informations on working angular wrapper for embla carousel , i tried many examples (with thumbnais) , it works for the first loaded carousel but got errors with next components load , it has to do with angular life cycles and the way embla carousel is initiated and destroyed once you leave a component . is there any update on this need ? thanks for your attention.

**Comment by davidcetinkaya** [comment]
Hi @jbradely,

Thank you for your question. I don’t know much about Angular, so when I created this issue I was hoping to attract an Angular dev out there, that would want to build a wrapper  in order to enable Angular users to use Embla Carousel in their projects.

There has been some attempts made in issue #71 and #29, but unfortunately it didn’t yield any results.

It’s not like Embla is poorly designed or similar, the React package was very easy to build with the Embla API. But I think we need a seasoned Angular dev that can pull this off and create a CodeSandbox with a working example. I’m willing to assist that person with my deep knowledge of how the Embla Carousel core works.

Best,
David

**Comment by donaldxdonald** [comment]
Hi @davidjerleke ,

Recently, I had the opportunity to utilize embla-carousel in my work to replace Swiper.js and integrated it seamlessly into an Angular project. I must say, I haven't encountered any issues so far.

Then I organize the code for the encapsulating components in [codesandbox](https://codesandbox.io/p/sandbox/recursing-chatelet-l4ykr8). Additionally, I included a few basic examples to showcase its functionality. I hope this contribution proves helpful to you and others who come across your repository.

Thank you for creating such an excellent tool :)

Best regards,
Donald

**Comment by davidjerleke** [comment]
Hi @donaldxdonald,

Thank you for your efforts and sharing that. That's great! I hope that Angular devs find your work useful 🙂. I just want to mention that there's a utility package that all reactive Embla wrappers use (`embla-carousel-react`, `embla-carousel-svelte` and `embla-carousel-vue`) called `embla-carousel-reactive-utils` that you can use if you want. 

All library wrappers are minimal wrappers that just wrap the core `embla-carousel` package for seamless integration and what they do is basically the following:

- Take `options` and `plugins` as parameters.
- They run `emblaApi.reInit()` if `options` or `plugins` change.
- They expose a `ref` for users attach to the DOM themselves. 
- They respect the `globalOptions` feature.
- They expose the **raw** `emblaApi` for maximum flexibility.

I will take the `embla-carousel-react` example to explain:

```ts
import { useRef, useEffect, useState, useCallback } from 'react'
// Feel free to use this in your Angular wrapper 👇 
import {
  areOptionsEqual,
  arePluginsEqual,
  canUseDOM
} from 'embla-carousel-reactive-utils'
import EmblaCarousel, {
  EmblaCarouselType,
  EmblaOptionsType,
  EmblaPluginType
} from 'embla-carousel'

type EmblaViewportRefType = <ViewportElement extends HTMLElement>(
  instance: ViewportElement | null
) => void

export type UseEmblaCarouselType = [
  EmblaViewportRefType,
  EmblaCarouselType | undefined
]

function useEmblaCarousel(
  options: EmblaOptionsType = {},
  plugins: EmblaPluginType[] = []
): UseEmblaCarouselType {
  const storedOptions = useRef(options)
  const storedPlugins = useRef(plugins)
  const [emblaApi, setEmblaApi] = useState<EmblaCarouselType>()
  const [viewport, setViewport] = useState<HTMLElement>()

  const reInit = useCallback(() => {
    if (emblaApi) emblaApi.reInit(storedOptions.current, storedPlugins.current)
  }, [emblaApi])

  useEffect(() => {
    // IF REF IS ATTACHED TO HTML - Initialise Embla and store the emblaApi which will be exposed
    if (canUseDOM() && viewport) {
      // GLOBAL OPTIONS - Make use of global options and pass it to the core library
      EmblaCarousel.globalOptions = useEmblaCarousel.globalOptions
      const newEmblaApi = EmblaCarousel(
        viewport,
        storedOptions.current,
        storedPlugins.current
      )
      setEmblaApi(newEmblaApi)
      return () => newEmblaApi.destroy()
    } else {
      // IF REF IS NOT ATTACHED TO HTML - Set emblaApi to undefined
      setEmblaApi(undefined)
    }
  }, [viewport, setEmblaApi])

 // IF OPTIONS CHANGE - Run emblaApi.reInit()
  useEffect(() => {
    // use areOptionsEqual() from the utils package to compare
    if (areOptionsEqual(storedOptions.current, options)) return
    storedOptions.current = options
    reInit()
  }, [options, reInit])

  // IF PLUGINS CHANGE - Run emblaApi.reInit()
  useEffect(() => {
    // use arePluginsEqual() from the utils package to compare
    if (arePluginsEqual(storedPlugins.current, plugins)) return
    storedPlugins.current = plugins
    reInit()
  }, [plugins, reInit])

  // EXPOSE - 0: A ref to attach to the DOM element that will be the carousel
  // EXPOSE - 1: The raw emblaApi
  return [<EmblaViewportRefType>setViewport, emblaApi]
}

useEmblaCarousel.globalOptions = <EmblaOptionsType | undefined>undefined

export default useEmblaCarousel
```

### Usage:

```tsx
import React, { useEffect } from 'react'
import useEmblaCarousel from 'embla-carousel-react'
import Autoplay from 'embla-carousel-autoplay'

export const EmblaCarousel = () => {
  // Usage of the useEmblaCarousel() wrapper
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: false }, [Autoplay()])

  useEffect(() => {
    if (emblaApi) {
      console.log(emblaApi.slideNodes()) // Access API
    }
  }, [emblaApi])

  return (
    <div className="embla" ref={emblaRef}>
      <div className="embla__container">
        <div className="embla__slide">Slide 1</div>
        <div className="embla__slide">Slide 2</div>
        <div className="embla__slide">Slide 3</div>
      </div>
    </div>
  )
}
```

Best,
David

**Comment by donaldxdonald** [comment]
Thanks for your reply. Actually the code example above is based on `embla-carousel@7` and compatible to Angular 13~16. Because I noticed that this version of `embla-carousel` has a significant number of downloads on npm. (Haven't used version 8 yet.)

I made some modifications to the sample code based on your suggestions, and I will provide an explanation below. The paradigm of the Angular utility library may be somewhat different from other frameworks.

## 1. Take `options` and `plugins` as parameters.

```typescript

@Component({
  ...
})
export class EmblaComponent implements AfterViewInit, OnChanges, OnDestroy, EmblaOptionsType {
  @Input() active: EmblaOptionsType['active'];
  @Input() align: EmblaOptionsType['align'];
  @Input() axis: EmblaOptionsType['axis'];
  @Input() container: EmblaOptionsType['container'];
  @Input() slides: EmblaOptionsType['slides'];
  @Input() containScroll: EmblaOptionsType['containScroll'];
  ...

}
```

Initially, I would think that encapsulating options into more granular props would be more convenient because often we need to dynamically update a specific option. But It is acceptable to ensure consistency in the coding style of the main library. Therefore, I have made the necessary modifications to it.

```typescript

@Component({
  ...
})
export class EmblaComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() options?: EmblaOptionsType;
  @Input() plugins?: EmblaPluginType[];
  ...

}
```



## 2. They run `emblaApi.reInit()` if `options` or `plugins` change.

This step will be executed within the `ngOnChanges` lifecycle hook.

```typescript

@Component({
  ...
})
export class EmblaComponent implements AfterViewInit, OnChanges, OnDestroy {
  ...
  ngOnChanges(changes: SimpleChanges): void {
    const { plugins, options } = changes;
    if (plugins || options) {
      this.ngZone.runOutsideAngular(() => {
        this.reInit(options?.currentValue, plugins?.currentValue);
      });
    }
  }
  
  reInit(options?: EmblaOptionsType, plugins?: EmblaPluginType[]) {
    if (!this.emblaApi) {
      return;
    }

    this.emblaApi.reInit(options, plugins);
  }
  ...

}  

```



## 3. Expose  `ref`  and  `emblaApi`

I have changed the injection of  `ElementRef` in the component to be public. This allows external access to its associated DOM element.

### Usage

```html
<!-- app.component.html -->

<ngx-embla #emblaCarousel>
  <div ngx-embla-slide *ngFor="let item of defaultSlides" >{{ item + 1 }}</div>
</ngx-embla>

```

```typescript
// app.component.ts
@Component({
  ...
})
export class AppComponent {

  @ViewChild('emblaCarousel')
  emblaComponent: EmblaComponent
  
  someMethod() {
    // DOM
    const ref = this.emblaComponent._elementRef.nativeElement
    // emblaApi
    const emblaApi = this.emblaComponent.emblaApi
  }

}  
```



## 4. They respect the `globalOptions` feature.

I have implemented this feature using an Angular-approach: dependency injection. I provided an injection token called `EMBLA_OPTIONS_TOKEN`, and set the `globalOptions` by using `forRoot` when importing the `EmblaModule`.

```typescript
// app.module.ts

@NgModule({
  ...
  imports: [
    ...
    EmblaModule.forRoot({
      startIndex: 2,
    }),
  ],
  ...
})
export class AppModule {}

```

```typescript
// embla.component.ts
@Component({
  ...
})
export class EmblaComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() options?: EmblaOptionsType;
  @Input() plugins?: EmblaPluginType[];

  @Output() emblaEvent = new EventEmitter<EmblaEventType>();

  emblaApi!: EmblaCarouselType;

  constructor(
    _elementRef: ElementRef<HTMLElement>,
    private ngZone: NgZone,
    @Inject(EMBLA_OPTIONS_TOKEN) globalOptions: EmblaOptionsType | undefined
  ) {
    // GLOBAL OPTIONS - Make use of global options and pass it to the core library
    EmblaCarousel.globalOptions = globalOptions;
  }

  ngAfterViewInit(): void {
    this.emblaApi = EmblaCarousel(
      this._elementRef.nativeElement,
      this.options,
      this.plugins
    );
    this.bindEvents(this.emblaApi);
  }
  ...

}  
```


The complete code and usage example have been updated on [**CodeSandbox**](https://codesandbox.io/p/sandbox/recursing-chatelet-l4ykr8).

**Comment by davidjerleke** [comment]
Hi @donaldxdonald,

Thank you for a detailed response 👍! I would like to share some thoughts about it but I have a ton of things to do right now, so I will get back to you as soon as possible. Thank you for your patience and efforts!

Best,
David

**Comment by donaldxdonald** [comment]
@davidjerleke  😃 Thanks for getting back to me. No worries, take your time, no rush on my end. It's all good.

**Comment by davidjerleke** [comment]
Hi @donaldxdonald,

Thanks for your patience. Here are my thoughts about your comments: 

### 1. Take `options` and `plugins` as parameters.

> Initially, I would think that encapsulating options into more granular props would be more convenient because often we need to dynamically update a specific option. But It is acceptable to ensure consistency in the coding style of the main library. Therefore, I have made the necessary modifications to it.

That's great. The Angular approach is now aligned with all other library wrappers (React, Svelte, Vue). Thank you 👍!

---

### 2. They run `emblaApi.reInit()` if `options` or `plugins` change.

> This step will be executed within the `ngOnChanges` lifecycle hook.

Hmm yes, but, **when** does that hook run? I'm going to take a guess and say on reference change like most other reactive libraries do. So:

```ts
let options = { loop: false };

options = { loop: false }; // This would fire the ngOnChanges hook right, even though options actually didn't change?
```

That's why the `embla-carousel-reactive-utils` package is there. Running the code through the utils:

```ts
import {
  areOptionsEqual,
  arePluginsEqual,
  canUseDOM
} from 'embla-carousel-reactive-utils'
```
Will ensure that Embla won't do unnecessary work and only re-initialize when options **actually change**. Same goes for the  plugins. You can see **how it's done** in the [React package here](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel-react/src/components/useEmblaCarousel.ts#L50-L60) and maybe how it's done in the [Svelte package](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel-svelte/src/components/emblaCarouselSvelte.ts#L52-L68) will be the one most similar to the Angular approach.

--- 

### 3. Expose  `ref`  and  `emblaApi`

> I have changed the injection of  `ElementRef` in the component to be public. This allows external access to its associated DOM element.

```html
<!-- app.component.html -->

<ngx-embla #emblaCarousel>
  <div ngx-embla-slide *ngFor="let item of defaultSlides" >{{ item + 1 }}</div>
</ngx-embla>
```

This will lead to problems and trust me, I'm speaking from experience. The React package did this back in the days and I had to change that. Devs will complain about the encapsulating of DOM elements and say:

- Hey, I use Tailwind and need access to the container element to set my own classes there. 
- Hey, I need to be able to choose other elements but now it can only be a `<div>`.

We need to free the ref. All other library wrappers (React, Vue, Svelte) call it `emblaRef` so it would be great to rename it to that and devs should be able to attach it freely like this:

```html
<div class="embla">
  <div class="embla__container" #emblaRef>
    <div class="embla__slide">Slide 1</div>
    <div class="embla__slide">Slide 2</div>
    <div class="embla__slide">Slide 3</div>
  </div>
</div>

```

---

### 4. They respect the `globalOptions` feature.

I have implemented this feature using an Angular-approach: dependency injection. I provided an injection token called `EMBLA_OPTIONS_TOKEN`, and set the `globalOptions` by using `forRoot` when importing the `EmblaModule`.

I'm going to trust you on this because I don't know much about Angular ways of doing things. However, I would like to ask if there's a possibility to re-think the naming here to make it more clear that we're setting **global options**? Just guessing a bit here but wouldn't this read better?

```ts
@NgModule({
  ...
  imports: [
    ...
    EmblaModule.globalOptions({
      startIndex: 2,
    }),
  ],
  ...
})
```

---

Thanks a bunch you for your time!

Best,
David

**Comment by donaldxdonald** [comment]
Hi @davidjerleke,

Thank you for your reply. Your advice is very valuable. Here is my response to your comment.

### 1. Take `options` and `plugins` as parameters.

:)

### 2. They run `emblaApi.reInit()` if `options` or `plugins` change.

```typescript
let options = { loop: false };

options = { loop: false }; // This would fire the ngOnChanges hook right, even though options actually didn't change?
```

As you say, this does cause change detection in `ngOnchanges` hook. The `embla-carousel-reactive-utils` looks good, but its peerDependencies require `embla-carousel@8` , and it doesn't seem to have much use for APIs that are specific to this version. 

I copied the `utils.ts` file to the `embla-carousel@7` example project, and it also worked successfully.

And you're right on that Embla won't do unnecessary work and only re-initialize when options **actually change**.

### 3. Expose `ref` and `emblaApi`

You're totally right. Recently, I discovered that the component wrapper (Template) is unnecessary. So I've removed the `EmblaComponent` and I'm now using only the `EmblaDirective`. In Angular, `Component` = `Template` + `Directive` .

This time, I have updated the example to include two usages - the traditional `NgModule` approach and the new standalone usage.

```typescript
// app.component.ts
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    CommonModule,

    // NgModule Usage
    // EmblaModule.forRoot({
    //   startIndex: 2,
    // }),

    // Standalone Directive Usage
    // with `provideEmblaGlobalOptions`
    EmblaDirective,
  ],
  providers: [
    provideEmblaGlobalOptions({
      startIndex: 2,
    }),
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

Access to `emblaRef` is similar to other library wrapper.

```html
<div class="embla" ngx-embla #emblaRef="emblaNode">
  <div class="embla__container">
    <div class="embla__slide">1</div>
    <div class="embla__slide">2</div>
    <div class="embla__slide">3</div>
  </div>
</div>
```



### 4. They respect the `globalOptions` feature.

The `forRoot` naming convention is [Angular's singleton pattern](https://angular.io/guide/singleton-services#the-forroot-pattern). Therefore, it may be beneficial to adhere to the official approach as it would be familiar to Angular developers.

To facilitate the usage of the standalone directive, I have added a `provideEmblaGlobalOptions` function that sets up a global options provider. This follows the official approach, similar to  [`provideRouter`](https://angular.io/api/router/provideRouter).

```typescript
// app.component.ts
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    CommonModule,
    // Standalone Directive Usage
    // with `provideEmblaGlobalOptions`
    EmblaDirective,
  ],
  providers: [
    provideEmblaGlobalOptions({
      startIndex: 2,
    }),
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```



The new full code example is here. [Codesandbox](https://codesandbox.io/p/sandbox/embla-angular-demo-new-q2xc6q)

Thanks again for your advice!

**Comment by davidjerleke** [comment]
Hi again @donaldxdonald,

I think it's looking really great now! Thank you for being open to input 👍. In my opinion, it's very much aligned with the Embla vision and the other library wrappers (React, Svelte, Vue). About this:

> ### 4. They respect the `globalOptions` feature.
>
> The `forRoot` naming convention is [Angular's singleton pattern](https://angular.io/guide/singleton-services#the-forroot-pattern). Therefore, it may be beneficial to adhere to the official approach as it would be familiar to Angular developers.
>
> To facilitate the usage of the standalone directive, I have added a `provideEmblaGlobalOptions` function that sets up a global options provider. This follows the official approach, similar to  [`provideRouter`](https://angular.io/api/router/provideRouter).

This also looks great. And I just want to mention again that I'm not familiar with the Angular way of doing things so if just `forRoot` is how it should be I trust you 🙂.

### I have one last question about the contents of the Angular wrapper❓
> As you say, this does cause change detection in ngOnchanges hook. The embla-carousel-reactive-utils looks good, but its peerDependencies require embla-carousel@8 , and it doesn't seem to have much use for APIs that are specific to this version.
>
> I copied the utils.ts file to the embla-carousel@7 example project, and it also worked successfully.

I might be missing something here but why don't you upgrade `embla-carousel` to the latest version `v8.0.0-rc14`? Don't let RC (release candidate) scare you because stable `v8` has a lot of new great features and is just around the corner. It's very stable now (only one or two small things might change).

If you choose to do this, you can make use of the **npm package** `embla-carousel-reactive-utils` instead of having the code locally in your Angular wrapper. It's more future proof with just bumping the version, instead of copy pasting the code if the package were to get updates.

### Where do you want to go from here 🤷‍♂️?
I think this is a great initiative from your side. The Angular wrapper is now aligned with the Embla vision. 

**What do you want to do now?**
You can either: 

- Create your own repository for this
- Or we can add it to the `embla-carousel` repository where all the core package and all other official packages like library wrappers and (almost) all plugins reside. 

**I think this should be the official Embla Angular wrapper**. If you're interested in this, I will share some information that's good to know **before** you **accept** this or not. Let me know what you think 🙂!

Cheers,
David

**Comment by donaldxdonald** [comment]
Hi @davidjerleke ,

I'm glad to see what you said above.

> ### I might be missing something here but why don't you upgrade `embla-carousel` to the latest version `v8.0.0-rc14`?

Like I said above, initially I was just using embla for work reasons and saw that no one on GitHub was sharing the Angular wrapper, so I'm sharing my own use case in the hope that it will help other developers. 😃 

Also for work reasons, the application needs to reach a large number of users, including some "legacy" browsers, and I saw that [**`embla@8` would not support some of the older browsers**](https://github.com/davidjerleke/embla-carousel/issues/492#issuecomment-1573568106), so I just used `embla@7` as an example (adding v8 support would be easy on top of that), and as I said above, `embla@7` is still getting significant downloads from NPM, and there are probably a lot of people out there who would want to use an Angular wrapper based on `embla@7` as well.

Anyway, my point is that upgrading `embla-carousel` to v8 is no problem, just a few code changes. 

> ### Where do you want to go from here 🤷‍♂️?

It's an honor for me to have this as an official Angular wrapper!🤩  I'm very happy to contribute code to the community, and I'm very interested in that. Rather than creating my own repository, I thought it would be more appropriate to add it to the `embla-carousel` repository so that more developers can find it and participate in it.

So I just need to open a PR directly to add the organized code to the repository right?

Best regards,
Donald

**Comment by davidjerleke** [comment]
Hi @donaldxdonald,

> Like I said above, initially I was just using embla for work reasons and saw that no one on GitHub was sharing the Angular wrapper, so I'm sharing my own use case in the hope that it will help other developers. 😃 
>
> Also for work reasons, the application needs to reach a large number of users, including some "legacy" browsers, and I saw that [**`embla@8` would not support some of the older browsers**](https://github.com/davidjerleke/embla-carousel/issues/492#issuecomment-1573568106), so I just used `embla@7` as an example (adding v8 support would be easy on top of that), and as I said above, `embla@7` is still getting significant downloads from NPM, and there are probably a lot of people out there who would want to use an Angular wrapper based on `embla@7` as well.
>
> Anyway, my point is that upgrading `embla-carousel` to v8 is no problem, just a few code changes.

I see 👍. Sorry for repeating the question. I just want to mention that [Safari 13 support was added recently](https://github.com/davidjerleke/embla-carousel/issues/492#issuecomment-1738595749), just forgot to update the issue you linked to.

---

## Before we continue

> It's an honor for me to have this as an official Angular wrapper!🤩 I'm very happy to contribute code to the community, and I'm very interested in that. Rather than creating my own repository, I thought it would be more appropriate to add it to the embla-carousel repository so that more developers can find it and participate in it.
>
> So I just need to open a PR directly to add the organized code to the repository right?

I'm very glad to hear that 🙂! Before you go ahead and do that, I have a few things that I need you to read, understand and accept. I just want to be clear with some things so they don't come as a surprise. It's a bit of a read so please bare with me:

### General information

- When contributing, your code will be used as part of an open source product if merged. By submitting a Pull Request, **you are giving your permission** for your code to be integrated into Embla Carousel as part of an open source product. This basically means is that as long as your package is part of this repository, the license for it has to be [MIT](https://github.com/davidjerleke/embla-carousel/blob/master/LICENSE).

- If you approve, your **GitHub profile image with a link to it** will be added to the [README special thanks section](https://github.com/davidjerleke/embla-carousel#special-thanks).

- Of course, the author will be you because **all the credit for this wrapper goes to you**. All README files for each and every package in this repository are generated automatically, and the author is [automatically injected](https://github.com/davidjerleke/embla-carousel/blob/master/scripts/create-readmes/readme-template.md?plain=1#L109) from the `package.json`. 

- When your PR is merged you don't automatically commit to any responsibilities. Feel free to contribute as much or as little you want. That's 100% up to you.

- Once the package is released, you will be able to **track usage statistics** to some extent through GitHub's network dependents view. Here's the [link to the dependents view](https://github.com/davidjerleke/embla-carousel/network/dependents?package_id=UGFja2FnZS00MzA0OTI2MDU%3D) for the `embla-carousel-react` package.  Example:

<img width="1463" alt="usage-statistics" src="https://github.com/davidjerleke/embla-carousel/assets/11529148/e405e687-b0d9-4cb1-97fc-1ce3d60d751a">

### Code specific information

- All official library wrappers are prefixed with `embla-carousel-<wrapperName>`. This goes for plugins too. So in this case, the Angular wrapper should be named `embla-carousel-angular`.

- All library wrapper packages have the same `rollup.js` structure which bundles the code. Check [this example out](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel-svelte/rollup.config.js). It's not mandatory to follow this but adhering to it has the benefit of developers being familiar with the bundling in this repository.

- All packages have the same folder structure. The code for each resides in a `src` folder. Inside that folder, there's an `index.ts` file that **exports** the wrapper itself and some useful types for the end user. The `components` folder holds all separate components and the wrapper code. This structure **isn't mandatory**, but adhering to it has the benefit of developers being familiar with the structure for each package. Examples:

<img width="1137" alt="folder-structure-svelte" src="https://github.com/davidjerleke/embla-carousel/assets/11529148/76d3a3b0-4f4f-4f15-af01-3f084a50ac2b">

<img width="1136" alt="folder-structure-vue" src="https://github.com/davidjerleke/embla-carousel/assets/11529148/80d35a5d-0ef7-4022-a69d-79a385fc86cc">

### Release cycle information
When creating a release with `yarn version:patch|minor|major`, the command automatically bumps every Embla package to the new version. For example, this means that a minor version bump in a plugin package or library wrapper will cause all packages to get that version bump so every package in the repository match. You might ask isn't that strange? Why does one package version affect another package of which contents hasn't changed? 

**Well, the answer is:**
It's because of practical reasons. I'm working on this project on my spare time (which is quite limited) so no one is paying me for my time. There's no way in the world that I would want to spend a lot of spare time trying to communicate to Embla users which plugin version is compatible with this version of Embla, or what library wrapper version is compatible with the core package. I'd rather spend my time improving this library, the docs and the examples. It's just easier to say that if you're using embla-carousel v8.0.1 your plugins should all match that version. Example:

- embla-carousel v8.0.1
- embla-carousel-autoplay v8.0.1

...or:

- embla-carousel-react v8.0.1
- embla-carousel-autoplay v8.0.1

---

Phew. That's a long read. Sorry about that. Thanks a lot for your time and let me know if this makes sense and/or if you have more questions.

Best,
David

**Comment by donaldxdonald** [comment]
Dear @davidjerleke ,
Thank you for the detailed guide, the content is all very clear. I have a lot of understanding and respect for contributing code in your spare time.

Sorry, I'm currently on a one-week Chinese National Day holiday. However, once the holiday is over, I will proceed with advancing the new code pull request as discussed ASAP.

Thank you for your understanding, and I look forward to collaborating with you on this project.

Best regards,
Donald
