### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by manlaingelo** [davidjerleke/embla-carousel#305]
### Bug is related to

- [x] embla-carousel-react

### Embla Carousel version

- v6.2.0 (Latest, 22/04/22)

### Describe the bug

Unable to install embla-carousel-react in react v18 project

### Steps to reproduce

1. Open react v18 project 
2. Install package with `npm install embla-carousel-react --save`

### Expected behavior

Successfully resolve react up to v18.

### Additional context

<img width="564" alt="image" src="https://user-images.githubusercontent.com/73154902/164586480-9df0b20f-e6f7-477e-a707-2d8c142c4d1e.png">

**Comment by davidcetinkaya** [comment]
Hi @manlaingelo,

Thank you for creating this issue. React 18 support will be released with version 7. You can track the progress of version 7 here:

- #298 

Best,
David

**Comment by manlaingelo** [comment]
Thank you for your quick response. I really appreciate it. 🙇‍♂️✨✨

**Comment by PerryRylance** [comment]
Sterling work, thanks David

**Comment by davidjerleke** [comment]
Hi @manlaingelo and @PerryRylance, 

If you're interested: [v7.0.0-rc01](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.0-rc01) has been released. Feel free to try it out.

Cheers,
David

**Comment by OwenMelbz** [comment]
Thanks for the snappy response!

I've added a reInit() call after the animations are complete and this does seem to solve the issues :)

Just curious if there is an option to opt back into usage of % to preserve any backwards compatibility?

Many thanks

**Comment by davidjerleke** [comment]
Hi @OwenMelbz,

Ok so seems like my guess was correct then. No unfortunately not. It’s a breaking change in other words. In most cases it will work as before but carousels inside elements that are toggled visible (like modals) have to be tested. If you look at the bugs section in the v7 issue:

- #298 

You will see that the relative unit caused bugs in some cases. That’s why the move to `px` was made. Keeping percentage as an option would increase bundle size and people think a small bundle size is very important. I have to weigh that in every time I make changes.

Best,
David

**Comment by davidjerleke** [comment]
Released with [v7](https://github.com/davidjerleke/embla-carousel/releases/edit/v7.0.0).
