### ISSUE TITLE
Svelte Wrapper

### ISSUE THREAD

**Issue by Yofou** [davidjerleke/embla-carousel#307]
Hey Guys, I'm Yofou but formally by Nathan, I love the work you guys did here with Embla-Carousel, it makes developers life so much easier when it comes to making carousel's, allowing them mostly to only focus on the styling and controls rather than the logic!

I loved it so much that I made a Svelte wrapper called [Svelte-Embla](https://svelte-embla.vercel.app/), the best case scenario is that it becomes an official wrapper rather than a community made one, which is why I made this issue post, basically the question is simple, would you guys be interested in such a preposition

(ps I hope you guys don't me using some of the assets of your docs, I wanted to keep my docs closely similar to yours as that would make the most sense to me, if this is an issue though, let me know and ill change assets to something different).

**Comment by davidcetinkaya** [comment]
Hello Nathan (@Yofou),

Thank you ⭐! I'm very happy that you shared this, what a great initiative and well done 🎉! I'm the creator of Embla Carousel and along the way we've had and still have awesome people contributing with great things to this project: @gunnarx2, @xiel and @nikrowell just to mention a few.

> the best case scenario is that it becomes an official wrapper rather than a community made one, which is why I made this issue post, basically the question is simple, would you guys be interested in such a preposition

An official Svelte wrapper for Embla would be fantastic. If it's ok with you, I would like to share the vision of Embla Carousel and get a conversation going about what we should aim for?

Best,
David

**Comment by Yofou** [comment]
Thank you responding so swiftly @davidcetinkaya 

Sure that sound's all good with me, where would you like to hold this conversation?

**Comment by davidcetinkaya** [comment]
@Yofou, for example, we can start a [discussion](https://github.com/davidcetinkaya/embla-carousel/discussions). One benefit of having the conversation here on GitHub is that people can join the conversation if they have ideas they want to share. Another option would be to have an email conversation. But I’m open to suggestions if you have something different in mind.

Let me know what you prefer 🙂.

Cheers,
David

**Comment by th-km** [comment]
As a new Svelte user and a big fan of Embla, I'd love to see an official Svelte wrapper.
Where should I look to keep track of the progress?

Best,
T

**Comment by Yofou** [comment]
Hey @th-km I unfortunately don't have an amazing amount of free-time currently as I moved my job over to a new company recently and been hyper focusing on that. I completely forgot about keeping on top of this.

if you wish to use embla with svelte, my package is up and is usable (I use it all the time for personal project) [svelte-embla.vercel.app](https://svelte-embla.vercel.app/)

I'll find the time today about opening up that discussion with @davidjerleke and we'll see where things go :).

**Comment by th-km** [comment]
Thanks for the update @Yofou, and good luck with the new job! 
I'll keep an eye on the discussion then 😉

**Comment by davidjerleke** [comment]
Hi @Yofou,

Congratulations on your new job! Let me do some Svelte research and I'll get back to you on the discussion you created:

- #333 
 
Se you over there. @th-km and anyone else interested in seeing a Svelte wrapper for Embla can follow the progress there too.

Cheers,
David

**Comment by davidjerleke** [comment]
Released with [v7](https://github.com/davidjerleke/embla-carousel/releases/edit/v7.0.0).
