### ISSUE TITLE
`examples/inspiration` section on the documentation website displays a blank page on scroll

### ISSUE THREAD

**Issue by CamilleHbp** [davidjerleke/embla-carousel#309]
### Bug is related to

- [ ] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [x] embla-carousel-docs (documentation website)

### Embla Carousel version

- v1.28.1 ? I don't know which one you use on your website :)

### Describe the bug

- As soon as I scroll the `examples/inspiration` section, I get a blank page and a console error

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/11173924/167077153-abc8014f-b91e-404e-a441-5184b4a65764.png">

### CodeSandbox

-  [https://www.embla-carousel.com/examples/inspiration/](https://www.embla-carousel.com/examples/inspiration/)

### Steps to reproduce

1. Go to [https://www.embla-carousel.com/examples/inspiration/](https://www.embla-carousel.com/examples/inspiration/)
2. Scroll

### Expected behavior

- It should not display a blank page :D

### Additional context

- Broswer: Chrome, Version 100.0.4896.127 (Official Build) (x86_64)
- Device: Macbook Pro MacOS Big Sur v11.6.5

**Comment by davidjerleke** [comment]
Thank you for your bug report @CamilleHbp! I’ll look into this as soon as possible.

Cheers,
David

**Comment by davidjerleke** [comment]
Hello again @CamilleHbp,

Thank you very much for noticing this so quickly. I'm working on **v7**:

- #298 

...so the Gatsby cache that was preserved from the v7 branch made its way into the master branch.

Cheers,
David
