### ISSUE TITLE
slidesToScroll different drag behavior in v4 and v6

### ISSUE THREAD

**Issue by rezakho** [davidjerleke/embla-carousel#315]
### Feature request is related to

- [x] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Is your feature request related to an issue? yes

- slidesToScroll option in v6 limit drag scroll but in v4 does not

### Describe the solution you'd like

- I suggest adding a special option like slidesToScrollDrage for drag

**Comment by davidjerleke** [comment]
Hi @rezakho,

Thank you for your question. You can set the [skipSnaps option](https://www.embla-carousel.com/api/options/#skipsnaps) to `true` if you want the **v6** drag interactions to behave like **v4**.

On a side note: Please respect [my decision](https://github.com/davidjerleke/embla-carousel/issues/187#issue-873669552) here.

Best,
David

**Comment by rezakho** [comment]
👍🏻 
Thanks
