### ISSUE TITLE
Embla + Framer Motion + Flubber makes slides "disappear" 

### ISSUE THREAD

**Issue by MartinConde** [davidjerleke/embla-carousel#317]
### Bug is related to

Using Embla in combination with Framer Motion and Flubber

### Embla Carousel version

- v6.2.0

### Describe the bug

Not really a bug, more like something I can't seem to figure out.

Basically, I've got images with a clippath inside my slides. When a slide becomes active, the clippath transitions to another shape using flubber and framer motion. This part works just fine.

The issue is that slides become "invisible" at times but show up after a second or so. While sliding through, slides will be dropped and re-appear. If I comment out the svg, the sliding works perfectly again.

I've tried playing with re-initting the slider at different points but can't figure out where I'm going wrong. I'm aware that this issue isn't emblas "fault" but figured I'd ask in case someone has an idea.

### CodeSandbox

https://codesandbox.io/s/embla-framer-test-llgvds?file=/src/components/EmblaCarousel/slide.js

### Steps to reproduce

1. Checkout the CodeSandbox, preferably in full screen mode so it's easier to see the issue with the transitions.
2. Open slide.js and remove or comment out the svg (marked with a comment in the code)
3. Re-open CodeSandbox in full screen mode and see the difference

### Expected behavior

Slides shouldn't drop/disappear, basically all should work like it does when the svg is removed

**Comment by MartinConde** [comment]
Hi @davidjerleke 

Awesome thanks a lot, guess I'll just go for v7 then. Would love to figure out the solution in v6 but been fiddling with it a lot and no patience for now to keep trying if v7 fixes it perfectly.

**Comment by davidjerleke** [comment]
I'm keeping this open until the release of:

- #298

**Comment by davidjerleke** [comment]
Hello @MartinConde,

If you're interested: [v7.0.0-rc01](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.0-rc01) has been released.

Cheers,
David

**Comment by davidjerleke** [comment]
Released with [v7](https://github.com/davidjerleke/embla-carousel/releases/edit/v7.0.0).
