### ISSUE TITLE
canScrollNext does not stop soon enough if more than one slide is visible

### ISSUE THREAD

**Issue by tordans** [davidjerleke/embla-carousel#341]
### Bug is related to

- embla-carousel (core package)
- embla-carousel-react
- embla-carousel-docs (documentation website)

### Embla Carousel version

- v6.2.0

### Describe the bug

Try using the slider at https://radwege-check.de/

Code: https://github.com/FixMyBerlin/fixmy.safetycheck/blob/develop/src/components/Homepage/Presets/PresetSlider.tsx

The issue – as far as I understand it – is, that [`canScrollNext`](https://www.embla-carousel.com/api/methods/#canscrollnext) does not handle the special case when more than one slide is visible at the same time.

I worked around it with this custom code for desktop. But that only seems to work well for the first tab of the sliders which has 6 slides. The one with 5 slides "over scrolls", which might be because my check does not look if the slide count is odd/even.

### Expected behavior

I am looking for a way to use `canScrollNext` that will allow to disable the button once all available slides are visible to the user.

### Screenshot

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/111561/181296941-25143230-6ec4-4f24-9d32-a84d786fc331.png">

**Comment by davidjerleke** [comment]
Hi @tordans,

Thank you for your question.

> The issue – as far as I understand it – is, that [canScrollNext](https://www.embla-carousel.com/api/methods/#canscrollnext) does not handle the special case when more than one slide is visible at the same time.

[`canScrollNext`](https://www.embla-carousel.com/api/methods/#canscrollnext) and [`canScrollPrev`](https://www.embla-carousel.com/api/methods/#canscrollprev) have nothing to do with what slides are in view or not. It is **purely index based** and will blindly follow the scroll snaps that Embla creates based on what options you pass to the carousel instance.

If I understand you correctly you're looking for the [`containScroll`](https://www.embla-carousel.com/api/options/#containscroll) options:

> Clear leading and trailing empty space that causes excessive scrolling. Use `trimSnaps` to only use snap points that trigger scrolling or `keepSnaps` to keep them.

```ts
const [emblaRef, emblaApi] = useEmblaCarousel({
  containScroll: 'trimSnaps',
  ...// other options
})
```

Let me know if this is what you're looking for.

Best,
David

**Comment by davidjerleke** [comment]
Hi @tordans,

Have you had the chance to read [my response](https://github.com/davidjerleke/embla-carousel/issues/341#issuecomment-1198970463)?

Best,
David

**Comment by davidjerleke** [comment]
I'm closing this as resolved because due to lack of response. Feel free to reopen this if the provided solutions wasn't what you were looking for. If that's the case, please provide clear instructions of what you want to achieve.

**Comment by davidjerleke** [comment]
I'm closing this as resolved because due to lack of response. Feel free to reopen this if the provided solutions wasn't what you were looking for. If that's the case, please provide clear instructions of what you want to achieve.
