### ISSUE TITLE
Active option not working

### ISSUE THREAD

**Issue by joaopluis** [davidjerleke/embla-carousel#355]
### Bug is related to

- [x] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- v7.0.0

### Describe the bug

- If `active` is set to `false`, either in the main object or in one of the breakpoints, the error `Cannot read properties of undefined (reading 'filter')` appears.

### CodeSandbox

- https://codesandbox.io/s/embla-carousel-default-vanilla-forked-6byjny

### Steps to reproduce

1. Open the Sandbox
2. See error

### Expected behavior

- There is no error and slider is disabled

### Additional context

- Problem showed up in the usecase where slider is disabled by default and enabled in a breakpoint. Could reduce it to only having `active: false`.

**Comment by davidjerleke** [comment]
Hi @joaopluis,

Thank you very much for reporting this. I can confirm that this is a bug. I'll ship a fix soon and will let you know when I'm done.

Best,
David

**Comment by davidjerleke** [comment]
Hi again @joaopluis,

I just released [v7.0.1](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.1) which includes a bugfix for this bug. Please update your package and let me know if it's working as expected now.

Best,
David

**Comment by davidjerleke** [comment]
Hi @joaopluis,

Let me know if you're intending to confirm the bug fix or not.

Cheers,
David

**Comment by avaleriani** [comment]
@davidjerleke I had this problem and after updating to v7.0.3 can confirm the issue is fixed. Thank you!

**Comment by joaopluis** [comment]
Sorry, was not able to respond earlier!

But as said before, I confirm the fix. Thank you for your quick response!

**Comment by davidjerleke** [comment]
Thanks for confirming guys (@joaopluis @avaleriani).

Cheers,
David
