### ISSUE TITLE
Autoplay jump parameter

### ISSUE THREAD

**Issue by davidjerleke** [davidjerleke/embla-carousel#357]
### Feature request is related to

- [x] embla-carousel-autoplay

### Is your feature request related to an issue?

There's no way to utilize the jump parameter that [`embla.scrollNext()`](https://www.embla-carousel.com/api/methods/#scrollnext) and [`embla.scrollPrev()`](https://www.embla-carousel.com/api/methods/#scrollprev) accepts because these are invoked internally in the autoplay plugin.

### Describe the solution you'd like

Add a `boolean` **jump option** that determines the default behaviour - if transitions should jump or not.

```ts
const options = { loop: true }
const embla = EmblaCarousel(emblaNode, options, Autoplay({ jump: true }))
```

Also allow to override the default jump behaviour using the autoplay API: 

```ts
const embla = EmblaCarousel(emblaNode, options, Autoplay({ jump: true })) // autoplay will jump when it starts here

embla.plugins().autoplay.play(false) // <-- override defaultJump and start animating
```

### Additional context
Feel free to join the conversation if you have anything to add. 

### Thanks
Thanks @th-km for the idea 💡:

- #354

**Comment by davidjerleke** [comment]
Hi @th-km,

Here's an implementation of the **jump option** and the `play(jump: boolean)` method **jump override parameter**:

- [CodeSandbox code](https://codesandbox.io/s/embla-carousel-default-react-forked-66kdfp)
- [CodeSandbox app view](https://66kdfp.csb.app/)

Let me know if it's working as expected and if this was what you had in mind.

Best,
David

**Comment by th-km** [comment]
Hi @davidjerleke, Sorry for the late reply, I'm just back from a trip.

This is exactly what I need in a current project, and it works as expected.
Thank you so much for doing this in such a short amount of time!

**Comment by davidjerleke** [comment]
Hi @th-km,

> Sorry for the late reply, I'm just back from a trip.

Not a problem. We all have a life 😉.

I just released this feature with [v7.0.2](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.2). Give it a go if you want and let me know if it works as expected. Additionally, if you have a moment, I would very much appreciate if you could check out the documentation additions and see if the explanations make sense to you or if you would like to amend something there:

- Autoplay [jump option](https://www.embla-carousel.com/plugins/autoplay/#jump)
- Autoplay [jump parameter for play method](embla-carousel.com/plugins/autoplay/#play)

Thanks and cheers!

Best,
David

**Comment by th-km** [comment]
@davidjerleke Thanks! I'll give it a go and get back to you. I have 2-3 projects that could really benefit from this update. The explanation looks great to me 👍

**Comment by th-km** [comment]
@davidjerleke I upgraded Embla to `7.0.2` on two recent projects and everything went super well!

**Comment by davidjerleke** [comment]
Happy to hear that @th-km 👍🏻. Enjoy! Closing this issue as resolved then.
