### ISSUE TITLE
Won't install on React 17

### ISSUE THREAD

**Issue by boris61** [davidjerleke/embla-carousel#362]
### Bug is related to

- [ ] embla-carousel (core package)
- [x] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- v7.0.2

### Describe the bug

- `npm install embla-carousel-react --save`  fails with React 17.0.2
### Expected behavior

- Should install

### Additional context

- ![image](https://user-images.githubusercontent.com/17053039/188616829-acd11141-bbb5-4a97-bd53-749dc431e31e.png)

**Comment by th-km** [comment]
@boris61 This is not a bug, you need to run `npm install embla-carousel-react --legacy-peer-deps` as mentioned in your log.

**Comment by boris61** [comment]
You're right, closing.

**Comment by boris61** [comment]
Reopening for a question. Installing with `--legacy-peer-deps` was fine and everything worked afterwards, but I still fail to see how this is not an issue. I won't ask every member of our team to install it manually, our `package.json` changes regularly. So the only way is to add `legacy-peer-deps=true` to `.npmrc` and that's a global project flag and not a good solution. So save for that and actually upgrading to React 18.1.0,, am I missing some other workaround?

**Comment by davidjerleke** [comment]
Hi @boris61,

Thank you for your question.

>  I still fail to see how this is not an issue

To be honest, I fail to see why this would be a problem specific to `embla-carousel-react`? This [StackOverflow thread](https://stackoverflow.com/a/66620869/4647781 ) explains why this is happening so please take some time to read it. And I'm sure you can find more information about it elsewhere too. Unfortunately we have to live with this.

Best,
David

**Comment by boris61** [comment]
Thanks for explanation and the link.

**Comment by davidjerleke** [comment]
@boris61 I have an update on this issue. Thanks to @horseeyephil's contributions, you can install `embla-carousel-react` without the `--legacy-peer-deps` from [v7.0.5](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.5) and up. I didn't know that an **or syntax** was valid in the `package.json` `peerDependecies` field. Read more about the [release here](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.5).

Cheers,
David
