### ISSUE TITLE
Option to not restart the autoplay delay after interacting

### ISSUE THREAD

**Issue by richgcook** [davidjerleke/embla-carousel#364]
### Feature request is related to

- [ ] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [x] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Is your feature request related to an issue?

I'm trying to re-create the 'Instagram Stories'-style pagination where the autoplay delay matches the fill 'progress' of one of the pagination dots (line). I've currently done this using CSS so when the pagination dot (line) is active then it runs a simple width 0% to 100% animation which matches the autoplay delay. However, my issue is that when the user interacts with the slider, the active pagination dot (line) continues to animate to 100% whereas the autoplay delay, due to interaction, has been restarted.

### Describe the solution you'd like

An option to, alongside setting`stopOnInteraction` to `false`, to prevent the delay from restarting when interacted with.

### Describe alternatives you've considered

An alternative solution to my problem, which would be much better, would be to be able to link the autoplay 'progress' to a pagination dot (line) for each slide. Is it possible to get the current progress of autoplay? That would be interesting...

**Comment by davidjerleke** [comment]
Hi @richgcook,

Please respect my decision here:

- #321

You can create a [new discussion](https://github.com/davidjerleke/embla-carousel/discussions/new) and move the content there if you want. Thank you for understanding.

Best,
David
