### ISSUE TITLE
Vue package - Incorrect types for emblaApi

### ISSUE THREAD

**Issue by davidjerleke** [davidjerleke/embla-carousel#366]
### Bug is related to

- [x] embla-carousel-vue

### Embla Carousel version

- v7.0.2

### Describe the bug

The typings are wrong for `emblaApi` that are exposed from `embla-carousel-vue` package. The current type is:
- `'EmblaCarouselType | HTMLElement'`

### Expected behavior

The type should be:

- `'EmblaCarouselType | null'`

### Additional context

Thanks @rojadesign for reporting this.

**Comment by davidjerleke** [comment]
@rojadesign I think the types [here](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel-vue/src/components/index.ts#L9-L12) should be something along these lines:

```ts
export type EmblaCarouselVueType = [
  Ref<HTMLElement | undefined>,
  Ref<EmblaCarouselType | undefined>
]
```

**Comment by rojadesign** [comment]
@davidjerleke exactly, I'm on it and will make a PR!

**Comment by davidjerleke** [comment]
Hi @rojadesign,

I just [released v7.0.3](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.3) that includes the fix for this type bug. Please update to the latest version and give it a go. Let me know how it goes.

Thanks for reporting this.

Best,
David

**Comment by rojadesign** [comment]
@davidjerleke works like a charm, thank you for everything! 🤘🏼

**Comment by davidjerleke** [comment]
Thanks again for reporting this problem 👍🏻.
