### ISSUE TITLE
Slide not properly centered on a modal viewport in reactjs

### ISSUE THREAD

**Issue by dexter4life** [davidjerleke/embla-carousel#375]
### Bug is related to

- [ ] embla-carousel (core package)
- [ ] embla-carousel-react

### Embla Carousel version

- v7.0.3

### Describe the bug
translate3d showing a value less than the size of the viewport. assuming the viewport size is 440px, it appears the translate3d is at 389px 0 0 instead and because of this is not perfectly centered.

- A clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/10168414/190895810-b7099ebe-61d4-443a-ab67-4e2e042dd29c.png)

### Steps to reproduce
Create a modal in react and make embla-carousel a child component of this modal

### Expected behavior
Each slide is expected to be perfectly center, it does work when not in modal but doesn't center perfectly when it is on the modal.

**Comment by davidjerleke** [comment]
Hi @dexter4life,

Thanks for your question. Please read [this comment](https://github.com/davidjerleke/embla-carousel/issues/159#issuecomment-805024840) and see if that solves your problem.

Best,
David

**Comment by dexter4life** [comment]
I think I found the problem

on this file Engine.ts 

Is using getBoundingClientRect() which produce a different value, but when I use getComputedStyle and replace the width the whole flow became normalized.

**Comment by dexter4life** [comment]
My solution is this

![image](https://user-images.githubusercontent.com/10168414/190919806-abe1f3fb-a067-4f43-a94e-c0197ca7c079.png)

**Comment by davidjerleke** [comment]
Hi @dexter4life,

**Please take time to read the comment I linked to.**

You didn’t find a solution to a problem. Thousands of users use Embla. Trust me, if this was a bug it would have been found a long time ago.

**Comment by davidjerleke** [comment]
> Hi @dexter4life,
> 
> **Please take time to read the comment I linked to.**
> 
> You didn’t find a solution to a problem. Thousands of users use Embla. Trust me, if this was a bug it would have been found a long time ago.

Best,
David

**Comment by dexter4life** [comment]
ok
