### ISSUE TITLE
Carousel gets in an infinite loop when using scrollTo for the first time in Next.js

### ISSUE THREAD

**Issue by SaizFerri** [davidjerleke/embla-carousel#380]
### Bug is related to

- [x] embla-carousel (core package)
- [x] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- v7.0.3

### Describe the bug

I copied all the code from the navigation example with dots into a component in Next.js to use in there.
After starting to test the carousel I noticed that when clicking on the second dot for the first time, embla gets stuck in an infinite loop while calculating the transform value for the second slide. This stops after some seconds and we see the second slide.

### CodeSandbox

[Link to reproduction](https://codesandbox.io/p/sandbox/confident-kapitsa-61zwol?file=%2Fcomponents%2FCarousel.tsx&selection=%5B%7B%22endColumn%22%3A26%2C%22endLineNumber%22%3A16%2C%22startColumn%22%3A26%2C%22startLineNumber%22%3A16%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl901cid400pr3b6on0j98age%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpages%252Findex.tsx%2522%252C%2522%252Fcomponents%252FCarousel.tsx%2522%252C%2522%252Fpages%252F_app.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl901kvg302le3b6o88csdb4c%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl901kuwi02jl3b6ow95u4ljw%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

### Steps to reproduce

1. Go to on the sandbox link above
2. Start the example
3. Open the devtools and select the first slide so that you see the inline styles applied to `embla__container`
4. Click on the second dot to navigate to the second slide
5. Observe how you do not see the second slide and see the bug in the inline style of `embla__container`

### Expected behavior

Clicking on the second dot should navigate to the second slide immediately

### Additional context

https://user-images.githubusercontent.com/19834971/194715040-1add36e1-f4ca-4825-b59e-0b5ea5567d03.mp4

**Comment by SaizFerri** [comment]
I just found out that the cause is the speed I set. My speed was set to 400 which is causing this super fast scrolling. Somehow after the first time it scrolls it just breaks and there is no more smooth scrolling. I think it is not clear from the docs what value range makes sense. The default is 10 but 10 what? Would be nice to have a clear unit of what that 10 means (ms or s or something else)
Btw. Thanks for this library!

**Comment by davidjerleke** [comment]
Hi @SaizFerri,

Thank you for your bug report.

> I think it is not clear from the docs what value range makes sense. The default is 10 but 10 what? Would be nice to have a clear unit of what that 10 means (ms or s or something else)

But the speed option is actually controlling the [magnitude of the attraction force](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel/src/components/ScrollBody.ts#L42) to the target or where the carousel is headed. Embla doesn't use simple transitions to scroll. Instead, it uses a simple physics simulation when scrolling. This isn't easy explain so I decided to call it speed, because it's simpler for most users to understand what it does.

[You've already figured](https://github.com/davidjerleke/embla-carousel/issues/380#issuecomment-1272360246) out that only a certain range makes sense and that range is`1-20`. Feel free to **make a contribution** and **add** this **to the docs**. I would happily accept a PR.

Best,
David

**Comment by SaizFerri** [comment]
Hi @davidjerleke thanks for the fast response! Now it makes sense. I will open a PR and add this that you told me to the docs 👌

**Comment by davidjerleke** [comment]
Solved in #381.
