### ISSUE TITLE
Carousel getting inline style `transform: translate3d(50%, 0px, 0px)` automatically, which is causing positioning issues

### ISSUE THREAD

**Issue by harshvardhan1000** [davidjerleke/embla-carousel#382]
### Bug is related to

- [ ] embla-carousel (core package)
- [x] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- v4.5.3

### Describe the bug

- Something is causing this style to get applied automatically to the parent container of the slides. If anything, the style should be `transform: translate3d(0px, 0px, 0px)` so that content is placed correctly, i.e aligned to the start of parent container.
On resizing the window, the style is recalculated to `transform: translate3d(0px, 0px, 0px)`, which then positions the carousel correctly.

### Expected behavior

- The style should be `transform: translate3d(0px, 0px, 0px)` so that content is placed correctly, i.e, aligned to the start of parent container.

### Additional context
[Screencast from 11-10-22 07:15:52 PM IST.webm](https://user-images.githubusercontent.com/108470211/195108627-fc1b212b-a931-4bd6-be9b-34a15be27446.webm)

- Add any other context about the problem here, like screenshots or similar.

**Comment by harshvardhan1000** [comment]
I was able to find a fix in this [comment](https://github.com/davidjerleke/embla-carousel/issues/159#issuecomment-805024840) by @davidjerleke

**Comment by davidjerleke** [comment]
@harshvardhan1000 closing this issue as resolved then?
