### ISSUE TITLE
How i can add navigation and dots from embla-carousel-vue? 

### ISSUE THREAD

**Issue by basharshaikh** [davidjerleke/embla-carousel#383]
### Feature request is related to

- [x] embla-carousel-vue
- [ ] embla-carousel-docs (documentation website)

Hello sir, 
I am new here. i just loved your carousel. i am trying to use it with my vue cli. it's working fine but i can't find any way to add nav and dots in carousel. I am using [this setup](https://www.embla-carousel.com/get-started/vue/)

Thank you

**Comment by davidjerleke** [comment]
Hi @basharshaikh,

Here you go, a [CodeSandbox](https://codesandbox.io/s/adoring-dream-8yqk7r) demonstrating that for you.

Best,
David

**Comment by basharshaikh** [comment]
Thank you so much @davidjerleke sir.. it's worked for me.
