### ISSUE TITLE
Interacting with a dropdown within the slider starts drag and drop behaviour

### ISSUE THREAD

**Issue by ChristianHoffmannS2** [davidjerleke/embla-carousel#394]
### Bug is related to

- [x] embla-carousel (core package)

### Embla Carousel version

- v7.0.0

### Describe the bug

- When interacting with a dropdown element inside of the slides, safari will be locked into free-drag state

### CodeSandbox

[- The link to a CodeSandbox that demonstrates the bug clearly.](https://codesandbox.io/s/embla-carousel-dragfree-react-forked-bidx62)

### Steps to reproduce

1. Go to the sandbox with a safari browser
2. Click on the dropdown and make a selection
3. Move the mouse without clicking anything

### Expected behavior

- Interacting with input elements should not be an interaction with the slider

### Additional context

- This might effect mobile safari as well. This might be related to drag- and touch events. 
-  Behaviour might be fixed with a stopPropagation at the right place
- Its unclear why this only happens when using Safari

**Comment by davidjerleke** [comment]
Hi @ChristianHoffmannS2,

Thank you for your bug report. The provided CodeSandbox doesn’t have a drop-down? Did you share the wrong link?

Best,
David

**Comment by davidjerleke** [comment]
Hi again @ChristianHoffmannS2,

Not to rush you or anything, but have you seen my response? Do you want to pursue this?

Best,
David

**Comment by ChristianHoffmannS2** [comment]
> Hi again @ChristianHoffmannS2,
> 
> Not to rush you or anything, but have you seen my response? Do you want to pursue this?
> 
> Best, David

Hi David,

this is Chris. I am sorry that I missed out your response!

Does this include it?

https://codesandbox.io/s/embla-carousel-dragfree-react-forked-e3mvkh?file=/src/js/EmblaCarousel.js

**Comment by davidjerleke** [comment]
Hi @ChristianHoffmannS2,

Thanks. That’s the CodeSandbox I think 🙂. I can confirm that this is a bug. Scanning the code, it seems to be a simple mistake because the [select name is missing in the list of elements that shouldn’t trigger dragging](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel/src/components/DragHandler.ts#L41).

I can create a CodeSandbox an add select to that list if you wouldn’t mind testing it?

Kindly,
David

**Comment by ChristianHoffmannS2** [comment]
Hi @davidjerleke,

thanks. That would be good to test against :)

**Comment by davidjerleke** [comment]
Sorry @ChristianHoffmannS2,

I’ve must have been really tired when writing  [my previous comment](https://github.com/davidjerleke/embla-carousel/issues/394#issuecomment-1320869519). The node type `SELECT` **is** in that list. I will have to investigate this a bit more.

I will let you know when I have something.

Best,
David

**Comment by ChristianHoffmannS2** [comment]
All good @davidjerleke .

I didn't payed enough attention neither :)

**Comment by davidjerleke** [comment]
Hi @ChristianHoffmannS2,

This bug has been fixed in [v7.0.7](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.7). Give it a go if you like.

Cheers,
David
