### ISSUE TITLE
Not working with Nextjs

### ISSUE THREAD

**Issue by hrqmonteiro** [davidjerleke/embla-carousel#395]
![Screenshot 2022-11-11 at 16 06 38](https://user-images.githubusercontent.com/17055027/201412837-f7322525-278b-45bd-9661-8187dbd051be.png)

Using any of the default examples, i have a hydration problem. How to fix it?

**Comment by davidjerleke** [comment]
Hi @hrqmonteiro,

Please provide more information if you want me to help you. What version are you using?This screenshot doesn’t help me at all. I can’t guess stuff. And reading the error message it could be anything causing this. How did you come to the conclusion that Embla is causing this?

A lot of devs use Embla with NextJS without any problems and the Embla script doesn’t even do anything on the server side.

**Comment by hrqmonteiro** [comment]
> Hi @hrqmonteiro,
> 
> Please provide more information if you want me to help you. Why didn’t you use the bug template where you’re asked to provide important information? Have you read the [bug section](https://github.com/davidjerleke/embla-carousel/blob/master/.github/CONTRIBUTING.md#bug-reports) in the **contribution guidelines**? What version are you using? This screenshot doesn’t help me at all. I can’t guess stuff and reading the error message it could literally be anything causing this. How did you come to the conclusion that Embla is causing this?
> 
> There are many devs out there that use Embla with NextJS without any problems.

What do you mean "How did you come to the conclusion that Embla is causing this?"?

I am trying to make an embla carousel and this error happens only when i try to do an example?

**Comment by davidjerleke** [comment]
Yeah but it doesn’t make sense at all to come here and dump an error message screenshot and say it’s a bug. As I said: Many devs use Embla with NextJS without problems.

Read the contribution guidelines. You need to provide useful information and a reduced test case. I have no idea how your setup looks like and what you’re doing. It could be literally anything causing this. If you want help, make a clear case. Provide your setup and step by step instructions on how you reproduce the error.
