### ISSUE TITLE
Scale artifacts when dragging with mouse

### ISSUE THREAD

**Issue by thdoan** [davidjerleke/embla-carousel#398]
### Bug is related to

- [x] embla-carousel (core package)

### Embla Carousel version

- v7.0.5

### Describe the bug

- Artifacts are visible when dragging the carousel slowly using the mouse:
![image](https://user-images.githubusercontent.com/4110567/202829888-0a20db9b-2559-4d2b-942b-3a2d9933871c.png)

### Steps to reproduce

1. Go to https://codesandbox.io/s/embla-carousel-scale-vanilla-gc3b0
2. Slowly drag a slide left or right using the mouse.
3. Artifacts in screenshot above are visible.

### Expected behavior

- No artifacts should be visible.

**Comment by davidjerleke** [comment]
Hi @thdoan,

Thanks for your bug report. What do you mean by artifacts? That the other slides are visible while sliding between two slides?


Kindly,
David

**Comment by thdoan** [comment]
@davidjerleke I'm referring to the redraw glitches:

![image](https://user-images.githubusercontent.com/4110567/202876269-2ba8e5ca-fd7d-4eac-ad33-a6172fde6374.png)

Device: Windows 10 desktop
Browser: Chrome Version 107.0.5304.107 (Official Build) (64-bit)

No, I cannot reproduce it on the documentation example, only in the sandbox with the white background.

**Comment by davidjerleke** [comment]
Hi again @thdoan,

Thanks for the additional details. At the time of writing, the CodeSandboxes are static and there are differences between the documentation website examples and the CodeSandboxes (including the scale example of course). The CodeSandboxes need manual updates so they are out of sync with the documentation website examples.

I’m working on creating the CodeSandboxes dynamically so they will share the same exact code as the documentation website examples in the near future:

- #281

I guess I’ve fixed the rendering problems you  describe on the documentation website (which are browser rendering problems to be clear) but not in the CodeSandbox example. It should be a matter of adding [something along these lines](https://stackoverflow.com/questions/13758215/artifacts-when-css-scaled-in-chrome) to the slide CSS. Try that and if it doesn’t solve your problem the dynamical CodeSandbox feature probably will.

Best,
David

**Comment by thdoan** [comment]
@davidjerleke thank you for the explanation. Add the CSS fixed it, so closing.
