### ISSUE TITLE
Unnecessary Peer Deps Error on Gestures Plugin

### ISSUE THREAD

**Issue by Eben-Hafkamp** [davidjerleke/embla-carousel#400]
### Describe the bug

After installing the embla-carousel-wheel-gestures plugin and using it successfully with embla-carousel-vue I keep getting npm warnings because embla-carousel is a peer dependency of the embla-carousel-wheel-gestures package. 

### Steps to reproduce

1. Install embla-carousel-vue
2. Install embla-carousel-wheel-gestures
3. See the warnings in the terminal

### Expected behavior

- As the plugin functions properly I would like to see a clear terminal void of issues instead of bloating my project with unnecessary packages.

**Comment by davidjerleke** [comment]
Hi @Eben-Hafkamp,

If you think this is a problem with the Wheel Gestures plugin, I would suggest you to [move your issue to that repository](https://github.com/xiel/embla-carousel-wheel-gestures/issues/new).

Best,
David
