### ISSUE TITLE
Handle click prevention on drag automatically

### ISSUE THREAD

**Issue by davidjerleke** [davidjerleke/embla-carousel#422]
### Feature request is related to

- [x] embla-carousel (core package)

### Is your feature request related to an issue?

- At the time of writing, the **opt-in** [`clickAllowed()`](https://www.embla-carousel.com/api/methods/#clickallowed) method only return returns `true` when the user's pointer has **not dragged the carousel**. 

### Describe the solution you'd like

- Embla should **handle this automatically.** It will make it convenient for devs to attach click listeners to slides without worrying about click events getting fired when users only drag the carousel.

**Comment by richgcook** [comment]
Was clickAllowed removed?

**Comment by davidjerleke** [comment]
@richgcook yes. It’s handled automatically now.l
