### ISSUE TITLE
Cannot slide image?

### ISSUE THREAD

**Issue by jamesli2021** [davidjerleke/embla-carousel#425]
### Bug is related to

- [x] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- Latest based on loading Embla from CDN.

### Describe the bug

- Styling is working but can't get slider to slide.
- Refresh page and 99% of the time slider doesn't work, 1% is working.

### CodeSandbox

I'm testing on Astro Build.

```
<div class="embla overflow-hidden max-w-3xl h-[428px]">
            <div class="embla__container flex">
              <div class="embla__slide min-w-0" style="flex: 0 0 100%">
                <img src="https://source.unsplash.com/random?landscape,mountain" alt="" />
              </div>
              <div class="embla__slide min-w-0" style="flex: 0 0 100%">
                <img src="https://source.unsplash.com/random?landscape,city" alt="" />
              </div>
              <div class="embla__slide min-w-0" style="flex: 0 0 100%">
                <img src="https://source.unsplash.com/random?landscape,night" alt="" />
              </div>
            </div>
          </div>

<script client:load src="https://unpkg.com/embla-carousel/embla-carousel.umd.js"></script>
<script is:inline>
  var emblaNode = document.querySelector('.embla')
  var options = { }

  var embla = EmblaCarousel(emblaNode, options)
</script>
```

### Steps to reproduce

1. Slide, it remain on the 1st image, does not slide to the next image.

### Expected behavior

- I think it might have to do with loading image from 3rd party site? It work for Keen slider when loading images from Unsplash. And note that I'm building and testing on Astro Build .astro page. (https://astro.build/)

**Comment by davidjerleke** [comment]
Hi @jamesli2021,

What happens when you resize the window. Does the slider start working then?

Best,
David

**Comment by jamesli2021** [comment]
I remember I have resize and still didn't side, out of my breathe.

**Comment by davidjerleke** [comment]
@jamesli2021 please log the following and let me know what you get.

```ts 
console.log(embla.slideNodes());
```

**Comment by jamesli2021** [comment]
Captured the console log.

```
Array(3) [ div.embla__slide.astro-FT4CRSVD, div.embla__slide.astro-FT4CRSVD, div.embla__slide.astro-FT4CRSVD
 ]
0: <div class="embla__slide astro-FT4CRSVD">​
1: <div class="embla__slide astro-FT4CRSVD">​
2: <div class="embla__slide astro-FT4CRSVD">
length: 3
<prototype>: Array []
```

I have tested Slide 1...3 text worled but not images.

**Comment by davidjerleke** [comment]
Hi @jamesli2021,

Thanks for helping out. So [this](https://github.com/davidjerleke/embla-carousel/discussions/413#discussioncomment-4582700) is why your carousel isn’t working. 

Either set image placeholders for your images so they take up their space before they’ve finished loading, or run `embla.reInit()` once all images have finished loading.
