### ISSUE TITLE
Support for solid-js

### ISSUE THREAD

**Issue by oSethoum** [davidjerleke/embla-carousel#429]
Can you support [solid-js](https://www.solidjs.com/) which has been gaining a lot of interest lately.

**Comment by davidjerleke** [comment]
Hi @oSethoum,

Thanks for your question. Let’s see if solidJs devs are interested in this.

### React with a —> 👍 if you want this feature.

**Comment by BoilingSoup** [comment]
Hi just wanted to share that I was able to get Embla working very easily with Solid by following [the vanilla JS steps.](https://www.embla-carousel.com/get-started/module/)

Only thing I did different was add the JS code inside Solid's `onMount()` callback.

**Comment by jassix** [comment]
> Hi @oSethoum,
> 
> Thanks for your question. Let’s see if `SolidJs` devs are interested in this.
> ### React with a —> 👍 if you want this feature.

We need Solid.js support 🥺

**Comment by davidjerleke** [comment]
Merged thanks to @LiamMartens great contribution. `embla-carousel-solid` will be released with `v8.0.0-rc19` soon 🎉 !

**Comment by davidjerleke** [comment]
@LiamMartens, @BoilingSoup, @oSethoum, @jassix - I just released the `SolidJs` wrapper with [`v8.0.0-rc19`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc19). Thanks a ton @LiamMartens ⭐! 

Here's the [get started guide](https://www.embla-carousel.com/get-started/solid/).

There's still a lot to do. We need to add `SolidJs` code examples under all API pages. For example, [here](https://www.embla-carousel.com/api/options/#constructor-options). Feel free to add these if you want to contribute.

Best,
David
