### ISSUE TITLE
Autoplay stops when you manually drag the item

### ISSUE THREAD

**Issue by oSethoum** [davidjerleke/embla-carousel#431]
### Bug is related to

- [x] embla-carousel-react
- [x] embla-carousel-autoplay

### Embla Carousel version

- v7.0.9

### Describe the bug

- A clear and concise description of what the bug is.
If I slide or drag the elements in the exact moment auoplay is trying to slide the items, the autoplay will stop completely until I refresh the page.
### CodeSandbox

- The link to a CodeSandbox that demonstrates the bug clearly.

### Expected behavior

- A clear and concise description of what you expected to happen.

### Additional context

- Add any other context about the problem here, like screenshots or similar.

**Comment by davidjerleke** [comment]
Hi @oSethoum,

Are you looking for the [`stopOnInteraction`](https://www.embla-carousel.com/plugins/autoplay/#stoponinteraction) option? Please set it to `false`.

Best,
David

**Comment by davidjerleke** [comment]
@oSethoum did you see my response?

**Comment by oSethoum** [comment]
@davidjerleke thank you, I just saw your response, I will try it and tell you.

**Comment by oSethoum** [comment]
@davidjerleke Thanks again, that solved the problem.
