### ISSUE TITLE
Gap after last slide when having containScroll: 'trimSnaps' enabled

### ISSUE THREAD

**Issue by SunpieAgency** [davidjerleke/embla-carousel#432]
### Bug is related to

- [x] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- v7.0.9

### Describe the bug

I'm facing a problem with the gap (margin-right) after the last slide which is now visible when having containScroll: 'trimSnaps' enabled. This issue seems to appear since version 7.0.

You can switch between newer Versions and V6.2.0 in my CodeSandbox to see the difference.

I'm aware of the fact that I could handle it with some CSS (:last-child: margin: 0, ...). But i'm wondering if this is a bug since older versions do the job and the documentation states that Embla "will conveniently pick up any spacings between the slides and automatically adjust the scroll snaps accordingly.".

### CodeSandbox

https://codesandbox.io/s/embla-carousel-default-vanilla-forked-qgdw54

![Screenshot 2023-02-08 163005](https://user-images.githubusercontent.com/98021625/217575088-50fdef5c-1d9c-414d-a196-41219d25c173.png)

**Comment by SunpieAgency** [comment]
Hi @davidjerleke,

thank you for your quick response. Would you recommend solving it via. CSS like your examples do? Like:

```
.embla__container { margin-left: calc(var(--slide-spacing) * -1); }

.embla__slide { padding-left: var(--slide-spacing); }
```

Anyway, thank you for this awesome Slider :)

**Comment by davidjerleke** [comment]
@SunpieAgency in most cases yes, because it will work without modifying your CSS in many cases, for example when changing the [`slidesToScroll`](https://www.embla-carousel.com/api/options/#slidestoscroll) option.

Cheers,
David
