### ISSUE TITLE
Setup using a class component in TypeScript

### ISSUE THREAD

**Issue by akaldesign** [davidjerleke/embla-carousel#451]
### Feature request is related to

- [x] embla-carousel-react

- I'm using a class component and wanted to know how to setup Embla carousel. There is no documentation for this.

**Comment by davidjerleke** [comment]
Hi @akaldesign,

Unfortunately, Embla Carousel dropped class component support a long time ago. It’s now only available using the `useEmblaCarousel` hook.

If you really want to use it in a class component, you need to use the vanilla `embla-carousel` package, and recreate what the `useEmblaCarousel` hook does under the hood in a class component way. However, I would encourage you to migrate to functional components as soon as possible.

Best,
David
