### ISSUE TITLE
Make carousel events work inside an iframe

### ISSUE THREAD

**Issue by slpy9** [davidjerleke/embla-carousel#455]
### Feature request is related to

- [x] embla-carousel (core package)

### Is your feature request related to an issue?

- Compatibility with the WordPress site editor. https://make.wordpress.org/core/2021/06/29/blocks-in-an-iframed-template-editor/

### Describe the solution you'd like

- As described in the blog post linked above, replace usage of the `document` property with [ownerDocument](https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument).

### Describe alternatives you've considered

- Replacing the drag handler via the Embla engine.

### Additional context

I've been developing a WordPress plugin using Embla Carousel, dragging is broken in the site editor due to the blocks being loaded in an iframe.

I was able to fix the issue by modifying the line below to use `rootNode.ownerDocument`.

https://github.com/davidjerleke/embla-carousel/blob/70fffbbedb8619cbc5d78de429ee683ff9fb9a5c/packages/embla-carousel/src/components/DragHandler.ts#L72

**Comment by davidjerleke** [comment]
Hi @slpy9,

Thank you for your question. Is the site editor rendering the carousel in an iframe?

Best,
David

**Comment by slpy9** [comment]
Hey David,

Yes, I believe that's the core issue.. the link I've posted above goes into better detail than I am able to explain myself. I wasn't really sure if I should post this issue as a bug or a feature request.

Thanks for your time.

**Comment by davidjerleke** [comment]
Thanks @slpy9. @M-Joyce created a discussion for this here:

- #448

He also linked to a [possible solution](https://github.com/nolimits4web/swiper/issues/2411#issuecomment-368547159) to the problem in the same discussion. I would like to implement this but I need someone to test it. If you’re willing to test it I will investigate this further.

Best,
David

**Comment by slpy9** [comment]
I'd be happy to give it a try, just let me know what you require from me.

I've read through the discussion you linked, and the proposed solution is effectively the same as what the WordPress dev's have suggested, replacing instances of `document` with `ownerDocument`.

I've made these changes in my local dev environment, and that has fixed the issue I was experiencing with dragging behaviour in the site editor.

**Comment by davidjerleke** [comment]
Hi @slpy9,

Thank you for your response! Yeah, they’re almost the same but I think the is iframe check is important. Because just changing `document` to `ownerDocument` is a more “naive” (in lack of a better term) approach and could have other implications that were missing. 

We wouldn’t want to introduce a critical bug to thousands of users. Unless you have a more robust source that proves that this is safe. If that’s the case, please share 🙂.

Best,
David

**Comment by davidjerleke** [comment]
Do you have any objections to renaming this issue title to something along these lines:

_Make Embla Carousel events work inside an iframe?_

?

Best,
David

**Comment by slpy9** [comment]
Hey David,

> Thank you for your response! Yeah, they’re almost the same but I think the is iframe check is important. Because just changing `document` to `ownerDocument` is a more “naive” (in lack of a better term) approach and could have other implications that were missing.

I understand your concerns and it is no doubt better to err on the side of caution.

> do you have any objections to renaming this issue

Not at all, go for it!

**Comment by davidjerleke** [comment]
Hi @slpy9,

> I've read through the discussion you linked, and the proposed solution is effectively the same as what the WordPress dev's have suggested, replacing instances of `document` with `ownerDocument`.

> I've made these changes in my local dev environment, and that has fixed the issue I was experiencing with dragging behaviour in the site editor.

I started looking into this today and wasn't sure about what you replaced? All `document`'s are easy to replace but did you also do something similar to all `window.` calls? Because if I'm not mistaken, `window` also refers to the top window (not the iframe but its parent) unless it's targeted differently?

Thanks in advance.

Best,
David

**Comment by slpy9** [comment]
Hey David,

You are correct, initially I did not make any changes to `window` calls as I thought the `DragHandler` was the only problem, but have since noticed some issues with resizing. The `window` calls also need updating to use `ownerDocument.defaultView`.

Thanks for looking into this!

**Comment by davidjerleke** [comment]
Thanks for the prompt answer @slpy9 👍.

> I'm not certain whether you need to update all window calls, as I've only experienced issues with event listeners in an iframe.

I guess it makes sense that any `document` and `window` reference should point to the **iframe** itself in case it's an iframe. Although this isn't technically advanced to implement, we need to initialize them and pass them around in many places in the code. I'll look into it when possible.

Cheers,
David

**Comment by deysan** [comment]
Hello  @slpy9. I have also faced this problem. How can the proposed solution be implemented locally?

@davidjerleke Let me know if you need help with testing 🙄

**Comment by slpy9** [comment]
Hey @deysan,

Are you using React? as a temporary fix, I've edited the source under `node_modules/embla-carousel`, and created a patch using [patch-package](https://www.npmjs.com/package/patch-package).

Though it's not ideal and I'd recommend waiting for an official patch if you can.

**Comment by davidjerleke** [comment]
Hi @slpy9,

Are you using the vanilla JavaScript package `embla-carousel`?

Best,
David

**Comment by slpy9** [comment]
Hey @davidjerleke,

I am using React on the backend, and plain JavaScript (CDN) on the frontend. The iframe only exists on the backend side of things as it's part of the WordPress site editor.

Are you able to provide some React compatible code?

Thankyou.

**Comment by davidjerleke** [comment]
@slpy9 sure, I updated my [previous comment](https://github.com/davidjerleke/embla-carousel/issues/455#issuecomment-1551930260) and added `embla-carousel-react`. Just toggle open the script.

**Comment by slpy9** [comment]
Thanks David,

I encountered a bug when trying to drag:
https://github.com/davidjerleke/embla-carousel/blob/7b3781c3f51316f8cbd6cb0c01568245eeca0e1a/packages/embla-carousel/src/components/utils.ts#L19-L20
This was returning false, so my mouse interactions were being treated as touch events and causing a script error. Reading through the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_realms), `instanceof` appears to have issues with iframe's too and they recommend the familiar workaround of `ownerDocument.defaultView`.

Other than that.. I've done some testing in Chrome & Firefox, dragging, resizing and breakpoint options all appear to be working as intended.

**Comment by davidjerleke** [comment]
Hi again @slpy9,

Thanks a lot fot pointing me to the problem. That's very helpful. I've updated both [scripts](https://github.com/davidjerleke/embla-carousel/issues/455#issuecomment-1551930260) with the workaround now so please give it a go and see if the script error is gone.

@deysan are you intending to test the scripts too?

Best,
David

**Comment by davidjerleke** [comment]
# Specification

- Refactor Embla so to work properly in different realms - iframes/windows.
- Animate all carousels within the same realm inside a single animation loop.

**Comment by slpy9** [comment]
It's working great on my end @davidjerleke, appreciate all the work you've been putting into this and looking forward to your next release, thanks!

**Comment by davidjerleke** [comment]
@slpy9, I just released this feature with [v8.0.0-rc04](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc04). Thanks a bunch for the help!
