### ISSUE TITLE
Autoplay stop working when you manually change current slide

### ISSUE THREAD

**Issue by Astanusic** [davidjerleke/embla-carousel#474]
### Bug is related to

- [x] embla-carousel (core package)
- [x] embla-carousel-vue
- [x] embla-carousel-autoplay

### Embla Carousel version

- v8.0.0-rc03

### Describe the bug

When using autoplay plugin if the user manually change the current slide with his mouse then the autoplay stop working, it doesnt autoplay at all.

### CodeSandbox

This is a codesandbox present in the documention of the Autoplay plugin.
[sandbox autoplay](https://codesandbox.io/s/0ynqpe)

### Steps to reproduce

1. Drag current slide to the left/right
2. Autoplay doesnt work anymore

### Expected behavior

- The Autoplay should keep playing event after changing slide manually.

**Comment by Astanusic** [comment]
#431 
I'm closing, I'm stupid.
Need to read the documentation before posting shit.

**Comment by davidjerleke** [comment]
- Duplicate of #431.
