### ISSUE TITLE
Add "type: module" (nodenext) support alongside commonjs

### ISSUE THREAD

**Issue by chronoDave** [davidjerleke/embla-carousel#481]
### Bug is related to

- [x] embla-carousel (core package)
- [x] embla-carousel-react
- [x] embla-carousel-vue
- [x] embla-carousel-svelte
- [x] embla-carousel-autoplay
- [x] embla-carousel-auto-height
- [x] embla-carousel-class-names

### Embla Carousel version

- 8.0.0-rc05

### Describe the bug

When using node16 esm import in TypeScript, TypeScript with incorrectly flag up the embla-carousel default import as missing. This is due to incorrect typing: https://arethetypeswrong.github.io/?p=embla-carousel%408.0.0-rc05

![image](https://github.com/davidjerleke/embla-carousel/assets/27073716/4333f66b-d2be-4146-8d37-0d7730e2ca46)

This error can be ignored using `@ts-expect-error` or something similar as I can confirm that the default import does work, it's just the typing that's incorrect.

### CodeSandbox

Unfortutately this bug does not occur when usign CodeSandbox. If needed, I can create a simple repository demonstrating this behaviour.

**package.json**
```JSON
{
  "name": "nodenext",
  "type": "module",
  "dependencies": {
    "embla-carousel": "^8.0.0-rc03",
    "typescript": "^5.0.4"
  }
}
```

**tsconfig.json**
```JSON
{
  "compilerOptions": {
    "module": "NodeNext",
  }
}
```

**index.ts**
```TS
import EmblaCarousel from 'embla-carousel';

const carousel = EmblaCarousel();
```

### Steps to reproduce

Simply hover over the EmblaCarousel error in your IDE of choice (mine being VSC)

### Expected behavior

I expect the default export to be typed correctly.

### Additional context

It seems to be a common issue:
 - https://github.com/vercel/next.js/issues/46078
 - https://github.com/knex/knex/issues/5358
 - https://github.com/microsoft/TypeScript/issues/49189

**Comment by davidjerleke** [comment]
Thanks @chronoDave. Do you happen to know how to solve this?

Best,
David

**Comment by chronoDave** [comment]
I've not done much research yet but I can pick it up if you'd like. I suspect it would be simply following the advice from https://arethetypeswrong.github.io/?p=embla-carousel%408.0.0-rc05

> The types resolved at the package use export default where the implementation appears to use module.exports =. Node treats a default import of these constructs from an ES module differently, so these types will make TypeScript under the node16 resolution mode think an extra .default property access is required, but that will likely fail at runtime in Node. These types should use export = instead of export default.

Though I'm not sure how it would impact cjs imports.

**Comment by chronoDave** [comment]
Thank you for the `slugify` recommendation. You're correct in that it's probably not in the best interest to monkey-patch the `index.d.ts` file produced by `rollup`.

After doing some more research into how `rollup` creates `index.d.ts`, it seems the issue is with `rollup-plugin-typescript2`. It currently does not support `node16`:
 - https://github.com/ezolenko/rollup-plugin-typescript2/issues/437
 
I've tried solving the issue using `@rollup/plugin-typescript` but had no luck getting it to export correctly.

I feel it's probably best to wait for that issue to be resolved and then see if that solves the problem.

**Comment by davidjerleke** [comment]
Thanks for taking the time to investigate this @chronoDave 👍.

At the time of writing my understanding of this problem and possible solutions is very limited. So sorry if this is a stupid question: What's your understanding of this problem? Because I'm a bit confused. The solution seems to be changing:

```ts
// from:
export default EmblaCarousel

// to:
export = EmblaCarousel
```

But is this backwards compatible for `esm` with node versions < 16? Or does this mean that we need to create two `esm` bundles with both solutions and point to different `esm` files (in `package.json` or similar) depending on the node version used?

Best,
David

**Comment by chronoDave** [comment]
The issue lies with TypeScript not being able to tell the difference between a `cjs` and a `esm` package. Even though you're exposing both `esm` and `cjs` packages, the `index.d.ts` file is only valid for `cjs`, therefore causing TypeScript to import the `esm` module as a `cjs` module and throwing the "has no call signatures" error.

I've attached a video that should hopefully better describe the issue. I've created a repo as well so you can easily verify it for yourself: https://github.com/chronoDave/ts-esm-cjs

https://github.com/davidjerleke/embla-carousel/assets/27073716/0b4e01e1-0859-456e-ae22-a4969b25e2ed

When trying to resolve the `embla-carousel` import, the following steps happen:

**Types**
1) It looks for a type declaration, which it finds based on `types: index.d.ts`
2) There's no `type` field, so it defaults to `cjs`
3) TypeScript throws an error because the `embla-carousel.esm.js` bundle does not expose correct `cjs` (as it's `esm`)

**Code**
1) It looks for an `esm` bundle, which it finds based on `module: embla-carousel.esm.js`
2) It's valid `esm` so it bundles correctly!

By adding `type: module`, it makes it explicit that the `types: index.d.ts` file is `esm`. However, the `index.d.ts` file does not have valid `esm` as it's missing file extensions (as seen in the video).

---

As for a solution, creating seperate type declarations seems to do the trick, but this requires `type: module` in the package.json to work. It seems to be working for `moduleResolution: node` and `moduleResoltion: nodenext` but I'd have to do more testing to see what impact this solution would have.

```JSON
  "exports": {
    ".": {
      "import": {
        "default": "./embla-carousel.esm.js",
        "types": "./esm.d.ts"
      },
      "require": {
        "default": "./embla-carousel.cjs.js",
        "types": "./cjs.d.ts"
      }
    }
  },
```

I hope this helps clarify the issue more. My apologies if my answers seem vague, I'm figuring it out as I go, I don't have too much experience yet with using `moduleResolution: nodenext` :)

**Comment by davidjerleke** [comment]
Hi @chronoDave,

I just found [this article](https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html) that claims you can support both `imports` and `require`. I haven't tried it yet though. Feel free to try it out if you get the chance to do so before I get the chance.

Best,
David

**Comment by chiptus** [comment]
after reading https://github.com/microsoft/TypeScript/issues/49189 I got a workaround for now:
```
import _useEmblaCarousel, {EmblaOptionsType, EmblaPluginType, UseEmblaCarouselType} from "embla-carousel-react";

const useEmblaCarousel = _useEmblaCarousel as unknown as (options?: EmblaOptionsType, plugins?: EmblaPluginType[]) => UseEmblaCarouselType;
```

**Comment by davidjerleke** [comment]
Hi @chronoDave,

Sorry for the late response. I've been working on v8 and it's been a looot of work 😅.

I'm getting close to a stable `v8` release and decided that this feature should be part of `v8`. So I tried writing a **Node script** that [did all of this](https://github.com/davidjerleke/embla-carousel/issues/481#issuecomment-1584474719). The script worked fine and everything was done the way you described but when the **rollup build** command was triggered it threw all sorts of errors at me (mainly about a ./package.json subpath which was triggered by the exports field in the package.json file). My guess is that the rollup version is very old and needs an update. But that will unleash a sh*tload of other errors as soon as we start upgrading all rollup plugins and similar.

You're welcome to give it a try! But if you run into a lot of trouble, I'm thinking that it might be worth investigating a migration to `esbuild`. Maybe that would make life a bit easier.

Let me know if you're interested in trying.

Best,
David

**Comment by davidjerleke** [comment]
@chronoDave never mind I found a solution!

**Comment by davidjerleke** [comment]
@chronoDave and @chiptus this will be released with the next version of Embla.
