### ISSUE TITLE
Carousel isn't reactivating after resizing from a breakpoint with `active: false`

### ISSUE THREAD

**Issue by turtlecrab** [davidjerleke/embla-carousel#486]
### Bug is related to

- [x] embla-carousel (core package)

### Embla Carousel version

- v8.0.0-rc05

### Describe the bug

- Carousel isn't reactivating after resizing from a breakpoint with `active: false` in 8.0.0-rc05. Works fine in 7.1.0

### CodeSandbox

- https://codesandbox.io/s/embla-8-resize-bug-6ezjqb?file=/src/App.tsx

### Steps to reproduce

1. In the sandbox make sure that the width of the built-in browser is <600, if it's not - resize and refresh it
2. Check that the carousel is working as expected
3. Resize built-in browser so the width is > 600, check that the carousel stopped working
4. Resize it back
5. Observe that the carousel isn't working
6. (optional) Change the version from 8.0.0-rc05 to 7.1.0 and repeat all the steps, observe that it's working as expected

### Expected behavior

- Should reactivate after resize

**Comment by davidjerleke** [comment]
Hi @turtlecrab,

Thank you for this crystal clear bug report. I can confirm that this is a bug. I will ship a fix for this in v8.0.0-rc06 as soon as possible. Stay tuned.

Best,
David

**Comment by turtlecrab** [comment]
@davidjerleke works fine on my side. Thank you for blazing fast fix!

**Comment by davidjerleke** [comment]
Released with [v8.0.0-rc06](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc06). Thanks for this clear and well written bug report @turtlecrab!
