### ISSUE TITLE
Uncaught "ResizeObserver loop limit exceeded" | NextJS

### ISSUE THREAD

**Issue by hmartiins** [davidjerleke/embla-carousel#488]
### Bug is related to

- [x] embla-carousel (core package)

### Embla Carousel version

- "embla-carousel-react": "8.0.0-rc05",

### Describe the bug

- I could not identify a step by step to reproduce this error, it happened sometimes in a production environment and I was able to capture this error through Datadog. This error started happening right when I migrated to version 8.0.0-rc05. My carousel didn't glitch or crash, but I got this error on my console. I'm using NextJS in my project.

### Steps to reproduce

I just browsed my website and every time I entered the page I had this message

### Expected behavior

- I would not want to get this error on my console.

### Additional context

![image](https://github.com/davidjerleke/embla-carousel/assets/51277667/d26582ad-996a-429b-b390-9b97906c67ee)

**Comment by davidjerleke** [comment]
@hmartiins please share more helpful information when creating a bug report. For example, [this bug report](https://github.com/davidjerleke/embla-carousel/issues/486#issue-1731287555) is very clear and doesn’t leave you with many questions. At the time of writing I have no idea how to reproduce this. 

- Have you browsed the web like StackOverflow to try to understand why or when this is happening?
- Is this only happening with NextJS or can you reproduce it without it?

> This error started happening right when I migrated to version 8.0.0-rc05.

- Migrated from which version?

**Comment by VadymBezsmertnyi** [comment]
In the Safari 16.4 (18615.1.26.110.1) browser console, when using embla-carousel 8.0.0-rc02 to 8.0.0-rc05, the following error occurs: [Error] ResizeObserver loop completed with undelivered notifications.
However, when using embla-carousel 7.1.0, there are no errors.
I am using embla-carousel for a regular React application.
Additionally, if I add watchResize: false to the settings of useEmblaCarousel where embla-carousel is used, the error also disappears. Occasionally, it also appears on Chrome, but I haven't been able to track when and how it happens.

**Comment by davidjerleke** [comment]
Thanks for chiming in with additional details @VadymBezsmertnyi. So at this point I need to understand why this is happening and possible solutions. If you or anyone else has any useful information about this - please share.

**Comment by davidjerleke** [comment]
@hmartiins and/or @VadymBezsmertnyi when does this error appear in the console? As soon as the carousel mounts? If you have additional details on how to reproduce this, please share.

**Comment by hmartiins** [comment]
@davidjerleke what i noticed is when the carousel is mounted on the screen. I'll try to provide a codesandbox trying to simulate the error. The difficult thing is, I haven't encountered this error so far in a local environment, I'm just getting error messages and alerts about this in a production environment. From what I analyzed in my monitoring tool, this error occurred both in the android and in the IOS environment, so far I have not caught any reports of this error on the desktop. From the replays of the sessions in which this error occurs, the carousel does not break

**Comment by davidjerleke** [comment]
Thanks for the additional details @hmartiins 👍🏻. I’ll try to reproduce the error using BrowserStack then.

**Comment by hmartiins** [comment]
@davidjerleke So, I simulated it here on browserstack and was able to see the error on my console. It looks like it only occurs on real mobile devices.

![image](https://github.com/davidjerleke/embla-carousel/assets/51277667/482b1a9b-e346-46f1-8b16-2a8ca1af4cce)

**Comment by davidjerleke** [comment]
@hmartiins that's so weird. I tried reproducing the error with BrowserStack but it did not throw any errors 😕. Would you mind creating a CodeSandbox with a carousel setup that triggers the error in BrowserStack?

**Comment by VadymBezsmertnyi** [comment]
@davidjerleke With the addition of watchResize:false in the options, it doesn't throw an error, but it doesn't resize adaptively either. To change the size of the object, a reload is needed. I also tested it on 8.0.0-rc01, and it still throws an error. The error occurs whenever there is a change in the object where embla-carousel is located or responds.

**Comment by tobimori** [comment]
I can confirm this error but it doesn't seem to have caused any issues

**Comment by davidjerleke** [comment]
Allright I was finally able to reproduce it. One way to do it is to flip the iPhone in BrowserStack. The error is also thrown whenever the slide container is resized.

@hmartiins, @VadymBezsmertnyi or @tobimori I would very much appreciate if you could try to reproduce the error in this [CodeSandbox](https://5bvnxf.csb.app/) with the bug fix I added.

Let me know if the error is gone or not.

Best,
David

**Comment by tobimori** [comment]
Works for me.

**Comment by davidjerleke** [comment]
@tobimori you mean no more ResizeObserver errors?

**Comment by tobimori** [comment]
> @tobimori you mean no more ResizeObserver errors?

yeah

**Comment by VadymBezsmertnyi** [comment]
Thank you, @davidjerleke . I tried your code in CodeSandbox, and the error doesn't occur. I also tried version 8.0.0-rc06 in the project, and the error is still reproducible.

**Comment by davidjerleke** [comment]
A bugfix for this problem has been released with [v8.0.0-rc07](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc07). Thanks for the help 👍.

**Comment by VadymBezsmertnyi** [comment]
Thank you, @davidjerleke. Everything is working perfectly and without any errors in the console. Thank you!

**Comment by mickaeltr** [comment]
Just so you know, I ran into this on v8.6.0 with embla-carousel-react + embla-carousel-wheel-gestures in a Next.js app. The error message wording is slightly different from the original ("ResizeObserver loop completed with undelivered notifications" rather than "loop limit exceeded") which might be a browser version difference, but it seems to be the same underlying issue.
