### ISSUE TITLE
Embla crashes on IOS 13 (Safari/Chrome)

### ISSUE THREAD

**Issue by khodich-dmitriy** [davidjerleke/embla-carousel#492]
### Bug is related to

- [ ] embla-carousel-react

### Embla Carousel version

- v8.0.0-rc01 - v8.0.0-rc06

### Describe the bug

- ios 13 safari crashes 

### Steps to reproduce

1. launch app on ios 13

### Expected behavior

Ios 13 works correctly with embla-corousel

### Additional context

![Снимок экрана 2023-06-02 в 11 00 03](https://github.com/davidjerleke/embla-carousel/assets/18570283/59be4ac4-e780-4081-b801-df98e2f1bc22)

**Comment by davidjerleke** [comment]
@khodich-dmitriy please provide a CodeSandbox that reproduces the problem. This is clearly stated in the [contribution guidelines](https://github.com/davidjerleke/embla-carousel/blob/master/.github/CONTRIBUTING.md#bug-reports). Please read it and add necessary things missing to this bug report.

Without this information, this issue **will be deleted** so let me know if you intend to complete this bug report.

Best,
David

**Comment by davidjerleke** [comment]
Hi @khodich-dmitriy,

Embla v8 only supports modern browser features. iOS 13 doesn’t support ResizeObserver:

![IMG_7133](https://github.com/davidjerleke/embla-carousel/assets/11529148/28567d25-aaec-45a2-8660-1788c81e9db5)

…and the number of users using iOS 13 is very very low:

![IMG_7132](https://github.com/davidjerleke/embla-carousel/assets/11529148/5f1fbe5e-a826-4f1d-bc57-f44c1ee68268)

However, as you can see on the table, iOS 13.1 **does** support ResizeObserver. Either upgrade your iOS version or downgrade Embla to any version before v8.0.0-rc0x.

Best,
David

**Comment by davidjerleke** [comment]
@khodich-dmitriy **IOS 13.x support** was added in [`8.0.0-rc13`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc13). Note that only for versions that support ResizeObserver:

- IOS 13.4 and up
- OSX Safari 13.1 and up

Best,
David
