### ISSUE TITLE
[Help] is it possible to create nested carousel with dynamic/virtual slides?

### ISSUE THREAD

**Issue by or2008** [davidjerleke/embla-carousel#501]
in react version, is it possible to create a nested carousel  that utilizes both the X and Y axes and accepts dynamic slides based on the scroll direction.

for example if I swipe right, fetch and render slide 1, if I swipe down, fetch and render another slide etc..  

It's important to note that pre-rendering all the slides isn't feasible in this case, as the slides are determined by the user's path, similar to a linked list or binary tree structure.

appreciate your help

**Comment by davidjerleke** [comment]
Hi @or2008,

Please don't create a bug report for when you want guidance or know if something is possible to achieve. Create a [new discussion](https://github.com/davidjerleke/embla-carousel/discussions/new/choose) instead.

Best,
David

**Comment by or2008** [comment]
ok thanks David

https://github.com/davidjerleke/embla-carousel/discussions/502
