### ISSUE TITLE
Focusable elements offscreen break layout.

### ISSUE THREAD

**Issue by aa-jeremyhoover** [davidjerleke/embla-carousel#506]
### Bug is related to

- [x] embla-carousel (core package)
- [x] embla-carousel-react

### Embla Carousel version

- v8.0.0-rc07

### Describe the bug

When a slide offscreen contains a focusable link, users can tab to this hidden content and break the layout of the slider.

### CodeSandbox

Here's a demo, pressing tab goes to a slide out of view and breaks the slide layout:
https://codesandbox.io/s/embla-carousel-default-react-forked-mfxmmy?file=/src/js/EmblaCarousel.jsx

### Steps to reproduce

1. Tab through elements on page
2. Element out of view receives focus and breaks the layout. Which looks like this:
![image](https://github.com/davidjerleke/embla-carousel/assets/116915321/7227be55-bd94-4ce9-b2c5-a39c459617e9)

### Expected behavior

1. Elements out of view shouldn't receive focus. They should still be accessible to keyboard users through navigation. As per [this comment](https://github.com/davidjerleke/embla-carousel/issues/6#issuecomment-755329248)

> Yes I believe that content of non-visible slides should not be tabable

**Comment by davidjerleke** [comment]
Hi @aa-jeremyhoover,

Try [this solution](https://github.com/davidjerleke/embla-carousel/issues/239#issuecomment-1073009374). Let me know if it helps.

Best,
David

**Comment by aa-jeremyhoover** [comment]
Thanks, that's what I needed :)

**Comment by davidjerleke** [comment]
Hi @aa-jeremyhoover,

Just wanted to let you know that as of [`v8.0.0-rc12`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc12) Embla handles this internally. No need to copy paste code to get this to work anymore.

Cheers,
David
