### ISSUE TITLE
what do you think about utils hooks in react version ?

### ISSUE THREAD

**Issue by MarlonPassos-git** [davidjerleke/embla-carousel#529]
### Feature request is related to

- [ ] embla-carousel (main package)
- [x] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation)
- [ ] embla-carousel-docs (generator)

### Is your feature request related to an issue?

No.

### Suggestion.

In my day to day work on several different projects I end up using some utility hooks to help me solve some common slider problems with Embla. One of them is `useEmblaArrows` which already does the entire Embla configuration process using arrows.

```ts
import type { EmblaCarouselType } from 'embla-carousel-react'
import { useCallback, useEffect, useState } from 'react'

export function useEmblaArrows(emblaApi: EmblaCarouselType | undefined) {
  const [prevBtnDisabled, setPrevBtnDisabled] = useState(true)
  const [nextBtnDisabled, setNextBtnDisabled] = useState(true)
  const scrollPrev = useCallback(() => emblaApi?.scrollPrev(), [emblaApi])
  const scrollNext = useCallback(() => emblaApi?.scrollNext(), [emblaApi])
  const onSelect = useCallback((_emblaApi: EmblaCarouselType) => {
    setPrevBtnDisabled(!_emblaApi.canScrollPrev())
    setNextBtnDisabled(!_emblaApi.canScrollNext())
  }, [])

  useEffect(() => {
    if (!emblaApi) return

    onSelect(emblaApi)
    emblaApi.on('reInit', onSelect)
    emblaApi.on('select', onSelect)
  }, [emblaApi, onSelect])

  return {
    scrollNext,
    scrollPrev,
    prevBtnDisabled,
    nextBtnDisabled,
  }
}


```

There's also `useEmblaDots` which helps me use dots.

```ts
import type { EmblaCarouselType } from 'embla-carousel-react'
import { useCallback, useEffect, useState } from 'react'

export function useEmblaDots(emblaApi: EmblaCarouselType | undefined) {
  const [selectedIndex, setSelectedIndex] = useState(0)
  const [scrollSnaps, setScrollSnaps] = useState<number[]>([])

  const scrollTo = useCallback(
    (index: number) => emblaApi?.scrollTo(index),
    [emblaApi]
  )

  const onInit = useCallback((_emblaApi: EmblaCarouselType) => {
    setScrollSnaps(_emblaApi.scrollSnapList())
  }, [])

  const onSelect = useCallback((_emblaApi: EmblaCarouselType) => {
    setSelectedIndex(_emblaApi.selectedScrollSnap())
  }, [])

  useEffect(() => {
    if (!emblaApi) return

    onInit(emblaApi)
    onSelect(emblaApi)
    emblaApi.on('reInit', onInit)
    emblaApi.on('reInit', onSelect)
    emblaApi.on('select', onSelect)
  }, [emblaApi, onInit, onSelect])

  return {
    scrollTo,
    scrollSnaps,
    selectedIndex,
  }
}
```

These hooks receive the Embla API as a parameter and return only the necessary states and functions for plug and play.

The point is, these hooks help me a lot on a daily basis, and I end up having to copy and paste the same thing in several different projects. And I think this could be something useful for other React developers.

### Describe the solution you would like

If this were valid for the philosophy of the library, I would love to see these hooks implemented in the Embla-react lib.

### Additional context

If you think it's valid, I might be doing a PR to start something about it.

**Comment by davidjerleke** [comment]
Hi @MarlonPassos-git,

Thanks a lot for your ideas. Would you mind creating a [new discussion](https://github.com/davidjerleke/embla-carousel/discussions/new?category=ideas) and moving the content in this issue to that discussion? I think it's better to discuss this before we create an issue. I'll share my thoughts as soon as you've done that.

Thanks for understanding!

Best,
David
