### ISSUE TITLE
After running for a while 'cannot read properties of undefined' error is thrown

### ISSUE THREAD

**Issue by jjachowski** [davidjerleke/embla-carousel#541]
### Bug is related to

- [x] embla-carousel (core package)
- [x] embla-carousel-react
- [x] embla-carousel-autoplay

### Embla Carousel version

- embla-carousel-react: 8.0.0-rc11
- embla-carousel-autoplay": 8.0.0-rc11

### Describe the bug

- After leaving carousel with autoplay plugin for a longer while (up to 30 minutes) 'cannot read properties of undefined' error is thrown. 
![embla-autoplay-error](https://github.com/davidjerleke/embla-carousel/assets/84469968/f5d9cd18-91e7-4ca6-ae43-11a9c6b1b935)
- Setting autplay plugin options `delay: 1` instantly reproduces bug
<img width="616" alt="image" src="https://github.com/davidjerleke/embla-carousel/assets/84469968/e96f5cea-0756-4853-8c0f-6077c34e01e7">

### CodeSandbox

- [The link to a CodeSandbox that demonstrates the bug clearly.](https://codesandbox.io/s/embla-carousel-generator-react-forked-mmn923?file=/package.json:413-492) 
- embla generator was used to generate this example, with options: React + Typescript, horizontal, left to right, loop, slide size  100, slide gaps 10, center, previous and next buttons, dot navigation, autoplay plugin.

### Steps to reproduce

1. Open link in the browser
2. Wait
3. Error should be thrown after longer while
4. Can be reproduced instantly by setting `delay: 1` to autoplay options
<img width="616" alt="image" src="https://github.com/davidjerleke/embla-carousel/assets/84469968/a30dd9a0-6881-4f09-9ad1-105fb4f209f6">

### Expected behavior

- Type Error shown on screenshot should not appear after leaving carousel on autoplay

### Additional context

- It can take long time to see this bug, last time I tried to recreate it, it took me over 30 minutes. You can leave browser window in the background. 
- From my understanding `undefined` value is being passed to `normalizeInput` function. Then in ternary operator we try to `.get()` on this undefined value.
<img width="582" alt="image" src="https://github.com/davidjerleke/embla-carousel/assets/84469968/59749e0e-6898-4bd2-a83a-2bdaae9d409f">

**Comment by davidjerleke** [comment]
Hi @jjachowski,

Thank you very much for a complete bug report. I’ll investigate this when possible.

Best,
David

**Comment by hmartiins** [comment]
Hi! I would like to give feedback that this error has already appeared in the error monitoring of my site as well, but we did not have time to stop to investigate to conclude that it was the embla that was logging this error.

![image](https://github.com/davidjerleke/embla-carousel/assets/51277667/235adf37-3a3f-48b8-aee5-448a46661875)

**Comment by davidjerleke** [comment]
@jjachowski please try [this CodeSandbox](https://codesandbox.io/s/embla-carousel-generator-react-forked-d2sdg4) and see if the problem is solved there.

Thanks in advance.

Best,
David

**Comment by jjachowski** [comment]
@davidjerleke looks great, thank you very much for that fix :)

**Comment by davidjerleke** [comment]
@jjachowski thanks for confirming 👍. The bug fix will be released with v8.0.0-rc12.

Cheers,
David

**Comment by davidjerleke** [comment]
@hmartiins, @jjachowski, a bug fix for this has been released with [v8.0.0-rc12](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc12).
