### ISSUE TITLE
TS Error for CallbackType of EventHandlerType

### ISSUE THREAD

**Issue by evgencode** [davidjerleke/embla-carousel#563]
### Bug is related to

- [x] embla-carousel (core package)

### Embla Carousel version

- v7.1.0

### Describe the bug

I'm trying to use such code: 

```
const onSelect = (emblaApi: EmblaCarouselType) => {
    // some actions with the emblaApi...
};
emblaApi.on('reInit', onSelect);
```

I'm getting TS error:

`TS2345: Argument of type '(api: EmblaCarouselType) => void' is not assignable to parameter of type 'CallbackType'.   Types of parameters 'api' and 'evt' are incompatible.     Type 'string' is not assignable to type 'EmblaCarouselType'.       Type 'string' is not assignable to type 'EmblaCarouselType'.`

on this:

`emblaApi.on('reInit', onSelect);`

In the file `embla-carousel/components/EventHandler.d.ts` the callback parameter is specified as: `export type EmblaEventType = 'init' | 'pointerDown' | 'pointerUp' | 'scroll' | 'select' | 'settle' | 'destroy' | 'reInit' | 'resize';`
but in fact the emblaApi object (EmblaCarouselType) gets into the function

**Comment by davidjerleke** [comment]
Hi @evgencode,

Thank you for your bug report. This is not a bug. The documentation is always for the latest version which at the time of writing is [v8.0.0-rc12](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc12). v7 is a major version behind the latest release and that means breaking changes.

Best,
David
