### ISSUE TITLE
Scroll to slide based on id not index

### ISSUE THREAD

**Issue by SidNewman** [davidjerleke/embla-carousel#564]
Hi there,

Is it possible to use the ```scrollTo()``` method to go to a slide by its id or custom data attribute as apposed to its index position?

Essentially I have a drop down variant selector for a few products on a project of mine, and when clicked - the value on the selected option would match a slide ID and then scroll to that slide.

Hopefully that makes sense

TIA

**Comment by davidjerleke** [comment]
Hi @SidNewman,

Thanks for your question. These kind of questions are better suited for a [discussion](https://github.com/davidjerleke/embla-carousel/discussions/new?category=q-a). Please create a new discussion and move the content there.

Thank you for understanding!

Best,
David

**Comment by SidNewman** [comment]
Cheers, moved

**Comment by SidNewman** [comment]
Cheers, moved
