### ISSUE TITLE
Help for a beginner

### ISSUE THREAD

**Issue by drenina** [davidjerleke/embla-carousel#577]
Hi, 
I would like to use Embla on my Wordpress site, but it is not working at all unfortunately. I am no developer but tried to insert the js and css but still nothing is sliding.
@davidjerleke is there an email I could message you to show you my issues?

Thank you so much!

**Comment by davidjerleke** [comment]
Hi @drenina,

Thank you for your question. I don’t provide free service’s on top of maintaining this library and the developer documentation, unless there’s anything that I can benefit from like:

- Financial compensation for my time.
- Anything else that I would benefit from like exposure of the library. For example, if you’re the author of a fairly popular Wordpress theme or similar that could qualify.

Thank you for understanding.

Best,
David
