### ISSUE TITLE
Displaying "empty" slides when the number of slides is not divisible by slidesToScroll

### ISSUE THREAD

**Issue by lockr7** [davidjerleke/embla-carousel#583]
### Feature request is related to

- [x] embla-carousel (core package)
- [x] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation)
- [ ] embla-carousel-docs (generator)

### Is your feature request related to an issue?

- Currently when I have slidesToScroll = 3 but only 5 slides (or any other combination, like slidesToScroll = 5 but only 8 slides), I get this behavior where it doesn't actually scroll 3 slides but only scrolls until the 5th slide is the last displayed

<img width="946" alt="image" src="https://github.com/davidjerleke/embla-carousel/assets/22669712/5a6969f4-e701-4f72-9085-b49c7d3af96d">

### Describe the solution you'd like

- When I have slidesToScroll = 3 but only 5 slides (or any other combination, like slidesToScroll = 5 but only 8 slides), I want the first 3 slides to be visible and then on drag or on next button click, I want only the 4th and 5th slide to be visible with the 6th slot left empty/blank

<img width="868" alt="image" src="https://github.com/davidjerleke/embla-carousel/assets/22669712/0bebea4a-6056-4c71-b9c0-655d2de8c18a">

### Describe alternatives you've considered

- This may already be possible, but I couldn't figure it out. I tried changing containScroll but didn't seem to help.

**Comment by davidjerleke** [comment]
Hi @lockr7,

Thank you for your question. Please create a [new discussion](https://github.com/davidjerleke/embla-carousel/discussions/new?category=q-a) if you have questions about how to achieve something. It's better to start there. You can copy paste the contents of this issue to your discussion.

Best,
David

**Comment by lockr7** [comment]
Ah apologies, will do!
