### ISSUE TITLE
Add an event for option active on breakpoints

### ISSUE THREAD

**Issue by drewlonious** [davidjerleke/embla-carousel#592]
### Feature request is related to

- [X] embla-carousel (core package)

### Is your feature request related to an issue?

- There should be an event emitted for when embla is active so embla can resume the normal grid

### Describe the solution you'd like

- on('active'), () => your code here

### Describe alternatives you've considered

- you can init the carousel on certain breakpoints checking browser width but this can be simplified by adding the on 'active' event

**Comment by davidjerleke** [comment]
Hi @drewlonious,

Thank you for your feature request. From now on, please always create a [new discussion](https://github.com/davidjerleke/embla-carousel/discussions/new?category=q-a) and discuss stuff before you create a new issue. 

With that said, you can achieve what you want like so:

```ts
function doSomethingWhenActiveOrNot(emblaApi) {
  const { active } = emblaApi.internalEngine().options
  // do what you want here
}

doSomethingWhenActiveOrNot(emblaApi)
emblaApi.on('reInit', doSomethingWhenActiveOrNot)
```

Best,
David

**Comment by drewlonious** [comment]
@davidjerleke Oh there it is. Thanks for this. Noted about discussion
