### ISSUE TITLE
Slides sizes doesnt account for gap with cssgrid + flexbox (incorrect CSS setup)

### ISSUE THREAD

**Issue by drewlonious** [davidjerleke/embla-carousel#593]
### Bug is related to

- [X] embla-carousel (core package)

### Embla Carousel version

- v8.0.0-rc14

### Describe the bug

- Slide sizes work only when gap isn't used. otherwise renders partial for the last slide

### Steps to reproduce

Set slides size to 20% to reproduce

### Expected behavior
- Should be 5 slides fully visible instead of the 5th slide being partially shown

### Additional context

<img width="1507" alt="Screenshot 2023-10-09 at 3 13 16 PM" src="https://github.com/davidjerleke/embla-carousel/assets/47552877/2bf5cd9b-2cb2-4451-b51d-983dce7386ff">

**Comment by davidjerleke** [comment]
Hi @drewlonious,

Please provide a CodeSandbox that clearly demonstrates the problem. Your issue will be deleted otherwise. This is clearly stated in the contribution guidelines.

Thanks for cooperating.

Best,
David

**Comment by drewlonious** [comment]
@davidjerleke https://codesandbox.io/s/embla-carousel-default-vanilla-forked-zz3jl4?file=/src/css/embla.css

using css grid slider doesnt account for gap

calculates correctly with margin-left/margin-right however

**Comment by davidjerleke** [comment]
Hi @drewlonious,

Thank you for the CodeSandbox. This isn't a bug but I rather think your math is a bit off. The following CSS says that:

```css
.embla__container {
  /* ...other styles */
  grid-auto-columns: 20%;
  grid-column-gap: 2rem;
}
```

- Each slide should be `20%` wide.
- Gap between each slide should be `2rem`s.

**The total of this is:** (20% * 5 slides = 100%) + (2rem * 4 gaps = 8rem). There are 4 gaps between all 5 slides = 100% + 8rem > 100 (which is more than the viewport width of 100%). So just change your CSS to this and you're good to go:

```diff
.embla__container {
  /* ...other styles */
- grid-auto-columns: 20%; <-- remove this
+ grid-auto-columns: calc(20% - 2rem * 0.8); <-- add this
  grid-column-gap: 2rem;
}
```

Best,
David

**Comment by drewlonious** [comment]
@davidjerleke This seems like a very unintuitive solution. Gap in CSS grid doesn't effect total width of grid items unlike flexbox. 

You want users of Embla to write calculations like this for a simple slider that uses more than > 1 per row

`
--slide-gap: 1rem;
--slides-per-row: 1;
--slides-per-row-tablet: 2;
--slides-per-row-desktop: 5

.embla__container {
grid-auto-columns: calc((100% / var(--slides-per-row-desktop, var(--slides-per-row-tablet, var(--slides-per-row, 1)))) - (var(--slide-gap, 0) * (var(--slides-per-row-desktop, var(--slides-per-row-tablet, var(--slides-per-row))) - 1) / 10));} 

`

**Comment by davidjerleke** [comment]
@drewlonious Embla Carousel isn’t just another carousel library. It’s different in many ways. It has almost no side effects in contrast other libraries doing all sorts of stuff to your DOM elements. That’s one reason it’s so lightweight. Another benefit is that it gives you the total freedom of setting up your elements and CSS any way you want.

Now to answer your question about what you call an “unintuitive” solution, you have to remember that you picked that solution. Not me. There are ways to get around the tedious way of calculating slide sizes and spacings. If you know how CSS works it’s easily solved. 

One solution is to use the negative margin on the container and padding left hack and the spacings between the items will always be included in the slide widths, so you can just set different slide widths based on different breakpoints without worrying about calculating stuff. Here’s an [example demonstrating that approach](https://www.embla-carousel.com/examples/generator/).

**Comment by Poylar** [comment]
@davidjerleke Hello, this was not very clear to me either.
Perhaps the fact is that the documentation does not say anything about this, maybe it is worth supplementing it with a short version of your message above?

**Comment by davidjerleke** [comment]
@Poylar the guides section in the docs will get a total rewrite when I have the time. Until then, feel free to submit a PR with an explanation where you think it would help.

As mentioned before all examples including the carousel generator uses the padding approach [mentioned here](https://github.com/davidjerleke/embla-carousel/issues/593#issuecomment-1760771682) so you can see how it’s solved there.

Best,
David
