### ISSUE TITLE
In next js production environment dragForce is NaN, flickering behavior doesn't work

### ISSUE THREAD

**Issue by nikitalarionov** [davidjerleke/embla-carousel#596]
### Bug is related to

- [x] embla-carousel (core package)

### Embla Carousel version

- v7.1.0

### Describe the bug

- Bug only appears in NODE_ENV=production. When user trying to tap and slide with drag event it's not scrolling to destination (next slide). We use options: align: 'start', loop: true, skipSnaps: true. 
- I used chrome dev tools with production source map and debugged embla-carousel, in function up(evt) i found that variable rawForce becomes NaN in production env. When i run code in development - all is okay. Scroll behavior do what expected. 
- Also i tried to exclude all our css applied to blocks with embla.
- Also i tried to change behavior by subscribing to event and manually write drag free flickering - it's works in any env.  
- Also i tried use reInit when childrens dom nodes becomes mounted (no difference)

### CodeSandbox

- I cant reproduce bug in codeSandbox.

### Steps to reproduce

I only can reproduce bug in our closed env. We use smart component where do initialization by embla hook. Then in children component we map items to slide component. 

### Expected behavior

- RawForce should't be NaN.

### Additional context

- No idea why it's happens, maybe it just in our project, but error happens in embla. Any ideas how to going next steps to found out clear reason why it happens. 
- I can add video or some code examples of using embla in react env

**Comment by nikitalarionov** [comment]
[https://img08.rl0.ru/test/c1200x1200/stage.daily.afisha.ru/uploads/images/3/1e/31ee032176f0e2a296494349c139e386.png](screenshoot_from_dev_tools)

**Comment by nikitalarionov** [comment]
@davidjerleke I downgraded version, it's work as expected. Thank you so much for help and writing great package with clear code.

**Comment by davidjerleke** [comment]
@nikitalarionov you mean upgraded 🙂?

**Comment by nikitalarionov** [comment]
@davidjerleke If i switched from 7.1.0 to 7.0.4 it's mean downgraded, not? :) Anyway tommorow i will check everything one more time and leave comment. My team messaged me interested thing, package-lock.json affects this behavior. I used production package-lock.json with npm ci and not found difference. I think this bug need more research for me, i didn't check all things after downgrade.

**Comment by davidjerleke** [comment]
@nikitalarionov ah sorry. I thought you were using v7.0.1. That’s downgraded then. My bad. Ok, let me know when you’ve tested stuff more.

**Comment by nikitalarionov** [comment]
@davidjerleke David, i'm come back with news. When package-lock.json changes version of babel packages we got two cases (1 - Carousel work as expected, 2 - Not work). I tested 2th case in next way: i turn off minification in next js - to not uglify outcoming code. Result: all works as expected in 2th case. Because of that - you right, there are minification problem. Tested one more times with no-cache in browser, rebuilding and checking.

**Comment by nikitalarionov** [comment]
Something i need to say more. Everytime when i see minification problem - there are interested thing, chrome debugger with sourcemaps cannot find declaration and give a hint on mouse hover about some function that broked and returns NaN after minification. Its a sign, keep it on mind if you got something like. After reviewing your code, i found one thing: why you wrap Math.abs in helper with familiar name? Just interested :)

**Comment by davidjerleke** [comment]
Thanks for the additional information @nikitalarionov, 

>  turn off minification in next js - to not uglify outcoming code. Result: all works as expected in 2th case. Because of that - you right, there are minification problem.

I think it's related to the [SWC minifer](https://nextjs.org/docs/messages/swc-minify-enabled) that's supposed to be 7 times faster, but is it really better if it destroys the code it's minifying? I'm surprised that such a famous and big framework like NextJS is using a minifier that alters code. It's very annoying and shouldn't be up to Embla to solve but rather SWC.

In NextJS do you have an option to set `SWCminify: false` or similar? If yes, please try that and see if the problem persists.

> After reviewing your code, i found one thing: why you wrap Math.abs in helper with familiar name? Just interested :)

It's used in many places so this reduces the bundle size:

```ts
Math.abs(-10) // can't be minified more because it's an object method.

function mathAbs(n) {
  return Math.abs(n)
}

// 👆 can be minified into:
function a(n) {
  return Math.abs(n)
}

// and called like so:

 a(-10)
```

Best,
David

**Comment by nikitalarionov** [comment]
@davidjerleke Thank you for detailed information about rust compiler which is used in latests versions of nextJS. I tried to use option to disable it, it fallbacks to old compiler and all work as expected. I think we will disable it in our project for a while.

Also thanks for detailed answer about wrapping methods.
