### ISSUE TITLE
Nested Carousel Looping Issue on First Slide Visibility

### ISSUE THREAD

**Issue by reasat-rafio** [davidjerleke/embla-carousel#609]
I'm encountering an issue with the implementation of a nested carousel. Referring to a previous issue where a [sandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-141-eg8b1) was created to demonstrate how to use a nested carousel. I've followed the provided example, but I've encountered a specific problem when integrating a loop into the implementation.

### Issue Details:

The first slide in the nested carousel becomes invisible when attempting to drag any nested carousel slide. Only the first slide is affected by this issue, becoming invisible when interacted with, and reverts to visibility upon clicking or interaction.

**Sandbox Link:** [sandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-141-forked-86fpt7?file=/src/js/EmblaCarousel.js) 

**Screenshot:** 

![embla](https://github.com/davidjerleke/embla-carousel/assets/59998970/67670abc-1535-45cf-97d9-747c4b64ed97)

**Comment by davidjerleke** [comment]
@reasat-rafio thanks for your bug report. The nested carousel example was created some time ago and is not part of an official plugin so please continue the conversation in the following issue:

- #141 

Bug reports are only for official plugins/packages. Thanks for understanding!

Best,
David

**Comment by reasat-rafio** [comment]
Thank you for your prompt response and guidance. I'll continue the conversation in the specified issue. Much appreciated.

**Comment by davidjerleke** [comment]
- Duplicate of #141.
