### ISSUE TITLE
How to make simular effect? like cards effect in swiper.js

### ISSUE THREAD

**Issue by Poylar** [davidjerleke/embla-carousel#631]
what i mean: https://codesandbox.io/p/sandbox/sw6ctl?file=%2Fsrc%2FApp.jsx%3A1%2C1
I try a lot of examples and read many docs, but i cant do this, do tou have some examples for me, please?

**Comment by davidjerleke** [comment]
Hi @Poylar,

Please create a [new discussion](https://github.com/davidjerleke/embla-carousel/discussions/new?category=q-a) for these type of questions. You can copy paste your question to the discussion.

Thanks for understanding.

Best
David
