### ISSUE TITLE
Destroying (eg on switching page) with autoplay plugin causes error: Cannot read properties of undefined (reading 'stopOnInteraction')

### ISSUE THREAD

**Issue by tombryden** [davidjerleke/embla-carousel#643]
### Bug is related to

- [x] embla-carousel-react
- [x] embla-carousel-autoplay

### Embla Carousel version

- `v8.0.0-rc15`

### Describe the bug

Great work with this project!

Switching page (or destroying embla api) causes `Cannot read properties of undefined (reading 'stopOnInteraction')` when there are only a few elements in a carousel with the autoplay plugin. I am not sure what number of elements cause this problem - in our prod site, we are getting the error when displaying 4 slides while showing 4 at a time (flex: 0 0 25%). The example CodeSandbox shows this working with displaying 2 slides, and only having 2 slides in total, however failing with one slide with the same error.

In most cases our prod app carousels contain 5+ slides so no issues, however there are instances where 4 or less slides are being displayed in dynamically rendered carousels, causing this error.

### CodeSandbox

https://codesandbox.io/p/github/tombryden/embla-autoplay-bug/main

### Steps to reproduce

1. Open CodeSandbox link above
2. Click 'Another Page' hyperlink
3. Observe `Cannot read properties of undefined (reading 'stopOnInteraction')` error.
4. Uncomment slide 2
5. Rerun above steps and observe no error

### Expected behavior

Behaviour of the reproduction should be consistent between the two scenarios

**Comment by ciza99** [comment]
Are there any updates on this? or is this not happening in previous versions so I could temporarily downgrade?

**Comment by davidjerleke** [comment]
@ciza99 I haven’t had the time to look into it. You can try downgrading and see if that solves the problem but I don’t know that either at the time of writing.

**Comment by ciza99** [comment]
@davidjerleke I can confirm that I have no issues on version `v8.0.0-rc14`

**Comment by davidjerleke** [comment]
Thanks @ciza99 for confirming!

**Comment by davidjerleke** [comment]
Hi @ciza99,

When I include `embla-carousel-autoplay` locally in your [CodeSandbox](https://codesandbox.io/p/github/tombryden/embla-autoplay-bug/csb-phgfhl/draft/withered-grass?file=%2Fsrc%2Fapp%2Fpage.tsx%3A44%2C12-44%2C17) it seems to work as expected. Try setting the NextJS option `SWCminify: false` so it uses terser instead, and let me know if the problem persists?

Best,
David

**Comment by tombryden** [comment]
Hi @davidjerleke. Just tested including `embla-carousel-autoplay` locally which works as expected.  Setting `swcMinify: false` still fails in NextJS 14.0.4 using the packaged version of autoplay. Thanks

**Comment by davidjerleke** [comment]
@tombryden thanks for testing. I will have to investigate this further then. It’s a bit weird that including it locally works as expected…

**Comment by davidjerleke** [comment]
@tombryden I found the culprit. A bug fix is on its way...

**Comment by davidjerleke** [comment]
@tombryden a bug fix for this was just released in [v8.0.0-rc17](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc17).

**Comment by tombryden** [comment]
@davidjerleke Many thanks!
