### ISSUE TITLE
Autoplay resumes before mouse has left the carousel container with stopOnMouseEnter set to true

### ISSUE THREAD

**Issue by tombryden** [davidjerleke/embla-carousel#644]
### Bug is related to

- [x] embla-carousel-react
- [x] embla-carousel-autoplay

### Embla Carousel version

- `v8.0.0-rc15`

### Describe the bug

With stopOnMouseEnter set to `true` and stopOnInteraction set to `false`, dragging the carousel without the mouse leaving the carousel container causes autoplay to begin scrolling despite the mouse not leaving the carousel container. [Here is a gif showing this behaviour](https://gyazo.com/5d4ef4d39ff0300e5986db93dbf43811)

### CodeSandbox

https://codesandbox.io/p/github/tombryden/embla-autoplay-bug/mouse-enter-bug

### Steps to reproduce

1. Hover mouse over slide
2. Observe that autoplay stops while hovered
3. Drag slide to move to another slide
4. Observe that autoplay starts, despite mouse not leaving carousel

### Expected behavior

Autoplay should not restart after drag interaction with `stopOnMouseEnter` set to `true`

**Comment by davidjerleke** [comment]
Thanks @tombryden for a **complete** bug report. I'll look into it when I get the chance.

Best,
David

**Comment by davidjerleke** [comment]
Hi @tombryden,

Would you mind testing the following [CodeSandbox](https://codesandbox.io/p/github/tombryden/embla-autoplay-bug/csb-8dp3dl/draft/happy-wind?file=%2Fsrc%2Fapp%2Fpage.tsx%3A1%2C1 ) and see if it behaves as expected now? Please let me know if you intend to test it or not so you don't leave me hanging. Thanks! 

Best,
David

**Comment by tombryden** [comment]
Hi @davidjerleke - just tested now, seems to be working as expected. Thanks!

**Comment by davidjerleke** [comment]
@tombryden thank you for confirming 👍🏻.

Cheers,
David

**Comment by davidjerleke** [comment]
@tombryden a bug fix for this was just released in [`v8.0.0-rc16`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc16).
