### ISSUE TITLE
`EmblaOptionsType` doesn't exists in React

### ISSUE THREAD

**Issue by proninyaroslav** [davidjerleke/embla-carousel#647]
### Bug is related to

- [ ] embla-carousel (core package)
- [x] embla-carousel-react
- [x] embla-carousel-vue
- [x] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation)
- [ ] embla-carousel-docs (generator)

### Embla Carousel version

- `v8.0.0-rc15`

### Describe the bug

Since version v8.0.0-rc15,  ESLint says that the `SliderPropsOptions` type does not have a `loop` property. This happens to all properties that are in `EmblaOptionsType`:

![image](https://github.com/davidjerleke/embla-carousel/assets/7840559/420a01d6-a92b-4d8a-b9af-c1efea9fb98f)

Also because of this, `useEmblaCarousel` has the `options` argument type `Partial<OptionsType> | undefined` instead of `EmblaOptionsType | undefined`, which causes a linter error:

![image](https://github.com/davidjerleke/embla-carousel/assets/7840559/0463401c-d806-421a-a9e5-5a662fefbc35)

**Comment by davidjerleke** [comment]
Thanks @proninyaroslav,

I’ve noted this bug and already started working on it. However, thanks for creating a bug report so I can connect it to a pull request and devs can track it 👍🏻.

Best,
David

**Comment by davidjerleke** [comment]
@proninyaroslav a bug fix for this was just released in [`v8.0.0-rc16`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc16). Try it out and let me know if it's working as expected.

**Comment by proninyaroslav** [comment]
@davidjerleke 
Updated to v8.0.0-rc17 and still have this problem.

**Comment by davidjerleke** [comment]
@proninyaroslav then I suggest you create a CodeSandbox with your setup in order to demonstrate the problem. You didn’t provide one in your bug report but it’s a requirement as mentioned in the contribution guidelines.

**Comment by davidjerleke** [comment]
@proninyaroslav I think it's better to get the types directly from the main package. Because `embla-carousel` is a dependency, you can do this:

```tsx
import { EmblaOptionsType } from 'embla-carousel'; // Get it like so
import useEmblaCarousel from 'embla-carousel-react';
```

I will remove the type re-exports from the library wrappers like `embla-carousel-react`, `embla-carousel-vue` etc. and recommend this approach in the docs.

Best,
David

**Comment by KingBael09** [comment]
The problem seems to have popped up again in `8.0.0-rc17`

**Comment by davidjerleke** [comment]
@KingBael09 please read my [comment here](https://github.com/davidjerleke/embla-carousel/issues/647#issuecomment-1868273239).

**Comment by proninyaroslav** [comment]
@davidjerleke 
How can I apply `EmblaOptionsType` in case of `SliderPropsOptions`? It extends `EmblaOptionsType`, but it itself is not exported.

**Comment by proninyaroslav** [comment]
@davidjerleke 
It works, thank you.

**Comment by davidjerleke** [comment]
@proninyaroslav you should use `EmblaOptionsType` which is a partial type and not the internal exhaustive definition. Because you don’t want to pass all options every time you want to customize the carousel. Instead, you should only pass the options that aren’t default.

**Comment by KingBael09** [comment]
> @KingBael09 please read my [comment here](https://github.com/davidjerleke/embla-carousel/issues/647#issuecomment-1868273239).

Oh my bad. Thanks for pointing out.

**Comment by davidjerleke** [comment]
Turns out, [this approach](https://github.com/davidjerleke/embla-carousel/issues/647#issuecomment-1868273239) doesn’t work with `pnpm` so I need to solve this differently. Stay tuned.

**Comment by davidjerleke** [comment]
@div-cowboy, @proninyaroslav. I've added examples of how to import types to the docs. There's also information about how to do it with `pnpm`: 

- [api/options](https://www.embla-carousel.com/api/options/#typescript)  
- [api/methods](https://www.embla-carousel.com/api/methods/#typescript)
- [api/events](https://www.embla-carousel.com/api/events/#typescript)    
- [api/plugins](https://www.embla-carousel.com/api/plugins/#typescript)

> [!IMPORTANT]  
> Remember to switch to the **React tab** if you're using `embla-carousel-react` etc.

**Comment by suiboli314** [comment]
With `bun` and `shadcn` for `"embla-carousel-react": "^8.1.7",`, 
`eslint` (es2024) gives `EmblaCarouselType not found in 'embla-carousel'eslint[import/named]` when `import { EmblaCarouselType } from "embla-carousel";`. 

[<img src="https://github.com/user-attachments/assets/1b5cbd3f-2882-4a34-a2bd-af19fbb06e34" width="400"/>](https://github.com/user-attachments/assets/1b5cbd3f-2882-4a34-a2bd-af19fbb06e34)

But no complain if `import type { EmblaCarouselType } from "embla-carousel";` 

Should I 
> install `embla-carousel` as a devDependency

as `pnpm`?

**Comment by davidjerleke** [comment]
@suiboli314 yes, as the docs says:

![IMG_8363](https://github.com/user-attachments/assets/45fdb7d6-3182-420e-bb7e-ac4fa88a5fad)
