### ISSUE TITLE
Loop + scrollTo with jump occasionally fails and selected slide turns white

### ISSUE THREAD

**Issue by dlhagstroem** [davidjerleke/embla-carousel#652]
### Bug is related to

- [ ] embla-carousel (core package)
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation)
- [ ] embla-carousel-docs (generator)

### Embla Carousel version

- `v8.0.0-rc15`

### Describe the bug

Selected slide sometimes turns white when using emblaApi.scrollTo(index, true).

Prerequisites: 
1. Use option loop: true when initiating carousel
2. Call scrollTo function with jump: true

### CodeSandbox

https://xtcdzj.csb.app/

### Steps to reproduce

1. Click on thumbnail in the end
2. Click thumbnail in the start
3. Repeat until step 4
4. See that selected slide occasionally turns white

### Expected behavior

Show selected image (slide)

### Additional context

Seems to be related to the loop option some how, when carousel "takes the closest way" to the selected index.

**Comment by davidjerleke** [comment]
Hi @dlhagstroem,

Thanks for your complete bug report. I will look into this when I get the chance. 

Best,
David

**Comment by davidjerleke** [comment]
@dlhagstroem can you reproduce the bug in [this CodeSandbox](https://jqtyw2.csb.app/)? Thanks in advance!

**Comment by dlhagstroem** [comment]
@davidjerleke I gave it a hard round and no - I could not reproduce the issue in the provided sandbox :)

**Comment by davidjerleke** [comment]
@dlhagstroem thank you for testing it 👍🏻. I will release a patch including the bug fix then. Stay tuned.

Best,
David

**Comment by davidjerleke** [comment]
@dlhagstroem a bug fix for this was just released in [`v8.0.0-rc19`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc19).
