### ISSUE TITLE
Responsive slides

### ISSUE THREAD

**Issue by ccanete** [davidjerleke/embla-carousel#653]
### Feature request is related to

- [x] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation)
- [ ] embla-carousel-docs (generator)

### Is your feature request related to an issue?

I'd like to display some slide only on mobile or desktop

### Describe the solution you'd like

I have been trying to show / hide slides using CSS (display: none) but it seems to impact the slider and I end up between two slides when sliding between slides. The CSS option might not be the best one or might require some additional thoughts / guidance.

**Comment by davidjerleke** [comment]
Hi @ccanete,

Use the [`slides`](https://www.embla-carousel.com/api/options/#slides) option together with breakpoints and make sure the slides you don’t want to show don’t have any sizes. For example you can hide them with `display: none;`.

Best,
David

**Comment by ccanete** [comment]
Thanks a lot @davidjerleke for the prompt answer and sorry for the wrong channel. I'll go for discussions next time.

And great job with Embla, it's fantastic to use.
