### ISSUE TITLE
EmblaCarouselType typed as "any" by eslint.

### ISSUE THREAD

**Issue by lbenevento** [davidjerleke/embla-carousel#654]
### Bug is related to

- [x] embla-carousel (core package)
- [x] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation)
- [ ] embla-carousel-docs (generator)

### Embla Carousel version

- v8.0.0-rc15

### Describe the bug

- I have typed a function parameter as EmblaCarouselType (named import from "embla-carousel-react"). Eslint still treats it as "any".

### Expected behavior

- Eslint should be able to recognize the type.

### Additional context
![image](https://github.com/davidjerleke/embla-carousel/assets/6758238/1a7c76fd-dd2a-4792-be7e-1f0801ab878f)

**Comment by davidjerleke** [comment]
Hi @lbenevento,

This is a duplicate of:

- #647


The problem has been solved but not released yet.

Best,
David

**Comment by lbenevento** [comment]
Oh okay, sorry for the duplicate. Thank you!

**Comment by davidjerleke** [comment]
Hi @lbenevento,

Please read [this comment](https://github.com/davidjerleke/embla-carousel/issues/647#issuecomment-1868273239). Thanks.

Best,
David
