### ISSUE TITLE
Slide gaps will not automatically adjust the scroll snaps

### ISSUE THREAD

**Issue by martinsjek** [davidjerleke/embla-carousel#656]
### Bug is related to

- [x] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation)
- [ ] embla-carousel-docs (generator)

### Embla Carousel version

- v8.0.0-rc15

### Describe the bug

- Slide gaps will not automatically adjust the scroll snaps when using margin-right, like it's described in DOCS.
https://www.embla-carousel.com/guides/slide-gaps/

### CodeSandbox

https://codesandbox.io/p/sandbox/embla-carousel-generator-vanilla-forked-cvmp97?file=%2Fsrc%2Fcss%2Fembla.css

**Comment by davidjerleke** [comment]
Hi @martinsjek,

When switching from padding spacing to margins, you probably forgot to **remove** [this line](https://codesandbox.io/p/sandbox/embla-carousel-generator-vanilla-forked-cvmp97?file=%2Fsrc%2Fcss%2Fembla.css%3A14%2C1-14%2C48) on the container. Try removing it and let me know how it goes.

Best,
David

**Comment by martinsjek** [comment]
@davidjerleke Thanks for your quick response.

But when i remove margin-left from .embla__container, it does not solve the issue.

Martins

**Comment by davidjerleke** [comment]
@martinsjek what's the issue then? What are you trying to achieve?

**Comment by martinsjek** [comment]
@davidjerleke I am trying to achieve that slider is not broken, as you can see in attached photo - the slide 4 is clipped when it shouldn't be. Maybe I am doing something wrong?
![image](https://github.com/davidjerleke/embla-carousel/assets/36192919/2082dec9-5bdc-430c-8079-5abbdc7380d9)

**Comment by davidjerleke** [comment]
@martinsjek you've set **align** to `start`, meaning that slides should be aligned to the left edge of the carousel viewport, and the selected snap is 2 (third slide) which is as expected aligned to the left. Both slides don't fit inside the viewport?

**Comment by martinsjek** [comment]
@davidjerleke Yes, the issue is that the slides do not fit inside the viewport.

**Comment by davidjerleke** [comment]
@martinsjek that's because your CSS math isn't correct. I'm guessing that [this is what you want to achieve](https://codesandbox.io/p/sandbox/embla-carousel-generator-vanilla-forked-vxjj6y?file=%2Fsrc%2Fcss%2Fembla.css%3A20%2C13)?

**Comment by martinsjek** [comment]
@davidjerleke Yes, almost that. Except i want the container to prevent overflow. And adding overflow:hidden, breaks it.
Maybe we need to add that in the docs with example with spacings?

**Comment by davidjerleke** [comment]
@martinsjek adding overflow to the container isn’t a valid setup. The docs makes this 100% clear. What overflow do you want to prevent? I’m not following?

Maybe you could share a link to an example carousel (like a website or a different carousel library) so I can better understand what you want to achieve?

**Comment by martinsjek** [comment]
@davidjerleke Thanks, i made a fix, and now I want 3 slides in viewport, but it's broken again: https://codesandbox.io/p/sandbox/embla-carousel-generator-vanilla-forked-rwmghf?file=%2Fsrc%2Fcss%2Fembla.css%3A3%2C28

**Comment by davidjerleke** [comment]
This is because you need to adjust [this line](https://codesandbox.io/p/sandbox/embla-carousel-generator-vanilla-forked-cdstx9?file=%2Fsrc%2Fcss%2Fembla.css%3A16%2C1-16%2C66) if you change the slide sizes. This is a [working example](https://codesandbox.io/p/sandbox/embla-carousel-generator-vanilla-forked-cdstx9?file=%2Fsrc%2Fcss%2Fembla.css%3A16%2C1-16%2C66). 

However, **I would recommend you to use the padding approach** instead of margins, because then you don't have to worry about getting the math right as soon as you change slide sizes. Please read this:

> One solution is to use the negative margin on the container and a corresponding amount of padding-left on each slide. This way, the spacings between the items will always be included in the slide widths, so you can just set different slide widths based on different breakpoints without worrying about calculating stuff. Here’s an [example demonstrating that approach](https://www.embla-carousel.com/examples/predefined/#slides-to-scroll). Just go to that sandbox and change the `--slize-size` variable (in the `css/embla.css` file) to anything that adds up to **100%**. For example: 20%, 25%, calc(100% / 3) and you'll see.

_Originally posted by @davidjerleke in https://github.com/davidjerleke/embla-carousel/issues/593#issuecomment-1760771682_

**Comment by martinsjek** [comment]
@davidjerleke Big thanks to you, your code example fixed my issue. I'm closing this issue :)
