### ISSUE TITLE
ESM d.ts point to non-existent .ts files

### ISSUE THREAD

**Issue by NikitaIT** [davidjerleke/embla-carousel#668]
### Bug is related to

- [x] embla-carousel-react

https://github.com/davidjerleke/embla-carousel/blob/b3b8554b06100b03766d0d1dbcc503962d7aeeb4/rollup.config.js#L125-L127

### Embla Carousel version

- v8.0.0-rc15 - rc18

### Describe the bug

Incorrect ESM:

```ts
export { EmblaOptionsType } from 'embla-carousel/components/Options.ts';
export { EmblaEventType, EmblaEventListType } from 'embla-carousel/components/EventHandler.ts';
export { EmblaPluginType } from 'embla-carousel/components/Plugins.ts';
export { EmblaCarouselType } from 'embla-carousel/components/EmblaCarousel.ts';
export { UseEmblaCarouselType } from './components/useEmblaCarousel.ts';
export { default } from './components/useEmblaCarousel.ts';
```

<img width="860" alt="image" src="https://github.com/davidjerleke/embla-carousel/assets/16810067/8d678b43-c4ff-4c1b-879d-aacee77d579d">

### Expected behavior

```ts
export { EmblaOptionsType } from 'embla-carousel/components/Options';
export { EmblaEventType, EmblaEventListType } from 'embla-carousel/components/EventHandler';
export { EmblaPluginType } from 'embla-carousel/components/Plugins';
export { EmblaCarouselType } from 'embla-carousel/components/EmblaCarousel';
export { UseEmblaCarouselType } from './components/useEmblaCarousel';
export { default } from './components/useEmblaCarousel';
```

### Additional context

- Add any other context about the problem here, like screenshots or similar.

<img width="833" alt="image" src="https://github.com/davidjerleke/embla-carousel/assets/16810067/3271cc25-ecb2-4db3-aec0-b3e1ecf7a4fb">

**Comment by davidjerleke** [comment]
@NikitaIT did you search issues before creating this bug report?

- Please [read this](https://github.com/davidjerleke/embla-carousel/issues/647#issuecomment-1868273239) in the following issue #647.
