### ISSUE TITLE
Infinite scrolling issues

### ISSUE THREAD

**Issue by smultar** [davidjerleke/embla-carousel#669]
### Bug is related to

- [x] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [x] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation)
- [ ] embla-carousel-docs (generator)

### Embla Carousel version

- `v8.0.0-rc17`

### Describe the bug

- When setting loop to `true`. The carousel doesn't infinitely loop in the same direction, as the example previews or the generated versions. I'm expecting the slide to keep scrolling in the direction the user is dragging in. In this case, the slide stops at the end and goes in the opposite direction back to the start.

### CodeSandbox
[Sandbox code](https://codesandbox.io/p/devbox/xhny8m?file=%2Fsrc%2FApp.tsx%3A9%2C23)

### Steps to reproduce

1. Make a project based on embla templates.
2. Ensure the loop is set to true
3. Try swiping
4. See visual error

### Expected behavior
I'm expecting the slide to keep scrolling in the direction the user is dragging in. In this case, the slide stops at the end and goes in the opposite direction back to the start.

### Additional context
The issue doesn't appear on the code-sandbox, however it does appear with NextJS

**Comment by davidjerleke** [comment]
@smultar please [read this](https://github.com/davidjerleke/embla-carousel/issues/596#issuecomment-1761324406). Please set `SWCminify: false` and see if the problem persists.

**Comment by smultar** [comment]
![image](https://github.com/davidjerleke/embla-carousel/assets/6223536/a22845af-b3bc-47fe-85c2-e85ea6e71df8)

The issue persists, as shown 

https://github.com/davidjerleke/embla-carousel/assets/6223536/b1214fc4-dc34-46c0-932e-f65e93ddd10d

I can provide access to the source code, but its a private repository.

**Comment by davidjerleke** [comment]
@smultar please create a temporary public repository with a reduced test case. Meaning with only stuff that's necessary and unnecessary details stripped.

**Comment by smultar** [comment]
Ask and you shall receive @davidjerleke .

https://github.com/smultar/aetherlink.embla-carousel

**Comment by davidjerleke** [comment]
@smultar I haven’t had the time to setup your repository locally but I found [this line](https://github.com/smultar/aetherlink.embla-carousel/blob/30f4f4e861e014dd690325a5bd784c9b7118d253/components/slides/home/home-carousel.scss#L21). You shouldn’t add any CSS transitions to the carousel container because Embla does the transition with javascript and this will break the carousel animation.

I’m not 100% sure that this is the only thing with the setup causing the problem you describe but you need to remove the CSS transition there.

Best,
David

**Comment by smultar** [comment]
Hey @davidjerleke, you are correct, adding animations to the embla container can affect infinite scrolling.

Removing the transition effect resolves #670
