### ISSUE TITLE
Cannot swipe video elements as carousel items (slides)

### ISSUE THREAD

**Issue by SeifOwleN** [davidjerleke/embla-carousel#678]
### Bug is related to

- [x] embla-carousel-react

### Embla Carousel version

- `v8.0.0-rc18`

### Describe the bug

cannot swipe video elements used as carousel items

### CodeSandbox

https://codesandbox.io/p/sandbox/embla-carousel-default-react-forked-7zsrhv

### Steps to reproduce

1- add a carousel slide item
2- add video element then try to swipe

### Expected behavior

being able to swipe like normal carousel slide

**Comment by davidjerleke** [comment]
@SeifOwleN thanks for your bug report. Are the video elements iframes?

**Comment by SeifOwleN** [comment]
no, its just a normal video tag like this
```tsx
 <video width="x" height="y" controls>
  <source src="movie.mp4" type="video/mp4">
  Placeholder
</video> 
```

**Comment by davidjerleke** [comment]
@SeifOwleN thanks. I wasn’t able to see the CodeSandbox for mysterious reasons. Isn’t this how the video tag is supposed to work? If you want it to be swipeable you need to remove the controls attribute and add custom controls.

Best,
David

**Comment by davidjerleke** [comment]
@SeifOwleN have you read [my comment](https://github.com/davidjerleke/embla-carousel/issues/678#issuecomment-1878210636)?

**Comment by SeifOwleN** [comment]
sorry, haven't noticed. yeah i did search more and implemented a custom video player and it actually worked thanks 🥰

**Comment by davidjerleke** [comment]
@SeifOwleN thank you for confirming 👍!
