### ISSUE TITLE
error on build

### ISSUE THREAD

**Issue by mehdiraized** [davidjerleke/embla-carousel#680]
### Bug is related to

- [x] embla-carousel (core package)
- [x] embla-carousel-react

### Embla Carousel version

- v8.0.0-rc18

### Describe the bug
```
Type error: '"embla-carousel-react"' has no exported member named 'EmblaCarouselType'. Did you mean 'UseEmblaCarouselType'?

> 1 | import { EmblaCarouselType } from 'embla-carousel-react';
```

### Steps to reproduce

1. run 'npm run build'
2. See error

**Comment by davidjerleke** [comment]
@mehdiraized a friendly reminder: If you didn’t, please search for existing issues before creating a new issue. 

Duplicate of:

- #647
