### ISSUE TITLE
Types warning in (TS + React) CodeSandbox template

### ISSUE THREAD

**Issue by zaaakher** [davidjerleke/embla-carousel#684]
I hate to be the bearer of bad news but codesandbox **might** be using pnpm under the hood 😅

### Bug is related to

- [x] embla-carousel-docs

### Embla Carousel version

- `8.0.0-rc19`

### Describe the bug

- The generated **(React + TS)** codesandbox shows a warning it's not recognizing `embla-carousel` (see image below)

![image](https://github.com/davidjerleke/embla-carousel/assets/46135573/84fe8f54-8a51-46d3-85ee-9419b60f8263)

### Steps to reproduce

1. Go to the [predefined examples page](https://www.embla-carousel.com/examples/predefined/)
2. Click on "edit code" in any of the examples
3. Choose "**React + Typescript**" and create the sandbox
4. Open a file that's importing a type from `embla-carousel` package
5. See the TS warning like in the image above

### Expected behavior

- No TS warnings should exist.

**Comment by zaaakher** [comment]
> codesandbox might be using pnpm under the hood

This is only a theory, I couldn't verify it.

**Comment by davidjerleke** [comment]
@zaaakher thanks! Did you try creating a sandbox  locally and could verify that the problem went away 🙂?

**Comment by zaaakher** [comment]
> Did you try creating a sandbox locally and could verify that the problem went away 🙂?

I just tested it locally and the problem is still there. I will investigate further

**Comment by davidjerleke** [comment]
@zaaakher I’m pretty sure that CodeSandbox handles dependencies differently because if I spin up a new npm or yarn project locally and import the types from the core package when using the react wrapper, it just works.

**Comment by zaaakher** [comment]
Yup, that's why I assumed they're using `pnpm` under the hood.

They might have their own custom dependency resolution handlers that work similarly to `pnpm`

**Comment by davidjerleke** [comment]
@zaaakher agree. Even `pnpm` works with the core package in `devDependencies`. I guess we have to add it to regular dependencies just for the CodeSandboxes then. Special case.
