### ISSUE TITLE
ClassNames plugin does not have a variable slideIndexes which is breaking integration

### ISSUE THREAD

**Issue by mdunbavan** [davidjerleke/embla-carousel#686]
### Bug is related to

- [ ] embla-carousel (core package)
- [ ] embla-carousel-react
- [x] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [x] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation)
- [ ] embla-carousel-docs (generator)

### Embla Carousel version

"embla-carousel-vue": "^8.0.0-rc19"

### Describe the bug

I have installed the ClassNames plugin with the vue setup but when I add it into the code I get this error:

`embla-carousel-class-names.js?v=56e245a8:86 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')`

This references this file, which is looking for slideIndexes but it does not appear to be there.

https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel-class-names/src/components/ClassNames.ts

- A clear and concise description of what the bug is.

### CodeSandbox

https://codesandbox.io/p/sandbox/nifty-chatterjee-jsq2nt

### Steps to reproduce

1. Install Vue embla plugin
2. Setup as per docs.
3. Install ClassNames plugin, integrate plugin in code.
4. Reload carousel and see the issue.

### Expected behavior

- The class names should appear on the slides and this is not happening.

### Additional context

Here is my code:

Template for slides:

```
<div class="embla featured__lg-content" ref="emblaNode">
      <div class="embla__container">
        <div
          class="embla__slide"
          v-for="(featuredItem, index) in featuredItems"
          :key="index"
        >
          <div class="mx-16">
            <TutorCard :tutor="featuredItem" class="z-10" />
          </div>
        </div>
      </div>
      <div @click="goPrev" class="featured__slider-arrow-prev">
        <LogArrowW></LogArrowW>
      </div>
      <div @click="goNext" class="featured__slider-arrow-next">
        <LogArrowW></LogArrowW>
      </div>
    </div>
```

Here is the vue js code for it:

```
setup() {
    const classNamesOptions = { selected: "my-selected-class" }
    const [emblaNode, emblaApi] = emblaCarouselVue(
      {
        loop: true,
        draggable: true,
        speed: 10,
        slidesToScroll: 1,
        skipSnaps: false,
        containScroll: "trimSnaps",
        align: "center",
        selectedClass: "is-selected",
        draggableClass: "is-draggable",
        startIndex: 0,
      },
      [ClassNames(classNamesOptions)]
    )
    const featuredItems = ref({})
    const selectedItem = ref({})
    const current = ref(1)
    const loading = ref(true)

    const goNext = () => {
      emblaApi.value.scrollNext()
    }

    const goPrev = () => {
      emblaApi.value.scrollPrev()
    }

    const getFeatured = async () => {
      try {
        await apiService(`api/tutors/featured`)
          .get()
          .json()
          .then((response) => {
            console.log(response)
            featuredItems.value = response.data.value
            selectedItem.value = featuredItems.value[0]
          })
        // set loading to false
        loading.value = false
      } catch (e) {
        console.log(e)
      }
    }
    onMounted(async () => {
      await nextTick()
      getFeatured()
    })
    return {
      emblaNode,
      featuredItems,
      selectedItem,
      loading,
      goNext,
      goPrev,
    }
  },
```

Thanks,
Mark

**Comment by mdunbavan** [comment]
@davidjerleke typical I added it in a codesandbox and it works.
I think the main difference is that I am using vite to build out the site, which I think is causing the issue

**Comment by davidjerleke** [comment]
@mdunbavan thanks for the additional details. That’s interesting. You can create a Vite project in a CodeSandbox. 

Alternatively, please provide a temporary GitHub repository with instructions on how to reproduce the problem.

**Comment by davidjerleke** [comment]
@mdunbavan do you intend to pursue this? Thanks.

**Comment by davidjerleke** [comment]
@mdunbavan last call.

> [!IMPORTANT]  
> This issue will be **deleted** if I don’t get a response soon.

**Comment by mdunbavan** [comment]
@davidjerleke sorry about the slow reply.

I can create a Vite project in codesandbox defo, I will do that tomorrow for you.

**Comment by davidjerleke** [comment]
@mdunbavan thanks. I created a Vite project locally and still couldn’t reproduce the problem. Please don’t forget to share steps to reproduce the problem if you create a CodeSandbox.

Thanks!
