### ISSUE TITLE
Init event not fired in SSR (React / NextJS)

### ISSUE THREAD

**Issue by StevenVerbiest** [davidjerleke/embla-carousel#689]
### Bug is related to

- [x] embla-carousel-react

### Embla Carousel version

- v8.0.0-rc19

### Describe the bug

The `.on("init")` event is not invoked when used in a useEffect in a SSR component.

### CodeSandbox

https://stackblitz.com/edit/stackblitz-starters-syez5k?file=app%2FEmblaComponent.tsx
https://stackblitzstarterssyez5k-c0ir--3000--f7aa08df.local-credentialless.webcontainer.io/

```
const [emblaRef, emblaApi] = useEmblaCarousel();

useEffect(() => {
  if (!emblaApi) return;

  emblaApi.on('init', () => {
    console.log('init');
  });
}, [emblaApi]);
```

### Steps to reproduce

1. Open the Stackblitz webcontainer
2. Open the console
3. There is no `'init'` log

The log _is_ shown after a hot reload. If you see the init log, do a hard refresh. 

### Expected behavior

The init event should always fire.

**Comment by davidjerleke** [comment]
@StevenVerbiest I can't access the link you shared. Would you mind double checking it?

Best,
David

**Comment by davidjerleke** [comment]
@StevenVerbiest thanks for pointing me to the source files, that worked. I believe you should read this to better understand why it's happening:

- [init event](https://github.com/davidjerleke/embla-carousel/discussions/379#discussioncomment-3759962) in #379.
- [SSR](https://github.com/davidjerleke/embla-carousel/issues/600#issuecomment-1767817848).

Best,
David

**Comment by StevenVerbiest** [comment]
Thanks for the info. I'm also having some other issues related to SRR regarding to special layouts, but I won't go into detail since it's unrelated to this issue. I like Embla, but not supporting SSR is an issue for me, so I will sadly need to look for an alternative.
Will definitely try Embla for my CSR projects and wil try to keep an eye for SRR support in the future. 
Cheers!

**Comment by davidjerleke** [comment]
@StevenVerbiest thanks. Although Embla doesn't run its script on the server, it still allows rendering the HTML and CSS on the server side.
