### ISSUE TITLE
Impossible to sync Autoplay's playing state using events

### ISSUE THREAD

**Issue by mykytabatrak** [davidjerleke/embla-carousel#690]
### Bug is related to

- [ ] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [x] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation)
- [ ] embla-carousel-docs (generator)

### Embla Carousel version

v8.0.0-rc19

### Describe the bug

`"autoplay:play"` and `"autoplay:stop"` events are dispatched before the `playing` variable is changed, which makes it impossible to synchronise react state with autoplay state

### CodeSandbox

[Codesandbox](https://codesandbox.io/p/sandbox/embla-carousel-generator-react-forked-2yrffy?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A20%2C27)

### Steps to reproduce

1. Click the "Stop" button
2. Observe the carousel stop but state change not being detected

### Expected behavior

I would expect those events to be dispatched after the corresponding variable is set. just like with other events.

**Comment by davidjerleke** [comment]
@mykytabatrak why not do it [like this](https://codesandbox.io/p/sandbox/embla-carousel-generator-react-forked-x9kwqz?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A5%2C3)?

Best,
David

**Comment by mykytabatrak** [comment]
@davidjerleke after looking at your approach and re-reading react docs on `useEffect`, I think you are right. For some reason I was fixated on using `useSyncExternalStore` for implementing this, it worked just fine for `canScrollPrev` and `canScrollNext`, and I just couldn't let it go.

Thank you so much, I believe you can close this issue now.
