### ISSUE TITLE
[Bug]: export the types

### ISSUE THREAD

**Issue by omarkhatibco** [davidjerleke/embla-carousel#715]
Hey David, I hope you have a nice day

### Version

v8.0.0-rc20

### Steps to reproduce

I just updated from `rc15` to `rc20` and I noticed that the exported types where removed 

before I was able to import them directly from `embla-carousel-react` and now I have explicity install and import them from `embla-carousel`

### Expected Behavior

I should be able to import them like this 

```ts
import { EmblaCarouselType, EmblaOptionsType, EmblaPluginType } from 'embla-carousel-react'
```

### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by preetmishra** [comment]
Hey, @omarkhatibco! I had a similar issue. This helped: https://github.com/davidjerleke/embla-carousel/issues/647.

**Comment by omarkhatibco** [comment]
@preetmishra thank for mentioning the other issue, I will close this one now
