### ISSUE TITLE
[Bug]: Event Hooks Do Not Get Called With Next 12 + React 18

### ISSUE THREAD

**Issue by ranno-lauri** [davidjerleke/embla-carousel#730]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

When trying to upgrade React and Next to latest versions the bug occurs when using the latest pre-release version of the libary and Next 12/13/14 + React 18. Event callbacks are called correctly with React 17.x.x and Next 12.x.x. For testing purposes it easiest to stay on Next 12, but only pump React and the issue will appear.

## React 18 behaviour
1. Open the sandbox
2. Check in package.json, verify React/Next versions to be:
```
    "next": "^12.x.x",
    "react": "^18.x.x",
    "react-dom": "^18.x.x",
```
3. Run `pnpm install` if changess were needed
4. Restart/start dev server
5. Open /components/EmblaCarousel.tsx
6. See `emblaApi.on` callbacks for events inside useEffect that should log the "init" event on first render (as it does if using React 17) and for other events
7. Open browser console
8. See only "~ in effect" log.
9. Refresh
10. See only '~ in effect" log again.
    
## React 17 behaviour
1. Open the sandbox
2. Check in package.json, verify React/Next versions to be:
```
    "next": "^12.x.x",
    "react": "^17.x.x",
    "react-dom": "^17.x.x",
```
3. Run `pnpm install` if changess were needed
4. Restart/start dev server
5. Open /components/EmblaCarousel.tsx
6. See `emblaApi.on` callbacks for events inside useEffect that should log the "init" event on first render and for other events
7. Open browser console
8. See both "~ in effect"  and "Called event init" log.

    

### Expected Behavior

Event callbacks/hooks are called the same way with React 18/Next 14 as with React 17/Next 12

### Additional Context

Tried the same example with only pure React 18 and it worked as expected. Issues come when React is pumped together with Next (as Next 13 requires React 18, they can't be done separately). This seems more like Next's issue, but I have little hope of them fixing this and would greatly appreciate it if something could be done from this side.

### What browsers are you seeing the problem on?

All browsers

### Version

8.0.0-rc22

### CodeSandbox

https://codesandbox.io/p/devbox/next-minimal-embla-xc65tv

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
Hi @ranno-lauri,

Thanks for the report. If you're unsure something is a bug or not, you can create a discussion instead.

**Comment by davidjerleke** [comment]
Hi @ranno-lauri,

Thanks for the bug report. If you're unsure something is a bug or not, you can create a [discussion](https://github.com/davidjerleke/embla-carousel/discussions/new?category=help) instead. To **answer your question**, there's a gotcha with the `init` event and `embla-carousel-react.` Please read this to understand it:

- https://github.com/davidjerleke/embla-carousel/discussions/379#discussioncomment-3759962

As far as I can see, all other events are working as expected in your CodeSandbox. For example, if you drag the carousel and wait for it to stop, it will fire the `settle` event.

Best,
David

**Comment by ranno-lauri** [comment]
Hey @davidjerleke,

Thank you for the reply and suggestions. Tried it out and works as expected. Problem solved! Should this be included as 'gotcha' in the documentation?

**Comment by davidjerleke** [comment]
@ranno-lauri thanks for confirming.

I'm not sure which solution would be optimal. I've been considering removing the `init` event because it feels like it has been causing more confusion than anything else 😅. For example, when using Vanilla JS, you can just run any code after invoking the `EmblaCarousel()` constructor and the carousel will be ready. So the `init` event might be redundant:

```tsx
// Vanilla JS
import EmblaCarousel from 'embla-carousel'

const emblaNode = document.querySelector('.embla')
const emblaApi = EmblaCarousel(emblaNode)

console.log('INIT - Embla is ready')

// React JS
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel() {
  const [emblaRef] = useEmblaCarousel({ loop: true })

  useEffect(() => {
    if (!emblaApi) return
    
    console.log('INIT - Embla is ready')
  }, [emblaApi])
  // ...
}
```

What's your thoughts about this?

Best,
David

**Comment by ranno-lauri** [comment]
Indeed, caused quite a bit of confusion. That's the general emotion with `useEffect` and React 18 has just made it worse 😆. Using `useEffect` instead of 'init' would be habitual for React devs. To make migrations from React 17 -> 18 easier for others, would still be useful to have the information in the documents, but add a deprecation note to the 'init' method (both in docs and in code), so new implemenations would not use it.

**Comment by davidjerleke** [comment]
Thanks for your input @ranno-lauri!
