### ISSUE TITLE
[Bug]: When the direction is set to 'rtl' and the loop is set to true, it doesn't loop infinitely

### ISSUE THREAD

**Issue by akashrajum7** [davidjerleke/embla-carousel#761]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

When the direction is set to 'rtl' and the loop is set to true, it doesn't loop infinitely.

### Expected Behavior

The slides should loop infinitely without any issues

### Additional Context

I first noticed it when using in sveltekit and tried to reproduce it using codesandbox and I was able to successfully reproduce it. Since I did not have a quick example to use, I have used the react example.

### What browsers are you seeing the problem on?

Chrome

### Version

v8.0.0

### CodeSandbox

https://codesandbox.io/p/sandbox/embla-carousel-auto-scroll-react-forked-mpdt9k

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
Hi @akashrajum7 and thank you for your bug report.

You haven't set your markup to `rtl` anywhere in your code. Here's a [working sandbox](
https://codesandbox.io/p/sandbox/embla-carousel-auto-scroll-react-rtl-452w4g?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A68%2C28-68%2C37). **A friendly reminder:** Before submitting a bug report, there's a checkbox that says the following:

<img width="1117" alt="checkbox" src="https://github.com/davidjerleke/embla-carousel/assets/11529148/f37cf469-9204-4b7a-8f38-946e91f4180c">

So it's important to at least read about the options you're using in the docs. In your case [direction](https://www.embla-carousel.com/api/options/#direction), which clearly says this:

<img width="679" alt="rtl" src="https://github.com/davidjerleke/embla-carousel/assets/11529148/1d4bedd2-88cd-465e-8d7c-1de40596b4de">

Best,
David
