### ISSUE TITLE
[Bug]: canScrollNext method returns false even when there are items to scroll

### ISSUE THREAD

**Issue by bansal1789** [davidjerleke/embla-carousel#762]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

The bug occurs when I use Fluent V9 Arrow Navigation hook. [https://react.fluentui.dev/?path=/docs/utilities-focus-management-usearrownavigationgroup--default](url)

Applied this hook inside the viewport into the container and canScrollNext() method started giving false.

### Expected Behavior

canScrollNext() method should return true when there are slides on the right

### Additional Context

I have also tried...

### What browsers are you seeing the problem on?

Chrome

### Version

v8.0.0-rc11

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@bansal1789 what's going on here?
