### ISSUE TITLE
[Bug]: AutoScroll position jumps when clicked and dragged

### ISSUE THREAD

**Issue by jasonk16** [davidjerleke/embla-carousel#764]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [X] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

I've recently updated the carousel to version 8.0.0. The carousel shifts its position when I click and drag the carousel, with autoscroll enabled. Based on my observation so far, it tends to happen if the mouse has entered the carousel, where it stops scrolling, and the user clicks and drags. It does not happen when my mouse quickly enters and drags the carousel. 

https://github.com/davidjerleke/embla-carousel/assets/59631071/f3ca12f0-1ff4-40ef-812d-0cd34a46df44

### Expected Behavior

Carousel should not shift its position when clicked and dragged. 

### Additional Context

I'm using Nextjs 14 with app router.

### What browsers are you seeing the problem on?

Chrome

### Version

8.0.0

### CodeSandbox

https://codesandbox.io/p/sandbox/embla-carousel-auto-scroll-react-forked-lkvshs?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
Hi @jasonk16,

Thanks for your bug report. Have you seen the [example](https://www.embla-carousel.com/examples/predefined/#auto-scroll) in the docs? Can you reproduce it there? If no, please check how to work with the plugin there.

Best,
David

**Comment by jasonk16** [comment]
Thanks for your quick reply. I've reproduced the jumpyness based on the example [here](https://codesandbox.io/p/sandbox/embla-carousel-auto-scroll-react-replication-3d4r3v), I've just changed the individual items to suit my needs, which is an image container.

**Comment by davidjerleke** [comment]
@jasonk16 thanks! I'll investigate what's going on when possible.

Best,
David

**Comment by jasonk16** [comment]
Your assumption is correct. I've just tried removing the anchor tags from the cards and it does not jump anymore. Perhaps I could use `onClick` on divs as a workaround temporarily, but long term I guess its not a good html semantics if those cards are links. 

I also tried nesting the anchor tag within the div but I guess the focus still triggers on click. Let me know if theres anything you'd need my help on. Thanks again!

**Comment by MuhamedAyoub** [comment]
@davidjerleke 
Does not working

Try starting the carousel and then attempt to drag it. It will stop.

**Comment by davidjerleke** [comment]
@MuhamedAyoub please ask for [help here](https://github.com/davidjerleke/embla-carousel/discussions/new?category=help) instead of bloating this issue. And please share more information so I can understand what you’re having problems with, like a screen recording and similar.

**Comment by davidjerleke** [comment]
> Perhaps I could use onClick on divs as a workaround temporarily, but long term I guess it's not a good html semantics if those cards are links.

@jasonk16 you're right about that. It's not good semantics so a solution for this is needed. I'm working on a new option called `watchFocus` which will enable you to either disable/enable the auto focus feature with a `boolean`. Alternatively, you will be able to pass your own callback to control when Embla should focus or not: Similar to [`watchDrag`](https://www.embla-carousel.com/api/options/#watchdrag), [`watchResize`](https://www.embla-carousel.com/api/options/#watchresize) and [`watchSlides`](https://www.embla-carousel.com/api/options/#watchslides).

Unfortunately, until then, you'll have to stick with the hacky solution you mentioned.

Best,
David

**Comment by jasonk16** [comment]
Oh yeah, something like `watchFocus` would be beneficial. Thanks a lot for coming up with a fix. I'll just go with the hacky solution for now but happy to help if you'd need me to test anything.

**Comment by davidjerleke** [comment]
Thanks @jasonk16. It would definitely help if you wouldn’t mind testing as soon as I have a draft ready. I’ll let you know when I have something 👍🏻.

**Comment by davidjerleke** [comment]
@jasonk16 and @4l3x91 you could try upgrading to `v8.2.0`. If that doesn't solve the problem, you can now modify or opt-out of the auto focus behavior using the `watchFocus` options released [v8.2.0 release](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.2.0).

**Comment by davidjerleke** [comment]
@jasonk16 and/or @4l3x91, let me know if you intend to test if the bug is solved as [described here](https://github.com/davidjerleke/embla-carousel/issues/764#issuecomment-2298227683).

**Comment by sb-relaxt-at** [comment]
@davidjerleke We do no longer have this jumping issue after upgrading to the latest version. In our case it has not been necessary to modify `watchFocus`. Thanks a lot (for this nice library and your fix)!

**Comment by davidjerleke** [comment]
@sb-relaxt-at thanks a lot for testing and confirming that the fix is working 👍🏻.

**Comment by jasonk16** [comment]
Hey @davidjerleke, sorry for the delay. I've upgraded to `v8.2.1` and so far there is no more focus issues when I wrap my items in an anchor. Thank you so much for fixing it!

**Comment by davidjerleke** [comment]
@jasonk16 thanks for confirming. Enjoy 🎉.
