### ISSUE TITLE
[Bug]: Autplay stops working after drag

### ISSUE THREAD

**Issue by DanielSpindler** [davidjerleke/embla-carousel#779]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

The bug occurs when I use the Autoplay plugin and i drag a slide.

### Expected Behavior

The Autoplay should continue after i dragged a slide. 

### Additional Context

I have also tried...
```
export default ({ news, storeQuery }: Props) => {
  const { locale, countryCode } = storeQuery.currentStore;
  const [emblaRef] = useEmblaCarousel({ loop: true, duration: 75 }, [
    Autoplay({ delay: 5000, jump: true }),
  ]);

  return (
    <div className="min-w-0 overflow-hidden  " ref={emblaRef}>
      <div className="flex">
        {news.map(({ slug, image: { url, alt }, subtitle, title }) => {
          return (
            <Link
              key={slug}
              href={`/${countryCode}/${locale}/collection/${slug}`}
              className="relative w-full flex-shrink-0 flex-grow-0"
            >
              <ImageWithFallback src={url} alt={alt} origin="cms" width={1920} height={750} />
              <div className="absolute bottom-0 left-0 right-0 m-4 text-l24-white lg:mb-8 lg:ml-8">
                <h2 className="text-base font-bold sm:text-2xl lg:text-4xl">{title}</h2>
                <p className="text-base sm:text-2xl lg:text-4xl">{subtitle}</p>
              </div>
            </Link>
          );
        })}
      </div>
    </div>
  );
};
```

### What browsers are you seeing the problem on?

All browsers

### Version

v8.0.0

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
Hi @DanielSpindler,

A friendly reminder: Please make an effort and read the docs before creating a bug report. This is simply a matter of setting the Autoplay option [stopOnInteraction](https://www.embla-carousel.com/plugins/autoplay/#stoponinteraction) to `true`.
