### ISSUE TITLE
[Bug]: Cannot find module 'embla-carousel/components/Options' or its corresponding type declarations. TypeScript, React with Vite

### ISSUE THREAD

**Issue by rxtsel** [davidjerleke/embla-carousel#780]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

It seems that the issue stems from the way `OptionsType` is imported in the` useEmblaCarousel.d.ts` file within the `embla-carousel-react` folder in `node_modules`. Instead of importing directly from `'embla-carousel/components/Options'`, it should be imported directly from the `EmblaOptionsType` type.

### Expected Behavior

![expect](https://github.com/davidjerleke/embla-carousel/assets/85462420/2043f427-099b-4e6c-96f0-7e363336ead0)

### Received behavior

![return](https://github.com/davidjerleke/embla-carousel/assets/85462420/862b1672-1694-4dc0-a01d-fe1d442a8e92)

### Additional Context

The bug occurs when I build:

![image](https://github.com/davidjerleke/embla-carousel/assets/85462420/381b7504-3d55-4646-b1a2-b3b9743ef7f4)

### Version

v8.0.0

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
Hi @rxtsel,

Thanks for the bug report. It seems like many devs are having this problem. 

- See this: https://github.com/davidjerleke/embla-carousel/discussions/726#discussioncomment-8331396

Setting `moduleResolution` to `node` in `tsconfig` seems to solve it, but I don’t know why yet.

> It seems that the issue stems from the way `OptionsType` is imported in the` useEmblaCarousel.d.ts` file within the `embla-carousel-react` folder in `node_modules`. Instead of importing directly from `'embla-carousel/components/Options'`, it should be imported directly from the `EmblaOptionsType` type.

Have you tried your solution? 
Which package manager are you using?

- Could be related to #778 

Best,
David

**Comment by rxtsel** [comment]
Hi @davidjerleke,

Thanks for responding.

Indeed, changing the value of `moduleResolution` from `bundler` to `node` worked for me. Thank you very much, we can close this issue, although it would be good if it detected whether that line is needed and added it or changed the value if necessary. Or simply add it to the documentation.
