### ISSUE TITLE
[Bug]: Direction rtl reverses y axis direction

### ISSUE THREAD

**Issue by nahasco** [davidjerleke/embla-carousel#784]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

The bug occurs when I set the direction option value to "rtl"

### Expected Behavior

For a vertical carousel, the functionality of the prevscroll and nextscroll should'nt be reversed if the direction is set to "rtl". The direction property should only affect the functionality of horizontal carousels.

### What browsers are you seeing the problem on?

All browsers

### Version

v8.0.0-rc15

### CodeSandbox

https://codesandbox.io/p/sandbox/embla-carousel-y-axis-react-forked-mr4d2l?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A19%2C20

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@nahasco thanks for your bug report. I’ve actually seen this before so I can instantly confirm that this is a bug. I will work on this when possible.

This is a case we’re adding tests when fixing the bug will be mandatory.

Best,
David

**Comment by nahasco** [comment]
> @nahasco thanks for your bug report. I’ve actually seen this before so I can instantly confirm that this is a bug. I will work on this when possible.
> 
> This is a case we’re adding tests when fixing the bug will be mandatory.
> 
> Best, David

Thank you! 

I will be following..

**Comment by davidjerleke** [comment]
@nahasco please try this [CodeSandbox](https://codesandbox.io/p/sandbox/embla-carousel-y-axis-rtl-bug-5chv45) and see if the problem is solved.

Thanks!
David

**Comment by nahasco** [comment]
> @nahasco please try this [CodeSandbox](https://codesandbox.io/p/sandbox/embla-carousel-y-axis-rtl-bug-5chv45) and see if the problem is solved.
> 
> Thanks! David

Tested side by side in this [CodeSandbox](https://codesandbox.io/p/sandbox/embla-carousel-y-axis-rtl-bug-5chv45) and it is perfect!

Thank you David!

**Comment by davidjerleke** [comment]
Released in [v8.0.1](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.1).
