### ISSUE TITLE
[Bug]: Angular autoplay error

### ISSUE THREAD

**Issue by sjostedtmax** [davidjerleke/embla-carousel#788]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [X] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

The bug occurs when I add the autoplay feature to a angular project, it seems to work the first time i run it. But every time after it produces this error

```
Error: node_modules/embla-carousel-autoplay/components/Autoplay.d.ts:5:9 - error TS2411: Property 'autoplay' of type 'AutoplayType | undefined' is not assignable to 'string' index type 'CreatePluginType<LoosePluginType, {}>'.  

5         autoplay?: AutoplayType;
```

I am not using the angular wrapper

### Expected Behavior

Fancy feature should have...

### Additional Context

Changing this line in embla-carousel-autoplay/components/Autplay.d.ts seems to fix the issue. Probably not a good idea.

```
   interface EmblaPluginsType {
        autoplay?: string;
    }
```

### Version

v8.0.0

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@sjostedtmax,

The `embla-carousel-angular` package is a separate repository and I'm not maintaining it. Please [create a bug there](https://github.com/donaldxdonald/embla-carousel-angular/issues/new) first. The Autoplay plugin is working fine with all other library wrappers so it could be related to the angular wrapper.

Best,
David
