### ISSUE TITLE
[Bug]: Autoplay fast scroll when opened in a new tab

### ISSUE THREAD

**Issue by mojtaba06** [davidjerleke/embla-carousel#790]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [x] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

The bug occurs when I open site on new tab without check it and after 30 seconds see the tab.

### Expected Behavior

When I visit that tab after 30 seconds, the slides should not have a fast initial scroll and the speed should be according to the settings.

### Additional Context

Hi, thank you for the useful carousel you developed,
Please open the sandbox link in a new tab and visit it after 30 seconds.
https://9xvhl9.csb.app
Good luck to you

### CodeSandbox

https://codesandbox.io/p/sandbox/embla-carousel-generator-react-9xvhl9?file=%2Fsrc%2Fjs%2Findex.tsx

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by sarussss** [comment]
Hi @mojtaba06
I think this problem is because Embla's autoplay plugin listens to the [visibilitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) event to optimize by turning off autoplay when the tab is not visible, so this is not necessarily a bug.

**Comment by davidjerleke** [comment]
@mojtaba06 thanks for your bug report. 

I think I have a pretty good idea what's causing this. Will let you know when I've had the chance to look into it. 

Best,
David

**Comment by mojtaba06** [comment]
Hi @sarussss, thank you for your comment. Good luck.

**Comment by davidjerleke** [comment]
@mojtaba06 would you mind testing if you can reproduce the problem in [this CodeSandbox](https://codesandbox.io/p/sandbox/790-4f3998)?

**Comment by mojtaba06** [comment]
@davidjerleke Sure, I've tested the CodeSandbox, and the issue has been resolved. Thank you and good luck.

**Comment by davidjerleke** [comment]
Released in [v8.0.1](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.1).
