### ISSUE TITLE
[Bug]: Embla Carousel's animation becomes less smooth when the battery saving mode is enabled.

### ISSUE THREAD

**Issue by SzymonGonet** [davidjerleke/embla-carousel#811]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [X] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

When you implement Embla Carousel and activate "battery saving mode," the smoothness of the animation tends to diminish.

### Expected Behavior

The animation should be smooth.

### What browsers are you seeing the problem on?

All browsers

### Version

v8.0.0

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@SzymonGonet thanks for your bug report. This isn’t a bug but rather how requestAnimationFrame is designed. See:

- #676
