### ISSUE TITLE
[Bug]: Render when slides are wider than view size

### ISSUE THREAD

**Issue by ferka123** [davidjerleke/embla-carousel#815]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

The bug occurs when the windows width is 325px or when i resize it to less than 325px
The error: `TypeError: Cannot read properties of undefined (reading 'right')`
I left a codesandbox below

### Expected Behavior

I expect it to work properly on any window width

### Additional Context

I use next.js 13 with styled components

### What browsers are you seeing the problem on?

Chrome

### Version

v. 8.0.0

### CodeSandbox

https://codesandbox.io/p/devbox/funny-williams-y3cdy8

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by ferka123** [comment]
It doesn't occur if i remove slidesToScroll: "auto"

**Comment by davidjerleke** [comment]
@ferka123 I've checked your CodeSandbox out and can confirm that this will be solved with:

- #805

**Comment by ferka123** [comment]
@davidjerleke Thank you! This would be most helpful

**Comment by davidjerleke** [comment]
@ferka123 this has been released in [v8.0.2](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.2).
