### ISSUE TITLE
[Bug]: When using the wheel gesture to swipe the carousel, for the first slide and the last slide, there are excessive blank space.

### ISSUE THREAD

**Issue by xnslx** [davidjerleke/embla-carousel#819]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

I am using the wheel gesture plugin combined with the embla core plugin, I noticed that for using the wheel gesture, there is excessive blank space if you swipe the first slide and the last slide in the wrong direction. 

https://github.com/davidjerleke/embla-carousel/assets/51500554/60f90c5d-2910-4c99-a3a0-f04385a91983

### Expected Behavior

I am wondering that is it possible to make, for the first slide to lock the left side which should not be swipped by the user and also for the last slide which lock the right side. I hope to make the carousel feel sharper, right now it feels quite floppy. Using [Zara](https://www.zara.com/us/) as an example.

### Additional Context

I have also tried...

### What browsers are you seeing the problem on?

Chrome

### CodeSandbox

https://codesandbox.io/p/devbox/github/xiel/embla-carousel-wheel-gestures/tree/master/docs/react

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@xnslx please move this question to discussions because this is expected behavior and therefore not a bug.

**Comment by xnslx** [comment]
Hey @davidjerleke After digging this issue a little bit, I think I find a similar issue that opened by others long time ago and you answer here, https://github.com/davidjerleke/embla-carousel/issues/42#issuecomment-895850425  Thank you so much. I am gonna move this to discussion. Thank you!🙏
