### ISSUE TITLE
[Bug]: Jest testing bug return TypeError: undefined is not a function

### ISSUE THREAD

**Issue by KareyM** [davidjerleke/embla-carousel#837]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

When writing test for the `EmblaCarousel`, i'm getting this error. Not sure what it is that's causing the issue. However, it seem to work just fine within the browser

```ts
TypeError: undefined is not a function
        at Array.map (<anonymous>)

      110 |   const DELAY = 4000;
      111 |   const plugins = [EmblaCarouselAutoplay({ delay: DELAY })];
    > 112 |   const emblaApi = EmblaCarousel(emblaNode, options, plugins);
          |                                 ^
      113 |   return emblaApi;
      114 | };
      115 |
```

### Expected Behavior

During a test, calling `EmblaCarousel` should behave the same work it does during the browser

### Additional Context

I'm using the TS version of this and downloaded it through `yarn`

### Version

v8.0.2

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@KareyM this is not a bug. You need to mock the following API:s to solve the problem:

- `IntersectionObserver`
- `matchMedia`
- `resizeObserver`

Feel free to [grab the mocks](https://github.com/davidjerleke/embla-carousel/tree/master/packages/embla-carousel/src/__tests__/mocks) that the core library `embla-carousel` is using.

Best,
David

**Comment by KareyM** [comment]
Thank you!!
