### ISSUE TITLE
[Bug]: Fade example missing dependency and missing vanilla examples 

### ISSUE THREAD

**Issue by meirroth** [davidjerleke/embla-carousel#877]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [X] embla-carousel-docs **(Generator)**

### Steps to reproduce

Click **edit source** then select the React CodeSandbox and you should see it fails to run due to missing `embla-carousel-fade` dependency. This is probably is quick fix and I would be willing to create a PR if you point me in the right direction.
Also, I think the Vanilla examples are missing.

### Expected Behavior

Fancy feature should have...

### Additional Context

I have also tried...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@meirroth thanks for noticing! You’re right. It’s missing [here](https://github.com/davidjerleke/embla-carousel/blob/9ac755ba911657e10a59de36eee108ce96e6bfc3/packages/embla-carousel-docs/src/consts/sandbox.ts#L112).

Best,
David

**Comment by meirroth** [comment]
@davidjerleke Thank you. I'll try.

**Comment by richgcook** [comment]
I think this is true outside of examples. I've tried to install the fade plugin with the latest version of embla and get the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: embla-carousel@8.1.0
npm ERR! node_modules/embla-carousel
npm ERR!   peer embla-carousel@"8.1.0" from embla-carousel-auto-scroll@8.1.0
npm ERR!   node_modules/embla-carousel-auto-scroll
npm ERR!     embla-carousel-auto-scroll@"^8.0.4" from the root project
npm ERR!   peer embla-carousel@"8.1.0" from embla-carousel-class-names@8.1.0
npm ERR!   node_modules/embla-carousel-class-names
npm ERR!     embla-carousel-class-names@"^8.0.4" from the root project
npm ERR!   2 more (embla-carousel-reactive-utils, embla-carousel-vue)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! embla-carousel-fade@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: embla-carousel@8.0.2
npm ERR! node_modules/embla-carousel
npm ERR!   peer embla-carousel@"8.0.2" from embla-carousel-fade@8.1.0
npm ERR!   node_modules/embla-carousel-fade
npm ERR!     embla-carousel-fade@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by meirroth** [comment]
@richgcook The new Fade plugin works just fine for me locally. Would you mind please opening a new issue with a minimal reproduction so we can debug?

**Comment by richgcook** [comment]
@meirroth I am using the "embla-carousel-vue": "^8.0.4" if that's maybe the issue... but yes can do!

**Comment by davidjerleke** [comment]
@richgcook yes please match the plugin version with the core package version.

**Comment by richgcook** [comment]
@davidjerleke Thanks for the response. I've tried this but still get an error when trying to npm install embla-carousel-fade

```
"embla-carousel-auto-scroll": "^8.1.0",
"embla-carousel-class-names": "^8.1.0",
"embla-carousel-vue": "^8.1.0",
```

```
npm ERR! While resolving: undefined@undefined
npm ERR! Found: embla-carousel@8.1.0
npm ERR! node_modules/embla-carousel
npm ERR!   peer embla-carousel@"8.1.0" from embla-carousel-auto-scroll@8.1.0
npm ERR!   node_modules/embla-carousel-auto-scroll
npm ERR!     embla-carousel-auto-scroll@"^8.1.0" from the root project
npm ERR!   peer embla-carousel@"8.1.0" from embla-carousel-class-names@8.1.0
npm ERR!   node_modules/embla-carousel-class-names
npm ERR!     embla-carousel-class-names@"^8.1.0" from the root project
npm ERR!   2 more (embla-carousel-vue, embla-carousel-reactive-utils)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! embla-carousel-fade@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: embla-carousel@8.0.2
npm ERR! node_modules/embla-carousel
npm ERR!   peer embla-carousel@"8.0.2" from embla-carousel-fade@8.1.2
npm ERR!   node_modules/embla-carousel-fade
npm ERR!     embla-carousel-fade@"*" from the root project
```

**Comment by davidjerleke** [comment]
@richgcook [this line is the problem](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel-fade/package.json#L62). I will solve it as soon as possible.

**Comment by davidjerleke** [comment]
@richgcook I just released a bug fix. Please try bumping all your Embla packages to [`v8.1.3`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.1.3) and let me know how it goes.

**Comment by richgcook** [comment]
@davidjerleke Yep all perfect :) Thanks!
