### ISSUE TITLE
[Bug]: Image disperses after window resize

### ISSUE THREAD

**Issue by halibegic** [davidjerleke/embla-carousel#881]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [X] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

1. Navigate to the next slide in the carousel.
2. Resize the window.
3. Notice that the image is missing after the window resize.

### Expected Behavior

After resizing the window, the image should remain visible

### Additional Context

Recorded the issue for reference.
https://github.com/davidjerleke/embla-carousel/assets/3328291/a7982844-4da5-4d39-bd24-b60f1aa4719d

### What browsers are you seeing the problem on?

Chrome

### Version

8.1.1

### CodeSandbox

https://codesandbox.io/p/sandbox/embla-carousel-fade-react-3fz67z?file=%2Fpackage.json

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
Thanks @halibegic! A bug fix for this was released in [`v8.1.2`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.1.2).
