### ISSUE TITLE
[Bug]: verticle view slider - last slider is not appearing above first slider by default

### ISSUE THREAD

**Issue by pragadesh-tartlabs** [davidjerleke/embla-carousel#896]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

The bug occurs in verticle slider when I try to display last slider above my first slider with some top margin on load(https://codesandbox.io/p/sandbox/embla-carousel-y-axis-react-forked-4ckh7h?file=%2Fsrc%2Fjs%2Findex.tsx%3A11%2C73) it only visible when i slightly scroll to top, in  horizontal view it is working like charm (https://codesandbox.io/p/sandbox/embla-carousel-autoplay-react-forked-pq4pq7?file=%2Fsrc%2Fcss%2Fembla.css%3A15%2C48) 

### Expected Behavior

verticle slider loop functionality  needs to look like horizontal loop slider

Example:
![image (39)](https://github.com/davidjerleke/embla-carousel/assets/110020189/baa1b6fd-b389-48d2-bf26-52302f7bb1ba)

verticle slider issue (i already made necesary css changes)
![image](https://github.com/davidjerleke/embla-carousel/assets/110020189/bdbbc3f6-ae2e-4dd3-8936-38021329aca9)
![image (40)](https://github.com/davidjerleke/embla-carousel/assets/110020189/a2f6ef41-dc29-4c12-9729-fec985fd713b)

### What browsers are you seeing the problem on?

Chrome

### CodeSandbox

https://codesandbox.io/p/sandbox/embla-carousel-y-axis-react-forked-4ckh7h?file=%2Fsrc%2Fjs%2Findex.tsx%3A11%2C73

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@pragadesh-tartlabs please make your CodeSandbox public. I can’t access it.

**Comment by davidjerleke** [comment]
@pragadesh-tartlabs this is not a bug. Don't add margins to the container (embla__container) because that's the scroll container. Add spacing to the slides instead.
