### ISSUE TITLE
Drag threshold is too high on wide screens

### ISSUE THREAD

**Issue by jordie23** [davidjerleke/embla-carousel#90]
I'm playing around with the carousel. I have it set up to be a large carousel, so full width on a large screen. When you drag the current slide, it bounces back. You have to drag really far in order for the slide to progress. Is there a way to set a smaller drag distance? Even on dragFree mode, it'll bounce back without a large amount of dragging. 

I had a look at the options and as far as I can see there's no way to change this, unless I've missed something?

**Comment by davidcetinkaya** [comment]
Hi @jordie23,
Do you want to pursue this?

Kindly 
David

**Comment by davidcetinkaya** [comment]
Closing this due to lack of response. Feel free to re-open this issue if you want to pursue this @jordie23.

Best
David

**Comment by davidjerleke** [comment]
Solution will be a min/max drag threshold limit:

- Discussed [here](https://github.com/davidjerleke/embla-carousel/issues/25#issuecomment-1406963359) and [here](https://github.com/davidjerleke/embla-carousel/issues/25#issuecomment-1476502439)

**Comment by davidjerleke** [comment]
To be released with **v8.0.0-rc01**.

**Comment by davidjerleke** [comment]
@jordie23 and @silllli a fix for this has been released with [v8.0.0-rc01](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc01).

**Comment by silllli** [comment]
> @jordie23 and @silllli a fix for this has been released with [v8.0.0-rc01](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc01).

Thank you @davidjerleke!
