### ISSUE TITLE
[Bug]: "Smoothness" of Slide Transitions feels degraded between 8.1.5 and 8.1.6

### ISSUE THREAD

**Issue by taylorfsteele** [davidjerleke/embla-carousel#928]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

1. Go to any example found via the docs in codesandbox. E.g., Vanilla + TypeScript: https://codesandbox.io/s/xkygsv
2. Fork the sandbox, and pin embla-carousel in `package.json` to `8.1.5`. Restart to recompile the sandbox: https://codesandbox.io/s/embla-carousel-default-vanilla-forked-vqr66k?file=/package.json
3. Compare the slide transitions between the two. 8.1.5 is noticeably "smoother" (at least to my eye).

### Expected Behavior

The performance and "feel" of the slide transitions should be that of 8.1.5.

### Additional Context

I could be completely off-base here, but I can definitely notice a difference between the two versions. Maybe I have super eyes or it's a 1st world problem with high refresh monitors 😆 

### What browsers are you seeing the problem on?

Chrome

### Version

8.1.6

### CodeSandbox

https://codesandbox.io/s/xkygsv

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@taylorfsteele thanks for noticing!

Your observation is correct! This will be fixed in `8.1.7` and I’m hoping to make it even a bit smoother than `8.1.5`. So please use `8.1.5` and stay tuned because there are no new actual features in `8.1.6` anyway.

**Comment by taylorfsteele** [comment]
Appreciate the fast reply! Glad to know it wasn't just me, I thought I might have been going crazy looking at these slight differences.

Let me know if I can provide any assistance, I just pulled the repo down to attempt a fix: My first instinct was that somehow removing this [lag offset callback](https://github.com/davidjerleke/embla-carousel/pull/926/files#diff-204e39eec44543ffbc1806f72da44a8521a61c8d93ff616eecf77d9a105253f6L208) accidentally broke something somewhere, but that didn't work for me. 

Regardless, if I can provide some form of help or contribution, I'm happy to do so 🙂

**Comment by davidjerleke** [comment]
> Regardless, if I can provide some form of help or contribution, I'm happy to do so 🙂

@taylorfsteele thanks for being helpful! Would you mind testing the following sandbox and see if the smoothness is back?

- [Sandbox](https://rfz8hd.csb.app/)

**Comment by taylorfsteele** [comment]
> > Regardless, if I can provide some form of help or contribution, I'm happy to do so 🙂
> 
> @taylorfsteele thanks for being helpful 👍! Would you mind testing the following [sandbox](https://rfz8hd.csb.app/) and see if the smoothness is back?

This looks really good to me! 🙌

**Comment by davidjerleke** [comment]
@taylorfsteele thanks a lot fot testing the sandbox 🙂. I'll let you know when I've released the bug fix with `v8.1.7`.

**Comment by davidjerleke** [comment]
@taylorfsteele, @rakyi, a bug fix for this has been included in the [v8.1.7](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.1.7) release.

**Comment by rakyi** [comment]
Thanks a lot, David! Embla is great.
