### ISSUE TITLE
[Bug]: GH-Pages Demo Links Broken

### ISSUE THREAD

**Issue by MarketingPip** [davidjerleke/embla-carousel#939]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

Go to the demo / website and click the example links etc...

### Expected Behavior

Should go to the correct page.

### Additional Context

I have also tried...

### What browsers are you seeing the problem on?

All browsers

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@MarketingPip please share some example links with screenshots so we can find them.

**Comment by MarketingPip** [comment]
@davidjerleke - hey! My apologizes. I somehow ended up on OLD page [here](https://davidcetinkaya.github.io/embla-carousel/). Meaning not sure if this issue is relevant.

**Comment by davidjerleke** [comment]
@MarketingPip I didn’t find that link when searching this repository so it’s quite old. That link was in use before I bought `www.embla-carousel.com`.

I don’t know where you found it but if it’s included in a post on a website or similar you need to contact the post author so they can update it.

Best,
David
