### ISSUE TITLE
When using Infinite Scroll, click the next button, the slides doesn't go to next page if there are slides to load.

### ISSUE THREAD

**Issue by QinshanSun** [davidjerleke/embla-carousel#941]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

The bug occurs when I use the Infinite Scroll example, if user keep clicking the next button from 5 to 6 slide, this issue should happen.

I am not sure if this behaviour is by design. But next button can't go to next page which also leads to some misunderstanding.

### Expected Behavior

when user click the next button from 5 to 6 slide, it should go to 6 slide page, not just stuck at 5/6 slides like this: 
![Screenshot 2024-07-17 at 14 38 29](https://github.com/user-attachments/assets/f1954659-a4f3-4f7a-8f6b-01176eac6dae)

### Additional Context

I have also tried...

### Version

v8.1.6

### CodeSandbox

https://codesandbox.io/s/7xy8jg

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@QinshanSun thanks for your bug report. If you’re unsure if it’s a bug or by design, I would recommend you to create a [new discussion](https://github.com/davidjerleke/embla-carousel/discussions/new?category=help) instead of a bug report.

**Comment by QinshanSun** [comment]
Hi @davidjerleke,

thanks for reply,  i will close this issue and create a new discussion.
