### ISSUE TITLE
[Bug]: Class Names plugin occour error when we use page transition library

### ISSUE THREAD

**Issue by bozdevs** [davidjerleke/embla-carousel#945]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [X] embla-carousel-auto-height
- [X] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

The bug occurs when I use "auto-height" and/or "class-names" plugin.

- I have use "Page transition library ([https://swup.js.org/](https://swup.js.org/))" on my project. It's change DOM elements when visit a link. In this case JS works once. For this I am `destroy` Embla instance and `init` it again, you can see below.
- If I use one instance it will work correctly but If I use one-more Embla instance, `embla-carousel-class-names` will occour an error, you can see below.

##### Console
![image](https://github.com/user-attachments/assets/0f223938-75f9-4393-86df-5f35060e92d3)
##### Source
![image](https://github.com/user-attachments/assets/4e904c5c-342c-4179-83a4-b6e7dc9e2e95)

### General logic

```js
   const emblaInstance = function() { ... }

   emblaInstance(); // First page load, first embla init
   document.addEventListener('swup:page:load', emblaInstance); // Swup page load, I init embla
   document.addEventListener('swup:content:replace', function(){ // Before Swup content replace, I destroy embla instance
       emblaInstance.destroy();
   }, {before: true});
```

If you duplicate the above example with more than one Embla slider instance, it will start to give errors during page transitions.

If I remove Embla Plugins from all code everything works fine. For plugins, is it necessary to call a separate "destroy" method along with "`emblaInstance.destroy()`"?

### Expected Behavior

Embla instances should be destroyed before [Swup](https://swup.js.org/hooks/) changes each page, and they should work again after changing the page.

### Additional Context

I have also tried... remove Embla plugins from project, it was work normal.

### What browsers are you seeing the problem on?

All browsers

### Version

v8.1.6

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@bozdevs thanks for your question,

> If I remove Embla Plugins from all code everything works fine. For plugins, is it necessary to call a separate "destroy" method along with `"emblaInstance.destroy()"`?

No it's not.

> If I use one instance it will work correctly but If I use one-more Embla instance, `embla-carousel-class-names` will occour an error, you can see below.

I see. I have nothing to debug in your issue description and no relevant code. If it's working with one instance and not with multiple instances, it's likely the problem is on your side. Make sure to create a new plugin instance for every separate carousel and don't re-use the same instance.

Please create a proper bug report as described in the [contributing guidlines](https://github.com/davidjerleke/embla-carousel/blob/master/CONTRIBUTING.md#bug-reports). You need to provide a CodeSandbox with a minimal reproduction of the bug meaning no production site with a lot of noise.

**Comment by davidjerleke** [comment]
@bozdevs did you solve the problem? Why did you close the issue?

**Comment by bozdevs** [comment]
No, I will create codesandbox and open it again. In the meantime, I'll try a few things.
