### ISSUE TITLE
[Bug]: If elements are generated through the template tag, the positioning of the first element does not work correctly

### ISSUE THREAD

**Issue by slavamirgit** [davidjerleke/embla-carousel#951]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

Instead of physically adding each element, use the template tag.
For example, using Alpinejs:
```
<template x-for="(num, i) in slides">
  <div class="embla__slide">
    <div class="embla__slide__number" x-text="num"></div>
  </div>
</template>
```

### Expected Behavior

The first element must be correctly positioned.

### What browsers are you seeing the problem on?

All browsers

### CodeSandbox

https://codesandbox.io/s/embla-carousel-generator-vanilla-forked-6zsrgp?file=/index.html

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by slavamirgit** [comment]
Found the same problem in the previously posted. Sorry

https://github.com/davidjerleke/embla-carousel/issues/73

**Comment by davidjerleke** [comment]
Hi @slavamirgit,

How is this a bug? This is expected behavior as stated in the [docs](https://www.embla-carousel.com/api/options/#slides). If you’re unsure this if something is a bug or not, please create a discussion to begin with.

Just use the [`slides`](https://www.embla-carousel.com/api/options/#slides) option as described [here](https://github.com/davidjerleke/embla-carousel/issues/440#issue-1610346044).

**Comment by slavamirgit** [comment]
Yeah, I found it. With the "slides" option works fine. Thank you!
