### ISSUE TITLE
[Bug]: `useEmblaCarousel` initializes Embla with stale options in certain cases

### ISSUE THREAD

**Issue by lesha1201** [davidjerleke/embla-carousel#980]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

The issues happens when `useEmblaCarousel` creates `EmblaCarousel` (`emblaApi`) at the same time when `options` have changed. It happens because of `useEffect` order

Here is an example: https://codesandbox.io/p/devbox/embla-carousel-stale-options-dw88yj

If you open the example on small viewport (less than 1024px in width) then the issue appears and Embla Carousel wrongly initialized with `watchDrag: false` instead of `watchDrag: true`.

https://github.com/user-attachments/assets/bb667a4b-f776-47ec-8960-7f948753aa61

### Expected Behavior

Embla Carousel should be initialized with the latest options.

### Additional Context

I have also tried...

### What browsers are you seeing the problem on?

All browsers

### Version

v8.2.0

### CodeSandbox

https://codesandbox.io/p/devbox/embla-carousel-stale-options-dw88yj

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by lesha1201** [comment]
I will open PR shortly.

**Comment by davidjerleke** [comment]
@lesha1201 why aren’t you using the [breakpoints](https://www.embla-carousel.com/guides/breakpoints/#changing-options) option?

**Comment by davidjerleke** [comment]
@lesha1201 thanks. I will look into this when possible.

**Comment by davidjerleke** [comment]
@lesha1201 thanks. Your PR solves the problem.

**Comment by davidjerleke** [comment]
@lesha1201 this bug fix was released in [`v8.2.1`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.2.1).
